### PR TITLE
fix: CURLRequest request body is not reset on the next request

### LINKED ISSUE #5632: Bug: Curl request body not resetting
### PHP Version

8.1

### CodeIgniter4 Version

4.1.7

### CodeIgniter4 Installation Method

Composer (as dependency to an existing project)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### Database

_No response_

### What happened?

image

### Steps to Reproduce

image

### Expected Output

The body of the second request should be empty because I did not add any parameters to the curl body.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by kenjis**
**Description**
Fixes #5632

**Checklist:**
- [x] Securely signed commits
- [] Component(s) with PHPDoc blocks, only if necessary or adds value
- [x] Unit testing, with >80% coverage
- [x] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

File: tests/system/HTTP/CURLRequestDoNotShareOptionsTest.php [hunk 1]
```diff
@@ -807,6 +807,21 @@ public function testApplyBody()
         $this->assertSame('name=George', $request->curl_options[CURLOPT_POSTFIELDS]);
     }
 
+    public function testBodyIsResstOnSecondRequest()
```
Comment (samsonasik) [inline tests/system/HTTP/CURLRequestDoNotShareOptionsTest.php:810]: Typo : Resst -> Reset

Comment (kenjis) [reply tests/system/HTTP/CURLRequestDoNotShareOptionsTest.php]: Oh, Thanks.
Fixed.

**Review by samsonasik — APPROVED** [review]
