### PR TITLE
Fix incorrect html output caused by escaping

### LINKED ISSUE #4235: Bug: Wrong HTML code in output of "form_input" helper function
**Describe the bug**
When using the "form_input" helper function with these example parameters:
<pre>
&lt;?php
$identity = [
	'name' =>  'identity',
	'id'   =>  'identity',
	'type' =>  'email',
	'value' => ''
];
echo form_input($identity, '', array('class' => 'form-control form-control-lg'));
?&gt;
</pre>
I get the following incorrect HTML code:

<pre>
&lt;input type=&quot;email&quot; name=&quot;identity&quot;value=&quot;&quot; id=&quot;identity&quot; class=&quot;form-control&amp;#x20;form-control-lg&quot; /&gt;
</pre>

There are two errors:

1) the space between <i>name=&quot;identity&quot;</i> and <i>value=&quot;&quot;</i> is missing.
2) the value of the attribute <i>class</i> is encoded in its entirety (therefore the space becomes erroneously &amp;#x20;), when instead it should be encoded for each single value separated by a space (i.e. in this case <i>form-control</i> and <i>form-control-lg</i>)

**CodeIgniter 4 version**
4.0.4

**Affected module(s)**
The first error is in the <i>parse_form_attributes</i> function (line 947) in the helper file called <i>/system/Helpers/form_helper.php</i>
The second error is in the <i>stringify_attributes</i> function (line 1136) in the file <i>/system/Common.php</i>

**Expected behavior, and steps to reproduce if appropriate**
I expect the <i>form_input</i> function to return the following correct HTML code:

<pre>
&lt;input type=&quot;email&quot; name=&quot;identity&quot; value=&quot;&quot; id=&quot;identity&quot; class=&quot;form-control form-control-lg&quot; /&gt;
</pre>

If I may, I would propose the following solutions to the two problems:
1) replace line number 947 in the <i>form_helper.php</i> file with:
<pre>
$att .= $key . '=&quot;' . $val . '&quot;' . ($key == key(array_slice($default, -1, 1, true)) ? '' : ' ');

or for PHP >= 7.3.0:

$att .= $key . '=&quot;' . $val . '&quot;' . ($key === array_key_last($default)) ? '' : ' ');
</pre>
2) Replace line number 1136 in the <i>Common.php</i> file with:
<pre>
$atts .= ($js) ? $key . '=' . $val. ',' : ' ' . $key . '=&quot;' . $val . '&quot;'; // without any attribute escaping
</pre>

**Context**
 - OS: Windows 10
 - Web server: Apache 2.4.41
 - PHP version: 7.2.4

### PR DESCRIPTION
**Pull request by totoprayogo1916**
**Description**
Supersedes and closes #4298
fixes #4235 

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPdocs
- [x] Unit testing, with >80% coverage
- [ ] User guide updated
- [ ] Conforms to style guide

### CODE REVIEW

File: system/Helpers/form_helper.php [hunk 1]
```diff
@@ -944,7 +944,7 @@ function parse_form_attributes($attributes, array $default): string
 				{
 					continue;
 				}
-				$att .= $key . '="' . $val . '"' . ($val === end($default) ? '' : ' ');
+				$att .= $key . '="' . $val . '"' . ($key === key(array_slice($default, -1, 1, true)) ? '' : ' ');
```
Comment (paulbalandan) [inline system/Helpers/form_helper.php:947]: Can we use `array_key_last` here?

**Review by paulbalandan — APPROVED** [review]
