### PR TITLE
fix: Call to undefined method Composer\InstalledVersions::getAllRawData() error

### LINKED ISSUE #7106: Bug: Call to undefined method Composer\InstalledVersions::getAllRawData() in Autoloader.php
> PHP Fatal error:  Uncaught Error: Call to undefined method Composer\InstalledVersions::getAllRawData() in .../vendor/codeigniter4/framework/system/Autoloader/Autoloader.php:376

Ref #7101

How to Reproduce:
```console
$ composer self-update 2.0.13
$ composer create-project codeigniter4/appstarter ci4
$ cd ci4
$ php spark serve
```

### PR DESCRIPTION
**Pull request by kenjis**
**Description**
Fixes #7106

The depreacted `getRawData()` is not reliable. See https://github.com/composer/composer/commit/f5e6cc89cd8d45c99cff77ee80d0f324ada45686#diff-817f0ad18cf006ca7b25f23ddd362c0c8b5cdcbea91c4b92be8d86ba59af223aR210
So using it does not make sense.

**Checklist:**
- [x] Securely signed commits
- [] Component(s) with PHPDoc blocks, only if necessary or adds value
- [] Unit testing, with >80% coverage
- [x] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Comment by lonnieezell** [comment]
Can we do a version. Check and use the function they recommend instead of blocking execution?

File: system/Autoloader/Autoloader.php [hunk 1]
```diff
@@ -373,7 +373,16 @@ private function loadComposerNamespaces(ClassLoader $composer, array $composerPa
...
         }
 
-        $packageList = InstalledVersions::getAllRawData()[0]['versions'];
+        if (method_exists(InstalledVersions::class, 'getAllRawData')) {
+            // This method requires Composer 2.0.14 or later.
+            $packageList = InstalledVersions::getAllRawData()[0]['versions'];
+        } else {
+            throw new RuntimeException(
+                'Your Composer version is too old.'
+                . ' Please update Composer (run `composer self-update`) and remove your vendor/ directory,'
```
Comment (ddevsr) [inline system/Autoloader/Autoloader.php:382]: Give more information in Exception

```suggestion
                . ' Please update Composer (run `composer self-update`) to v2.0.14 or later and remove your vendor/ directory,'
```

Comment (kenjis) [reply system/Autoloader/Autoloader.php]: Done.

File: system/Autoloader/Autoloader.php [hunk 2]
```diff
@@ -373,7 +373,16 @@ private function loadComposerNamespaces(ClassLoader $composer, array $composerPa
...
+                . ' and run `composer update`.'
+            );
+        }
```
[the remark this answers is not in the document]
Comment (kenjis) [reply system/Autoloader/Autoloader.php]: Done.

**Comment by kenjis** [comment]
@lonnieezell 
> Can we do a version. Check and use the function they recommend instead of blocking execution?

What do you mean?
What is the function they recommend?

**Review by paulbalandan — APPROVED** [review]
