### PR TITLE
fix: QueryBuilder limit(0) bug

### LINKED ISSUE #8278: Bug: [QueryBuilder] if set limit to 0, it will return all data. Perhaps it should return 0 data.
### PHP Version

8.2

### CodeIgniter4 Version

4

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

fpm-fcgi

### Database

MariaDB 10.2.44

### What happened?

`$builder->limit(0, 0)` , set the limit => 0 and the query will shows all the table rows. It should return no rows because limit is 0.

### Steps to Reproduce

```php
$builder->limit(0,0)
```

### Expected Output

it should return no rows if it set limit to 0.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by kenjis**
**Description**
Fixes #8278

- `LIMIT` can be used in MySQL, SQLite3, PostgreSQL, and they return 0 rows when we specify `LIMIT 0`.
- `limit()` is to limit the result rows. So when we specify it, the result should be limited, not be all rows.

> LIMIT 0 quickly returns an empty set. This can be useful for checking the validity of a query.
https://dev.mysql.com/doc/refman/5.7/en/limit-optimization.html

**Checklist:**
- [x] Securely signed commits
- [x] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Comment by lonnieezell** [comment]
Um. Don't you think this has the potential to alter behavior in a major way for thousands of sites? As you said before this has always been this way in v4. And I am pretty sure I did not make any changes to the way this works when I ported the database layer over from 3.

While I understand the reporter has a valid use case I think this is probably a situation where we should say sorry, we can't that. This is way too big of a breaking change.

**Comment by kenjis** [comment]
Thank you for the comments.

I have modified the current implementation and checked to see if the tests passes, but the impact seems to be larger than expected, so I will be more careful in handling this issue.

However, I think this bug should be fixed.
- `LIMIT` can be used in MySQL, SQLite3, PostgreSQL, and they return 0 rows when we specify `LIMIT 0`.
- `limit()` is to limit the result rows. So when we specify it, the result should be limited, not be all rows.

File: app/Config/Feature.php [hunk 1]
```diff
@@ -18,4 +18,12 @@ class Feature extends BaseConfig
...
      */
     public bool $oldFilterOrder = false;
+
+    /**
+     * Keep the behavior of `limit(0)` in Query Builder in 4.4 or before.
+     *
+     * If true, `limit(0)` returns all records. (the behavior in 4.4 or before)
+     * If false, `limit(0)` returns no records.
+     */
+    public bool $limitZeroAsAll = false;
```
Comment (michalsn) [inline app/Config/Feature.php:28]:
```suggestion
    public bool $limitZeroAsAll = true;
```
By default, we should keep the current behavior. It can be changed in v5.

File: app/Config/Feature.php [hunk 2]
```diff
@@ -18,4 +18,12 @@ class Feature extends BaseConfig
      * Use filter execution order in 4.4 or before.
      */
     public bool $oldFilterOrder = false;
+
+    /**
+     * Keep the behavior of `limit(0)` in Query Builder in 4.4 or before.
+     *
+     * If true, `limit(0)` returns all records. (the behavior in 4.4 or before)
+     * If false, `limit(0)` returns no records.
+     */
```
Comment (michalsn) [inline app/Config/Feature.php:27]: I would mention CI3 compatibility.

Comment (kenjis) [reply app/Config/Feature.php]: Added.

**Comment by kenjis** [comment]
Added docs.

**Review by michalsn — APPROVED** [review]

**Comment by kenjis** [comment]
@codeigniter4/database-team Review, please.

File: system/BaseModel.php [hunk 3]
```diff
@@ -382,7 +383,7 @@ abstract protected function doFindColumn(string $columnName);
      *
      * @return array
      */
-    abstract protected function doFindAll(int $limit = 0, int $offset = 0);
+    abstract protected function doFindAll(?int $limit = null, int $offset = 0);
```
Comment (samsonasik) [inline system/BaseModel.php:386]: nullable flag seems not needed, just default null should be ok, see https://3v4l.org/4NMIj that also make suggest to apply null only when they know what they are doing

Comment (kenjis) [reply system/BaseModel.php:386]: The rule https://cs.symfony.com/doc/rules/function_notation/nullable_type_declaration_for_default_null_value.html adds `?`.

Comment (samsonasik) [reply system/BaseModel.php:386]: Ok 👍

**Comment by michalsn** [comment]
Just started wondering... will this change have any effect on pagination?

**Comment by kenjis** [comment]
I want to fix this behavior because I don't think it is a good idea to have QueryBuilder behave so differently from the behavior of the original SQL. `LIMIT 0` returning zero rows has been the case for a long time.

**Comment by michalsn** [comment]
I agree with your reasons.

Well, the Pager class has tests and since they pass, I should not worry.

**Comment by kenjis** [comment]
> will this change have any effect on pagination?

`Pager` has nothing to do with Query Builder.

The `$perPage` is more than zero in normal use cases.
https://github.com/codeigniter4/CodeIgniter4/blob/6c487a1c03a81cd279012bed8be12b6730489d3c/system/BaseModel.php#L1212

**Comment by kenjis** [comment]
There were other `$limit` parameters. https://github.com/codeigniter4/CodeIgniter4/pull/8280/commits/20ea3930862e7ef09fe12fab09c1d07a456a0e40

**Comment by michalsn** [comment]
Do we reach a consensus here? The feature flag will be removed in v5, so this is a transitional solution.

**Comment by kenjis** [comment]
It is true that the code is more complicated with the addition of feature flag. 
However, there are only if statements regarding the feature flag,
and when they are removed, they are just removed.
We can easily search where the if statements are with the flag.

I do not see these as major maintenance obstacles.
In addition, there are few use cases where 0 is specified for limit.

**Review by lonnieezell — APPROVED** [review]
