### PR TITLE
fix: change assertion on CLITest::testWaitZero

### LINKED ISSUE #7536: CLITest::testWaitZero failed
```
There was 1 failure:

1) CodeIgniter\CLI\CLITest::testWaitZero
Failed asserting that 1 is identical to 0.

/home/runner/work/CodeIgniter4/CodeIgniter4/tests/system/CLI/CLITest.php:76
```
https://github.com/codeigniter4/CodeIgniter4/actions/runs/5161186392/jobs/9297977046?pr=7535

### PR DESCRIPTION
**Pull request by paulbalandan**
**Description**
Fixes #7536 

`time()` is volatile. It may be called on the edges causing difference to be at least 1.

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPDoc blocks, only if necessary or adds value
- [x] Unit testing, with >80% coverage
- [ ] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

File: tests/system/CLI/CLITest.php [hunk 1]
```diff
@@ -73,7 +73,7 @@ public function testWaitZero()
         $time = time();
         CLI::wait(0);
 
-        $this->assertSame(0, time() - $time);
+        $this->assertCloseEnough(0, time() - $time);
```
Comment (kenjis) [inline tests/system/CLI/CLITest.php:76]: > Failed asserting that 1 is identical to 0.

`time()` returns an interger number.
Does `assertCloseEnough()` help it?

Comment (paulbalandan) [reply tests/system/CLI/CLITest.php:76]: What I mean to say is if `time()` is called near the turn of the second, say 1.98 seconds (this will return the whole seconds, e.g. `1687499559`). Then we call `time()` again after executing `CLI::wait(0)` which for example took 5ms, (so `time()` will give something like `1687499560`). So the difference is 1 second. `$this->assertCloseEnough` is just a modified way of asking if the value is less than or equal the tolerance, which in the case of the method, is equal to 1.

Comment (kenjis) [reply tests/system/CLI/CLITest.php:76]: Okay, `$tolerance = 1`, which means one second in this case.
https://github.com/codeigniter4/CodeIgniter4/blob/ded8d382a054b5e543e3da63e125aa7bb080519d/system/Test/CIUnitTestCase.php#L445

**Review by kenjis — APPROVED** [review]
