### PR TITLE
fix: duplicate Cache-Control header with Session

### LINKED ISSUE #7266: Bug: Duplicate Response Headers
### PHP Version

8.0

### CodeIgniter4 Version

4.3

### CodeIgniter4 Installation Method

Composer (as dependency to an existing project)

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

apache

### Database

_No response_

### What happened?

Cache-Control and Pragma headers are included twice

### Steps to Reproduce

Make a standard controller and return a string. Check the response headers.

### Expected Output

Expected to only list each header once.

This is what I get though:

```
Cache-Control: no-store, no-cache, must-revalidate, no-store, max-age=0, no-cache
Cache-Control: private, no-cache, no-store, proxy-revalidate, no-transform
Connection: Keep-Alive
Content-Encoding: gzip
Content-Length: 5969
Content-Type: text/html; charset=UTF-8
Date: Thu, 16 Feb 2023 18:37:48 GMT
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Keep-Alive: timeout=5, max=100
Pragma: no-cache
Pragma: no-cache
Server: Apache/2.4.18 (Ubuntu)
Set-Cookie: ......
Vary: Accept-Encoding
```

Perhaps it is ok to have duplicates in some circumstances. https://stackoverflow.com/questions/4371328/are-duplicate-http-response-headers-acceptable

I wouldn't think this would be ok:

```
Pragma: no-cache
Pragma: no-cache
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by kenjis**
**Description**
Fixes #7266

- remove the default CI4 `Cache-Control` header before the Session starts.

Before:
```
HTTP/1.1 200 OK
Host: localhost:8080
Date: Sat, 02 Mar 2024 12:54:18 GMT
Connection: close
X-Powered-By: PHP/7.4.33
Expires: Thu, 19 Nov 1981 08:52:00 GMT             // PHP Session
Cache-Control: no-store, no-cache, must-revalidate // PHP Session
Pragma: no-cache                                   // PHP Session
Cache-Control: no-store, max-age=0, no-cache       // CI4
Content-Type: text/html; charset=UTF-8
```

After:
```
HTTP/1.1 200 OK
Host: localhost:8080
Date: Sat, 02 Mar 2024 12:56:08 GMT
Connection: close
X-Powered-By: PHP/7.4.33
Expires: Thu, 19 Nov 1981 08:52:00 GMT
Cache-Control: no-store, no-cache, must-revalidate
Pragma: no-cache
Content-Type: text/html; charset=UTF-8
```

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Review by Gedoxa — APPROVED** [review]

**Review by samsonasik — APPROVED** [review]

File: system/Config/Services.php [hunk 1]
```diff
@@ -690,6 +690,12 @@ public static function session(?SessionConfig $config = null, bool $getShared =
         $session->setLogger($logger);
 
         if (session_status() === PHP_SESSION_NONE) {
+            // PHP Session emits the headers according to `session.cache_limiter`.
+            // See https://www.php.net/manual/en/function.session-cache-limiter.php.
+            // The headers are not managed by the CI's Response class.
+            // So removes the CI's default Cache-Control header.
```
Comment (paulbalandan) [inline system/Config/Services.php:696]:
```suggestion
            // PHP Session emits the headers according to `session.cache_limiter`.
            // See https://www.php.net/manual/en/function.session-cache-limiter.php.
            // The headers are not managed by CI's Response class.
            // So, we remove the CI's default Cache-Control header.
```

**Comment by bgeneto** [comment]
@kenjis Excuse my ignorance, but wouldn't it be better not to create this 'Cache-Control' header in the first place instead of creating it and removing it afterwards and thus adding a (maybe) unnecessary overhead to the framework? The ResponseTrait has
```php
        $this->removeHeader('Cache-Control');
        $this->setHeader('Cache-Control', ['no-store', 'max-age=0', 'no-cache']);
```
It seems to me that the first line does not remove anything and the second line is adding the headers we want to remove while using sessions... What do you think?

**Comment by kenjis** [comment]
I don't know why, but the behavior is intentional. It is not a bug.

> By default, all response objects sent through CodeIgniter have HTTP caching turned off. The options and exact circumstances are too varied for us to be able to create a good default other than turning it off. 
https://codeigniter4.github.io/CodeIgniter4/outgoing/response.html#http-caching

So we cannot change it as a bug fix.

Do you propose to remove the default cache control header?
If so, it is a breaking change and not allowed in `develop` branch.

https://github.com/codeigniter4/CodeIgniter4/blob/a99787c5beeb6c77db4e78cbd4aaa8e69d7e2dee/system/HTTP/ResponseTrait.php#L344-L350

> It seems to me that the first line does not remove anything and the second line is adding the headers we want to remove while using sessions... 

It is the code in the public  `noCache()` method. Devs can call it from somewhere.
So we cannot remove the first line. Because the cache control header may be set already.

> What do you think?

I think it is better to remove the default cache control header. That is, to remove these lines:
https://github.com/codeigniter4/CodeIgniter4/blob/a99787c5beeb6c77db4e78cbd4aaa8e69d7e2dee/system/HTTP/Response.php#L152-L154
Because I think it is better that devs have full control to cache control header, and it is simpler.
But it is a breaking change, so we need more consideration, and need to do it in `4.5` branch, if we do it.

**Comment by vikaskhunteta** [comment]
@kenjis  The issue here is marked as fixed but I am still getting duplicate header when the session enabled globally and I have been trying to cache response of an API request, if I call this function `session_cache_limiter('');` before the session start into `initController` inside `BaseController` then I am getting same error like this user comment

[https://github.com/codeigniter4/CodeIgniter4/issues/7266#issuecomment-1971665482](https://github.com/codeigniter4/CodeIgniter4/issues/7266#issuecomment-1971665482)

image

Should I extend different controller for the API requests which doesn't start the session? What should be the HTTP response code if the request cached? I believe it should be `304 Not Modified` but when I stopped session globally and cached the request I am always getting `200 OK` response.

Framework version - 4.5.3
PHP Version - 8.2.12
OS - Windows 11 Home

**Comment by kenjis** [comment]
@vikaskhunteta What do you mean by "when the session enabled globally"?

Read the code: https://github.com/codeigniter4/CodeIgniter4/pull/8601/files
That's what this PR does.

**Comment by kenjis** [comment]
If you use Shield, Shield may enable Session before your controller.
Check where the Session is initialized, and configure before it.

**Comment by vikaskhunteta** [comment]
@kenjis But there should be no session enable before the login, btw where should I look this? Is there any impact on the headers due to site environment?

**Comment by kenjis** [comment]
We use GitHub issues to track BUGS and to track approved DEVELOPMENT work packages. We use our [forum](http://forum.codeigniter.com/) to provide SUPPORT and to discuss FEATURE REQUESTS.
