### PR TITLE
Fix HealthTest::testBaseUrlHasBeenSet()

### LINKED ISSUE #3977: Bug: appstarter HealthTest::testBaseUrlHasBeenSet fails
**Describe the bug**
HealthTest::testBaseUrlHasBeenSet fails.

**CodeIgniter 4 version**
4.0.4

**Affected module(s)**
tests

**Expected behavior, and steps to reproduce if appropriate**
~~All tests should pass.~~
HealthTest is supposed to check for various "common mistakes" in a user's app, including if App::$baseURL is set.
So fails only when a user does not set baseURL.

```
$ composer create-project codeigniter4/appstarter ci4
$ cd ci4/
$ composer test
...
There was 1 failure:

1) HealthTest::testBaseUrlHasBeenSet
Failed asserting that false is true.

/Users/kenji/tmp/ci4/tests/unit/HealthTest.php:31

FAILURES!
Tests: 5, Assertions: 6, Failures: 1.
Script phpunit handling the test event returned with error code 1
```

**Context**
 - OS: [macOS 10.15.7]
 - Web server [n/a]
 - PHP version [7.4.13]

### PR DESCRIPTION
**Pull request by kenjis**
**Description**
Fixes #3977

Tests about `baseURL`:
- `baseURL` is a valid URL
- Set it in `.env` or `app/Config/App.php`

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPdocs
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Comment by kenjis** [comment]
```sh-session
$ composer create-project codeigniter4/appstarter ci4
$ cd ci4/
$ vendor/bin/phpunit --no-coverage
PHPUnit 9.5.2 by Sebastian Bergmann and contributors.

....F                                                               5 / 5 (100%)

Time: 00:00.085, Memory: 12.00 MB

There was 1 failure:

1) HealthTest::testBaseUrlHasBeenSet
baseURL in app/Config/App.php is not set
Failed asserting that false is true.

/Users/kenji/tmp/ci4/tests/unit/HealthTest.php:38

FAILURES!
Tests: 5, Assertions: 7, Failures: 1.
```

**Comment by kenjis** [comment]
```diff
--- a/app/Config/App.php
+++ b/app/Config/App.php
@@ -23,7 +23,7 @@ class App extends BaseConfig
     *
     * @var string
     */
-   public $baseURL = 'http://localhost:8080/';
+   public $baseURL = 'http://abc.example.com/';
 
    /**
     * --------------------------------------------------------------------------

```

```sh-session
$ vendor/bin/phpunit --no-coverage
PHPUnit 9.5.2 by Sebastian Bergmann and contributors.

.....                                                               5 / 5 (100%)

Time: 00:00.080, Memory: 12.00 MB

OK (5 tests, 8 assertions)
```

**Comment by kenjis** [comment]
```sh-session
$ git reset --hard HEAD
$ cp env .env
$ vi .env
```

```diff
--- env	2021-02-01 11:56:38.000000000 +0900
+++ .env	2021-02-07 11:09:59.000000000 +0900
@@ -20,7 +20,7 @@
 # APP
 #--------------------------------------------------------------------
 
-# app.baseURL = ''
+app.baseURL = http://xyz.example.com/
 # app.forceGlobalSecureRequests = false
 
 # app.sessionDriver = 'CodeIgniter\Session\Handlers\FileHandler'
```

```sh-session
$ vendor/bin/phpunit --no-coverage
PHPUnit 9.5.2 by Sebastian Bergmann and contributors.

.....                                                               5 / 5 (100%)

Time: 00:00.078, Memory: 12.00 MB

OK (5 tests, 8 assertions)
```

**Comment by kenjis** [comment]
I think this is probably OK. But a bit complicated...

**Comment by MGatner** [comment]
Per the issue conversation this should be updated only to fix the regex. But please make sure the regex allows single quotes still, the version in this PR does not.

**Comment by kenjis** [comment]
URL with single quotes passes the test. `'` is included in `.`.

```diff
--- env	2021-02-01 11:56:38.000000000 +0900
+++ .env	2021-02-10 10:57:00.000000000 +0900
@@ -20,7 +20,7 @@
 # APP
 #--------------------------------------------------------------------
 
-# app.baseURL = ''
+app.baseURL = 'http://localhost:8080/'
 # app.forceGlobalSecureRequests = false
 
 # app.sessionDriver = 'CodeIgniter\Session\Handlers\FileHandler'
```

```sh-session
$ vendor/bin/phpunit --no-coverage
PHPUnit 9.5.2 by Sebastian Bergmann and contributors.

.....                                                               5 / 5 (100%)

Time: 00:00.075, Memory: 12.00 MB

OK (5 tests, 8 assertions)
```

**Comment by paulbalandan** [comment]
why are we disallowing `localhost:8080` for the baseURL?

**Comment by kenjis** [comment]
The user guide says:
> Open the app/Config/App.php file with a text editor and set your base URL. If you need more flexibility, the baseURL may be set within the .env file as app.baseURL=”http://example.com/”. (Always use a trailing slash on your base URL!)
https://codeigniter4.github.io/CodeIgniter4/installation/running.html#initial-configuration-set-up

So I think users are supposed to set their base URL, and `localhost:8080` is the default, they did not set it.

**Comment by MGatner** [comment]
Localhost is fine for a base URL! See my comment above, but the issue is when a user has explicitly created a scenario where the base URL is blank - out of the box it should work fine.

**Comment by MGatner** [comment]
I think the regex currently fails to catch `app.baseUrl = ''` which should fail.

**Comment by kenjis** [comment]
How about this? I've cleaned up.

I removed disallowing `localhost:8080`, and changed the validation to use Validator.

`app.baseURL = ''` is not a valid URL, so it fails.

File: admin/starter/tests/unit/HealthTest.php [hunk 1]
```diff
@@ -16,18 +18,35 @@ public function testIsDefinedAppPath()
...
+			$config = new Config\App();
+			$this->assertTrue(
+				$validation->check($config->baseURL, 'valid_url'),
+				'baseURL "' . $config->baseURL . '" in .env is not valid URL'
+			);
 		}
 
-		// Then check the actual config file
+		// Get the baseURL in app/Config/App.php
+		// Don't forget phpunit.xml.dist sets app.baseURL
```
Comment (paulbalandan) [inline admin/starter/tests/unit/HealthTest.php:43]: I think this is not needed. As `ConfigReader` does not call `Config\App`'s constructor, its properties would not be populated by environment values but only by the hardcoded values.

Comment (kenjis) [reply admin/starter/tests/unit/HealthTest.php]: @paulbalandan I fixed the comment. My intention is why we need to use ConfigReader.
I forgot about phpunit.xml.dist at the first time.

**Review by paulbalandan — APPROVED** [review]

**Comment by bereldhuin** [comment]
I noticed another problem with the regexp (using CI 4.1.1) : VisualStudio code tends to remove spaces in .env files.

So my baseUrl looks like this : 
`app.baseURL='http://192.168.1.11:81/'`
Instead of
`app.baseURL = 'http://192.168.1.11:81/'`

Which makes the phpunit fail on testBaseUrlHasBeenSet
