### PR TITLE
fix: correct path parsing in `SiteURIFactory::parseRequestURI()`

### LINKED ISSUE #9602: Bug: codeigniter in a subdirectory + indexPage results in 404
### PHP Version

8.3

### CodeIgniter4 Version

4.6.1

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

apache

### Database

_No response_

### What happened?

I have a codeigniter 4 app that has to live in a shared hosting enviroment and has to be in a subdirectory.
The app has been developed with legacy autorouting enabled.
The app has indexPage as `index.php`

All the autorouting routes end up throwing a 404 with the "index.php is not a valid controller name" statement.

### Steps to Reproduce

1. get an apache webserver
2. set `indexPage ` as `index.php` in your app/Config/App.php
3. install codeigniter in a subdirectory:
```
/var/www/html/code-igniger-app
/var/www/html/other-apps-here
```
this way you'll access the app from http://localhost:8080/code-igniger-app/index.php
4. enable legacy autorouting and create a controller

### Expected Output

It should not be throwing a 404

### Anything else?

To fix it i added the following code to the very beginning of the index.php
```php
$_SERVER["SCRIPT_NAME"] = str_replace("/public","",$_SERVER["SCRIPT_NAME"]);
```
The SCRIPT_NAME would have been: `/code-igniger-app/public/index.php` this way it becomes `/code-igniger-app/index.php`.
This way when `CodeIgniter\HTTP\SiteURIFactory` uses the `parseRequestURI` method to remove the `SCRIPT_NAME` form the uri and then return the `$path` it is able to return it correctly.

### PR DESCRIPTION
**Pull request by michalsn**
**Description**
This PR fixes a bug where route path detection was failing when serving the app from a subfolder using Apache `mod_rewrite` (to "hide" `public` directory) while preserving `index.php` in URL.

 So something like: `https://localhost/ci/index.php/controller/method` - when our real directory structure was like: `ci/public/index.php`.  This caused the route path to return: `index.php/controller/method` instead of `controller/method`.
 
 Closes #9607
Fixes #9602 
 

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPDoc blocks, only if necessary or adds value
- [x] Unit testing, with >80% coverage
- [ ] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

File: system/HTTP/SiteURIFactory.php [hunk 1]
```diff
@@ -146,6 +146,15 @@ private function parseRequestURI(): string
             $path = implode('/', $keep);
         }
 
+        // Cleanup: if indexPage is still visible in the path, remove it
+        if ($this->appConfig->indexPage !== '' && str_starts_with($path, $this->appConfig->indexPage)) {
+            $remainingPath = substr($path, strlen($this->appConfig->indexPage));
```
Comment (neznaika0) [inline system/HTTP/SiteURIFactory.php:151]: Is it better to use `mb_*` functions? Sometimes the project folder may be in Cyrillic: **/var/www/проект/тест1/public/index.php**

Comment (neznaika0) [reply system/HTTP/SiteURIFactory.php:151]: You can add a test for this

Comment (michalsn) [reply system/HTTP/SiteURIFactory.php:151]: There's no need to use multibyte functions here.

That said, this particular scenario can cause issues, since `REQUEST_URI` contains the raw (percent-encoded) HTTP path, while `SCRIPT_NAME` is already decoded.

In any case, this isn't directly related to the issue we're currently fixing. I'm also not sure we should address it, as using multibyte characters in folder names (while technically possible) is generally discouraged in this context. In any case, the developer can always choose to use ASCII-safe folder names.

Comment (michalsn) [reply system/HTTP/SiteURIFactory.php:151]: This problem is now handled in a separate PR: #9615

**Comment by michalsn** [comment]
Thank you @paulbalandan
