### PR TITLE
Parser: Escape hashes in main pattern

### LINKED ISSUE #3824: Bug: Parser preg_replace_callback exception if template has #
**Describe the bug**
If the template has for example:
```html
<p style="color:#999999">{test}</p>
``` 
the parser will trow the exception **preg_replace_callback(): Unknown modifier '9'**
*Notice the 9 modifier comes from the first char after #* 
This only happens if you use **setData**, if not the error does not happen.
 
**CodeIgniter 4 version**
4.0.4 (live)

**Affected module(s)**
Parser

**Expected behavior, and steps to reproduce if appropriate**
- No error:
```php
$parser = \Config\Services::parser();
$template = '<p style="color:red; background-color:#993399;">Price $: 12.50</p>';
echo $parser->renderString($template);
```

- Error
```php
$parser = \Config\Services::parser();
$data   = [
	'books' => [
		['price' => '12.50'],
	],
];
$template = '{books}<p style="color:red; background-color:#993399;">Price $: {price}</p>{/books}';
$parser->setData($data);
echo $parser->renderString($template);
```

**Context**
 - OS: Ubuntu: 18.04.5 LTS
 - Web server: Apache/2.4.29
 - PHP version: PHP 7.4.10

### PR DESCRIPTION
**Pull request by paulbalandan**
**Description**
Fixes #3824 and alternative to #3846 

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPdocs
- [x] Unit testing, with >80% coverage
- [ ] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

File: system/View/Parser.php [hunk 1]
```diff
@@ -572,12 +569,18 @@ public function setDelimiters($leftDelimiter = '{', $rightDelimiter = '}'): Rend
 	 */
 	protected function replaceSingle($pattern, $content, $template, bool $escape = false): string
 	{
-		// Any dollar signs in the pattern will be mis-interpreted, so slash them
+		// Any dollar signs in the pattern will be misinterpreted, so slash them
 		$pattern = addcslashes($pattern, '$');
 
+		// Flesh out the main pattern from the delimiters and escape the hash
+		if (preg_match('/^(#)(.*)(#(m?s)?)$/', $pattern, $parts))
```
Comment (samsonasik) [inline system/View/Parser.php:576]: I think it need note with `@see https://regex101.com/path` to show the regex demo, eg: 

```php
// @see https://regex101.com/r/gV1eVk/1
```

so in the future, when there is a bug fix on regex, it will be easier to check/update.

**Review by samsonasik — APPROVED** [review]
