### PR TITLE
Fix validation for multi select

### LINKED ISSUE #2757: Bug: Multiple select validation problem
Hello,
I try to validate a form with a multiple select that was working in CI3

In my view:
```html
<select name="id_user[]"  multiple="">
<option value="1">user1</option>
<option value="2">user2</option>
<option value="3">user3</option>
</select>
```

In my controller :
```php
echo '<pre>' , var_dump($_POST) , '</pre>';
```
print
```
array(2) {
["id_user"]=>
array(2) {
[0]=> string(1) "1"
[1]=> string(1) "2"
}
["find"]=> string(10) "find"
 }
```
AND 

```php
$this->validation->setRules([
    'id_user[]'=>'numeric',
]);
$this->validation->withRequest($this->request)->run();
echo '<pre>' , var_dump($this->validation->getErrors()) , '</pre>';
```
print
```
array(1) {
  ["id_user[]"]=>  string(46) "The id_user[] field must contain only numbers."
}
```
it looks like CodeIgniter\Validation\run() is looking for "id_user[]" in the $_POST wich doesn't exist, instead of "id_user". And if I change the rule to 'id_user'=>'numeric', it does't care about the multiple value ...
is it a bug or do I have to change something in my code ?

**Context**
- CodeIgniter 4.02
 - Windows 10
 - PHP version 7.3.15

### PR DESCRIPTION
**Pull request by musmanikram**
Fix #2757 

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPdocs
- [x] Unit testing, with >80% coverage
- [ ] User guide updated
- [ ] Conforms to style guide

### CODE REVIEW

**Comment by lonnieezell** [comment]
Seems ok to me. Merging.

File: tests/system/Validation/ValidationTest.php [hunk 1]
```diff
@@ -665,24 +665,25 @@ public function testRulesForArrayField($body, $rules, $results)
...
 					'foo.0' => 'required|alpha|max_length[2]',
 					'foo.1' => 'required|alpha|max_length[2]',
-					'foo.2' => 'required|alpha|max_length[2]'
+					'foo.2' => 'required|alpha|max_length[2]',
 				],
-				'results' => []
+				'results' => [],
 			],
-			'first_field_will_return_required_error' => [
+			/*'first_field_will_return_required_error' => [
```
Comment (samsonasik) [inline tests/system/Validation/ValidationTest.php]: just wondering, why this data provider commented ?

Comment (musmanikram) [reply tests/system/Validation/ValidationTest.php]: :man_facepalming: :man_facepalming: :man_facepalming: My bad. Will create another PR.

Thank you for pointing this out
