### PR TITLE
fix: exceptionHandler may return invalid HTTP status code

### LINKED ISSUE #6227: Bug: Fatal error:  Uncaught CodeIgniter\HTTP\Exceptions\HTTPException: Unknown HTTP status code provided with no message: 167
### PHP Version

8.1

### CodeIgniter4 Version

4

### CodeIgniter4 Installation Method

Manual (zip or tar.gz)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### Database

_No response_

### What happened?

ehm id write an api and this comes:
```
<b>Fatal error</b>:  Uncaught CodeIgniter\HTTP\Exceptions\HTTPException: Unknown HTTP status code provided with no message: 167 in /var/www/vhosts/blackserv.de/api.blackserv.de/system/HTTP/ResponseTrait.php: 158
Stack trace:
#0 /var/www/vhosts/blackserv.de/api.blackserv.de/system/HTTP/ResponseTrait.php(158): CodeIgniter\HTTP\Exceptions\HTTPException: :forUnkownStatusCode()
#1 /var/www/vhosts/blackserv.de/api.blackserv.de/system/Debug/Exceptions.php(114): CodeIgniter\HTTP\Response-&gt;setStatusCode()
#2 [internal function]: CodeIgniter\Debug\Exceptions-&gt;exceptionHandler()
#3 {main}
thrown in <b>/var/www/vhosts/blackserv.de/api.blackserv.de/system/HTTP/ResponseTrait.php</b> on line <b>158</b><br/>
{
    "title": "ErrorException",
    "type": "ErrorException",
    "code": 500,
    "message": "Uncaught CodeIgniter\\HTTP\\Exceptions\\HTTPException: Unknown HTTP status code provided with no message: 167 in /var/www/vhosts/blackserv.de/api.blackserv.de/system/HTTP/ResponseTrait.php:158\nStack trace:\n#0 /var/www/vhosts/blackserv.de/api.blackserv.de/system/HTTP/ResponseTrait.php(158): CodeIgniter\\HTTP\\Exceptions\\HTTPException::forUnkownStatusCode()\n#1 /var/www/vhosts/blackserv.de/api.blackserv.de/system/Debug/Exceptions.php(114): CodeIgniter\\HTTP\\Response->setStatusCode()\n#2 [internal function]: CodeIgniter\\Debug\\Exceptions->exceptionHandler()\n#3 {main}\n  thrown",
    "file": "/var/www/vhosts/blackserv.de/api.blackserv.de/system/HTTP/ResponseTrait.php",
    "line": 158,
    "trace": [
        {
            "function": "shutdownHandler",
            "class": "CodeIgniter\\Debug\\Exceptions",
            "type": "->"
        }
    ]
}
```

### Steps to Reproduce

```php
<?php
namespace App\Controllers;
use CodeIgniter\API\ResponseTrait;
use CodeIgniter\Controller;
use App\Libraries\AuthSystem;

class Authentication extends BaseController
{
    use ResponseTrait;

    public function index()
    {
        $data = ['options' => ['1' => '/authentication/login', '2' => '/authentication/register'], 'server' => getEnv("ServerID") , ];
        return $this->respond($data);
    }

    public function login()
    {
        $auth = new AuthSystem();
        if (isset($_POST['username']) || isset($_POST['email']) && isset($_POST['password']))
        {
            if (isset($_POST['username']))
            {
                $login = $auth->login($_POST['username'], $_POST['password']);
                $userdat = $auth->find($_POST['username']);
            }
            if (isset($_POST['email']))
            {
                $login = $auth->login($_POST['email'], $_POST['password']);
                $userdat = $auth->find($_POST['email']);
            }
            if ($login == "success")
            {	
				
                $sessiontoken = $auth->regentoken($userdat->id, $this->request->getUserAgent(), $this->request->getIPAddress());

                $data = ['state' => 'succes', 'session' => $sessiontoken, 'server' => getEnv("ServerID") , ];
                return $this->respond($data);

            }
            else
            {
                $data = ['state' => 'error', 'message' => $login, 'server' => getEnv("ServerID") , ];
				return $this->respond($data);
            }

        }
        else
        {
            $data = ['state' => 'error', 'message' => 'not all parameters given', 'server' => getEnv("ServerID") , ];
            return $this->respond($data);
        }
		return $this->respond($data);
    }

}
```

### Expected Output

nothing

### Anything else?

PLEASE HELP

### PR DESCRIPTION
**Pull request by kenjis**
**Description**
The current implementation has undocumented behavior that use **Exception code** as **HTTP status code**,
and determine **Exit code** from Exception code.
But Exception code has nothing to do with HTTP status code or Exit code.

This PR introduces interfaces that explicitly show the Exception code is  HTTP status code or Exit code

- add `HTTPExceptionInterface` and `HasExitCodeInterface`
- fix `Exceptions::determineCodes()`

**Breaking Changes:**
- If you expect Exception code as HTTP status code, the HTTP status code will be changed.
In that case, you need to implements `HTTPExceptionInterface` in the Exception.
- If you expect Exit code based on Exception code, the Exit code will be changed.
In that case, you need to implements `HasExitCodeInterface` in the Exception.

Related: #6286

**Checklist:**
- [x] Securely signed commits
- [x] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [x] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Comment by iRedds** [comment]
I have doubts about the implementation.
If it's an HTTP exception, then the code should be >= 400 and < 500. 
In all other cases, the code should be 500.

Something like this
```php
$statusCode = 500;
$exitStatus = EXIT_ERROR;

if (
    $exception instanceof HttpException
    && $exception->getCode() >= 400
    && $exception->getCode() < 500
) {
    $statusCode = $exception->getCode();    
}

There is no point in additional interfaces.
And to be honest, it's a little strange for me that HTTP exceptions are handled through Debug.
```

**Comment by kenjis** [comment]
> it's a little strange for me that HTTP exceptions are handled through Debug.

Yes. This is global exception handler, so it should return 500 Response for all cases.
HTTP exceptions should be handled before here.

**Comment by MGatner** [comment]
Just a note that HTTP exceptions actually include 300s as well via `RedirectException`.

**Comment by kenjis** [comment]
There is `HTTPException`, but it has nothing to do with HTTP response code.
https://github.com/codeigniter4/CodeIgniter4/blob/bc688d9b99868075c2d98f701c154f5add038346/system/HTTP/Exceptions/HTTPException.php#L19

**Comment by kenjis** [comment]
`RedirectException` is caught in `CodeIgniter::run()`:
https://github.com/codeigniter4/CodeIgniter4/blob/bc688d9b99868075c2d98f701c154f5add038346/system/CodeIgniter.php#L350-L359

**Comment by kenjis** [comment]
I think this PR is ready for reviews.
I think this is the best we can do at the moment.

**Comment by MGatner** [comment]
> `RedirectException` is caught in `CodeIgniter::run()`

Why not make `RedirectException` and `PageNotFoundException` extend `HTTPException` and then catch all `HTTPException` in `run()` and handle them there? These two are currently special cases but I could see a developer wanting to force any HTTP code response at any point via an exception.

**Comment by MGatner** [comment]
Actually I just read this:

> The exception code has nothing to do with HTTP status code.
> So it is impossible to determine HTTP status code from exception code.

So maybe the exception type is what defines these two special cases and we don't want more robust handling.

**Comment by kenjis** [comment]
> Why not make RedirectException and PageNotFoundException extend HTTPException and then catch all HTTPException in run() and handle them there?

404 is handled in the exceptionHandler() now.
If we catch all HTTPException in run(), we need to change the current code more.

**Comment by kenjis** [comment]
I've changed my mind.
This PR changes too much. If we add interfaces or change the parent class, it should go `4.3`.

I sent another PR #6228 with minimum changes for the bug fix.

**Comment by paulbalandan** [comment]
With the merge of #6254 , is this still needed?

**Comment by kenjis** [comment]
Yes, #6254 is a workaround.

I think the current behavior is broken. Because Exception code has nothing to do with HTTP status code/Exit code.
If the Exception code means HTTP status code/Exit code, devs should make it explicit.

**Comment by kenjis** [comment]
It seems to me that it is impossible to use Exception code to represent Exit code. 
If you have already used an Exception code, you cannot specify an Exit code.

I feel it would be better to have `getExitCode()` in `ExitExceptionInterface`.

**Comment by kenjis** [comment]
I renamed `ExitExceptionInterface` to `hasExitCodeInterface` and added `getExitCode()` method.

File: system/Exceptions/hasExitCodeInterface.php [hunk 1]
```diff
@@ -0,0 +1,23 @@
...
+ * For the full copyright and license information, please view
+ * the LICENSE file that was distributed with this source code.
+ */
+
+namespace CodeIgniter\Exceptions;
+
+/**
+ * Interface for Exceptions that has exception code as exit code.
+ */
+interface hasExitCodeInterface
```
Comment (MGatner) [inline system/Exceptions/hasExitCodeInterface.php:17]: Doesn't this need to be capitalized?

Comment (kenjis) [reply system/Exceptions/hasExitCodeInterface.php:17]: You are correct!

Comment (kenjis) [reply system/Exceptions/hasExitCodeInterface.php]: Fixed.

**Review by MGatner — APPROVED** [review]
Good by me!

**Comment by kenjis** [comment]
Added the docs.

File: user_guide_src/source/changelogs/v4.3.0.rst [hunk 2]
```diff
@@ -23,6 +23,20 @@ Exceptions when Database Errors Occur
 - The exceptions thrown by the database connection classes have been changed to ``CodeIgniter\Database\Exceptions\DatabaseException``. Previously, different database drivers threw different exception classes, but these have been unified into ``DatabaseException``.
 - The exceptions thrown by the ``execute()`` method of Prepared Queries have been changed to ``DatabaseException``. Previously, different database drivers might throw different exception classes or did not throw exceptions, but these have been unified into ``DatabaseException``.
 
+HTTP Status Code and Exit Code when Exception Occurs
+----------------------------------------------------
+
+Previously, the CodeIgniter's Exception Handler used the *Exception code* as *HTTP status code* in some cases, and set calculated *Exit code* based on the Exception code. However there is essentially nothing to do with Exception code and HTTP Status Code or Exit code.
```
Comment (MGatner) [inline user_guide_src/source/changelogs/v4.3.0.rst:29]:
```suggestion
Previously, CodeIgniter's Exception Handler used the *Exception code* as the *HTTP status code* in some cases, and calculated the *Exit code* based on the Exception code. However there should be no logical connection with Exception code and HTTP Status Code or Exit code.
```

File: user_guide_src/source/changelogs/v4.3.0.rst [hunk 3]
```diff
@@ -23,6 +23,20 @@ Exceptions when Database Errors Occur
...
+
+- Now the Exception Handler sets HTTP status code to ``500`` and set Exit code to the constant ``EXIT_ERROR`` (= ``1``) by default.
+- You can change HTTP status code or Exit code to implements ``HTTPExceptionInterface`` or ``HasExitCodeInterface`` in your Exception class. See :ref:`error-specify-http-status-code` and :ref:`error-specify-exit-code`.
```
Comment (MGatner) [inline user_guide_src/source/changelogs/v4.3.0.rst:32]:
```suggestion
- You can change HTTP status code or Exit code to implement ``HTTPExceptionInterface`` or ``HasExitCodeInterface`` in your Exception class. See :ref:`error-specify-http-status-code` and :ref:`error-specify-exit-code`.
```

File: user_guide_src/source/general/errors.rst [hunk 4]
```diff
@@ -113,3 +113,23 @@ forcing a redirect to a specific route or URL:
...
+
+.. _error-specify-http-status-code:
+
+Specify HTTP Status Code in Your Exception
+==========================================
+
+Since v4.3.0, you can specify the HTTP status code for your Exception class to implement
+``HTTPExceptionInterface``.
+
+When an exception implemented ``HTTPExceptionInterface`` is caught by CodeIgniter's exception handler, the Exception code will be the HTTP status code.
```
Comment (MGatner) [inline user_guide_src/source/general/errors.rst:125]:
```suggestion
When an exception implementing ``HTTPExceptionInterface`` is caught by CodeIgniter's exception handler, the Exception code will become the HTTP status code.
```

File: user_guide_src/source/general/errors.rst [hunk 5]
```diff
@@ -113,3 +113,23 @@ forcing a redirect to a specific route or URL:
...
+
+.. _error-specify-exit-code:
+
+Specify Exit Code in Your Exception
+===================================
+
+Since v4.3.0, you can specify the exit code for your Exception class to implement
+``HasExitCodeInterface``.
+
+When an exception implemented ``HasExitCodeInterface`` is caught by CodeIgniter's exception handler, the code returned from the ``getExitCode()`` method will be the exit code.
```
Comment (MGatner) [inline user_guide_src/source/general/errors.rst:135]:
```suggestion
When an exception implementing ``HasExitCodeInterface`` is caught by CodeIgniter's exception handler, the code returned from the ``getExitCode()`` method will become the exit code.
```

File: user_guide_src/source/installation/upgrade_430.rst [hunk 6]
```diff
@@ -44,6 +44,17 @@ Add **types** to the properties in these Config classes. You may need to fix the
 Breaking Changes
 ****************
 
+HTTP Status Code and Exit Code of Uncaught Exceptions
+=====================================================
+
+- If you expect *Exception code* as *HTTP status code*, the HTTP status code will be changed.
+  In that case, you need to implements ``HTTPExceptionInterface`` in the Exception. See :ref:`error-specify-http-status-code`.
```
Comment (MGatner) [inline user_guide_src/source/installation/upgrade_430.rst:51]:
```suggestion
  In that case, you need to implement ``HTTPExceptionInterface`` in the Exception. See :ref:`error-specify-http-status-code`.
```

File: user_guide_src/source/installation/upgrade_430.rst [hunk 7]
```diff
@@ -44,6 +44,17 @@ Add **types** to the properties in these Config classes. You may need to fix the
...
+- If you expect *Exit code* based on *Exception code*, the Exit code will be changed.
+  In that case, you need to implements ``HasExitCodeInterface`` in the Exception. See :ref:`error-specify-exit-code`.
```
Comment (MGatner) [inline user_guide_src/source/installation/upgrade_430.rst:53]:
```suggestion
  In that case, you need to implement ``HasExitCodeInterface`` in the Exception. See :ref:`error-specify-exit-code`.
```

**Review by MGatner — CHANGES_REQUESTED** [review]
Looks good! Some proofing suggestions.

**Review by MGatner — APPROVED** [review]
