### PR TITLE
fix: Toolbar when `maxHistory` is set to `0`

### LINKED ISSUE #9504: Bug:  Toolbar is not working correctly if `$maxHistory = 0`
### PHP Version

8.4

### CodeIgniter4 Version

4.6

### CodeIgniter4 Installation Method

Git

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

cli-server (PHP built-in webserver)

### Database

_No response_

### What happened?

I believe that when disabling the request history `Config\Toolbar::$maxHistory = 0`, there should be no files in **writable/debugbar/***. They are being created now. 

The second point, is that after disabling the **History** tab, JS cannot find this button (tab) and writes an error in the console.

### Steps to Reproduce

Set in .env file:

```env
CI_ENVIRONMENT = development
toolbar.maxHistory = 0
``` 
run server, open homepage. See browser console and files in **writable/debugbar/***.

Image

### Expected Output

Request history files **writable/debugbar/*.json** should not be created. The toolbar should handle missing tabs.

### Anything else?

The point of write history:
https://github.com/codeigniter4/CodeIgniter4/blob/c377646e8cb42d80e59d17b19b4155c476442879/system/Debug/Toolbar.php#L406

Losing the button here:
https://github.com/codeigniter4/CodeIgniter4/blob/c377646e8cb42d80e59d17b19b4155c476442879/system/Debug/Toolbar/Views/toolbar.js#L31

### PR DESCRIPTION
**Pull request by michalsn**
**Description**
This PR fixes issues with the debug bar when `maxHistory` is set to `0`:

- A JavaScript error occurred because the expected button does not exist.
- Debug toolbar history files were not properly cleaned up.

Fixes #9504

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

File: system/Debug/Toolbar/Views/toolbar.js [hunk 1]
```diff
@@ -27,11 +27,13 @@ var ciDebugBar = {
             .getElementById("debug-icon-link")
             .addEventListener("click", ciDebugBar.toggleToolbar, true);
 
-        // Allows to highlight the row of the current history request
-        var btn = this.toolbar.querySelector(
-            'button[data-time="' + localStorage.getItem("debugbar-time") + '"]'
-        );
-        ciDebugBar.addClass(btn.parentNode.parentNode, "current");
+        if (this.toolbar.querySelector(".ci-history-load")) {
```
Comment (neznaika0) [inline system/Debug/Toolbar/Views/toolbar.js:30]: See down, `historyLoad` set. You can use it.

Comment (michalsn) [reply system/Debug/Toolbar/Views/toolbar.js]: Updated. Thank you.

**Review by neznaika0 — COMMENTED** [review]
All good, but HTMX creates an unlimited number of json files until a new HTTP request is executed (example **F5** in browser).

**Comment by michalsn** [comment]
IMO, this is fine as-is. The limit should only apply to "normal" requests (when we actually display the toolbar). Otherwise, we’d introduce a much bigger problem: removing a debug entry from history would be possible even though it’s still visible in the list of available data. Let’s avoid complicating things unnecessarily.

If you're using the codeigniter-htmx library, you should not experience this problem since the debug toolbar is reloaded on every request.

**Review by neznaika0 — APPROVED** [review]

**Review by paulbalandan — APPROVED** [review]

**Comment by michalsn** [comment]
Thank you @paulbalandan and @neznaika0
