### PR TITLE
Fix ResourceController Issue, including Test Unit

### LINKED ISSUE #2617: Bug: ResourceController json response always empty
When creating a ResourceController, [following the documentation](https://codeigniter4.github.io/userguide/incoming/restful.html#resourcecontroller) any json response will be empty. This is because json_encode() can not handle the \CodeIgniter\Entity class automatically.

**Proposed solution**
\CodeIgniter\Entity to implement \JsonSerializable and the method `jsonSerialize()` to return its attributes.

**CodeIgniter 4 version**
4.0.2

**Affected module(s)**
system/Entity.php

**Expected behavior, and steps to reproduce if appropriate**
Following the user guide I would expect to get a json result instead of an empty response.

**Context**
 - macOS
 - php spark serve
 - PHP version 7.2

### PR DESCRIPTION
**Pull request by arif-rh**
This is an alternative way to fix #2617 

I found that variable `$format` should be moved to `ResponseTrait` , so that it can be used inside `format` method.

I have add two unit testing for this change

**Checklist:**
- [x] Securely signed commits
- [x] Component(s) with PHPdocs
- [x] Unit testing, with >80% coverage
- [ ] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Comment by arif-rh** [comment]
Hi @MGatner , I have updated to follow the style guide

**Comment by lonnieezell** [comment]
Unfortunately I don't know exactly what Jim had planned here. Doing it as an after filter definitely makes sense at first glance.

File: system/API/ResponseTrait.php [hunk 1]
```diff
@@ -366,7 +372,15 @@ protected function format($data = null)
 
 		// Determine correct response type through content negotiation
 		$config = new Format();
-		$format = $this->request->negotiate('media', $config->supportedResponseFormats, false);
+
+		if (! in_array($this->format, ['json', 'xml']))
```
Comment (MGatner) [inline system/API/ResponseTrait.php]: Does hard-coding the available formats prevent meaningful extension? I wonder if this should be checking again the application-configured formatters instead (**app/Config/Format.php**) in case a developer has defined their own.

Comment (arif-rh) [reply system/API/ResponseTrait.php]: what I understand from `ResourceController` is this feature can set default format for an API. For example, all API by default using json format, but one API will have xml format, so we can overide this by `setFormat` function.

setFormat

Currently, setFormat only validate two kind of format, either json or xml, that why it need to be re-checked, by hard-coding the available format. 

In case a developer has defined their own format, he can set it up with custom format then system will check again using request negotiate.

@MGatner , tell me if my understanding is wrong.

Comment (MGatner) [reply system/API/ResponseTrait.php]: No, you are very right! I didn’t realize that was hard-codes into `setFormat` as well. Might be worth changing these down the road but we’ll leave that for the next pass at the RESTful, maybe with the After Filter.
