### PR TITLE
test: fix BaseConfigTest

### LINKED ISSUE #8094: Dev: FactoriesTest fails in `develop` after v4.4.2
7cd5c99c84aadce345adc8461830b08451dd3e33

```console
(develop *$=)$ ./phpunit tests/system/Config/
PHPUnit 9.6.13 by Sebastian Bergmann and contributors.

Runtime:       PHP 8.1.24
Configuration: /Users/kenji/work/codeigniter/official/CodeIgniter4/phpunit.xml

.........................................................F....F.FFFFF............................................................ 129 / 140 ( 92%)
...........                                                                                                                       140 / 140 (100%)

Time: 00:06.997, Memory: 22.00 MB

There were 7 failures:

1) CodeIgniter\Config\FactoriesTest::testCreatesByBasename
Failed asserting that null is an instance of class "Tests\Support\Widgets\SomeWidget".

/Users/kenji/work/codeigniter/official/CodeIgniter4/tests/system/Config/FactoriesTest.php:157

2) CodeIgniter\Config\FactoriesTest::testReturnsSharedInstance
Failed asserting that Tests\Support\Widgets\SomeWidget Object &00000000000003d20000000000000000 () is identical to null.

/Users/kenji/work/codeigniter/official/CodeIgniter4/tests/system/Config/FactoriesTest.php:193

3) CodeIgniter\Config\FactoriesTest::testRespectsComponentAlias
Failed asserting that null is an instance of class "Tests\Support\Widgets\SomeWidget".

/Users/kenji/work/codeigniter/official/CodeIgniter4/tests/system/Config/FactoriesTest.php:210

4) CodeIgniter\Config\FactoriesTest::testRespectsPath
Failed asserting that null is an instance of class "Tests\Support\Widgets\SomeWidget".

/Users/kenji/work/codeigniter/official/CodeIgniter4/tests/system/Config/FactoriesTest.php:218

5) CodeIgniter\Config\FactoriesTest::testRespectsInstanceOf
Failed asserting that null is an instance of class "Tests\Support\Widgets\SomeWidget".

/Users/kenji/work/codeigniter/official/CodeIgniter4/tests/system/Config/FactoriesTest.php:226

6) CodeIgniter\Config\FactoriesTest::testSharedRespectsInstanceOf
Failed asserting that null is an instance of class "Tests\Support\Widgets\SomeWidget".

/Users/kenji/work/codeigniter/official/CodeIgniter4/tests/system/Config/FactoriesTest.php:237

7) CodeIgniter\Config\FactoriesTest::testPrioritizesParameterOptions
Failed asserting that null is an instance of class "Tests\Support\Widgets\OtherWidget".

/Users/kenji/work/codeigniter/official/CodeIgniter4/tests/system/Config/FactoriesTest.php:245

FAILURES!
Tests: 140, Assertions: 240, Failures: 7.
```

### PR DESCRIPTION
**Pull request by kenjis**
**Description**
Closes #8094
Follow-up #8036

- add `BaseConfig::reset()` for testing
- reset state after testing

```console
$ ./phpunit tests/system/Config/
PHPUnit 9.6.13 by Sebastian Bergmann and contributors.

Runtime:       PHP 8.1.24
Configuration: /.../CodeIgniter4/phpunit.xml

................................................................................................................................. 129 / 140 ( 92%)
...........                                                                                                                       140 / 140 (100%)

Time: 00:05.899, Memory: 22.00 MB

OK (140 tests, 241 assertions)
```

**Checklist:**
- [x] Securely signed commits
- [] Component(s) with PHPDoc blocks, only if necessary or adds value
- [] Unit testing, with >80% coverage
- [] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

File: tests/system/Config/BaseConfigTest.php [hunk 1]
```diff
@@ -271,18 +271,27 @@ public function testBadRegistrar(): void
...
         $modules->method('shouldDiscover')->with('registrars')->willReturn(false);
-
         RegistrarConfig::setModules($modules);
+
         $config = new RegistrarConfig();
 
         $this->assertSame([], $config::$registrars);
+
+        // Reset Modules Config.
+        RegistrarConfig::setModules(new Modules());
```
Comment (paulbalandan) [inline tests/system/Config/BaseConfigTest.php:289]: this is already done in setUp

Comment (kenjis) [reply tests/system/Config/BaseConfigTest.php:289]: Yes, but if the test method moves to the last, the mock object remains.
Since we are using static properties, we have to reset them again and again.

Comment (paulbalandan) [reply tests/system/Config/BaseConfigTest.php:289]: Then it should be added in tearDown also so if the test fails, resetting will still be done.

Comment (kenjis) [reply tests/system/Config/BaseConfigTest.php]: Added tearDown() and so on.

**Review by paulbalandan — APPROVED** [review]
