### PR TITLE
fix: gather affected rows after query call failed

### LINKED ISSUE #9362: Bug: insertBatch not return false
### PHP Version

8.1

### CodeIgniter4 Version

4.5.1

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### Database

PostgreSQL 15

### What happened?

insertBatch never not return false

### Steps to Reproduce

DataBase 
```sql
CREATE TABLE public.test (
	id serial4 NOT NULL,
	"name" varchar(22) NOT NULL
);
```

Controller
```php
public function test2()
{
    $db = \Config\Database::connect();
    $toInsert[] = [
        'name' => 'aaaa'
    ];
    $toInsert[] = [
        'name' => null
    ];
    try {
        $db->transBegin();
        $query = $this->db->table('public.test');
        if ($query->insertBatch($toInsert) === false) {
            d($db->error());
            d('Error from IF');
            $db->transRollback();
        }
        else
        {
            $db->transCommit();
        }
    } catch (DatabaseException $th) {
        d($th->getMessage());
        d('Error from TRY');
        $db->transRollback();
    }
}
```

### Expected Output

$query->insertBatch($toInsert) === false

### Anything else?

Without the transaction, the code works correctly. With the transaction, there is an error.   pg_affected_rows(): Argument #1 ($result) must be of type PgSql\Result, bool given

### PR DESCRIPTION
**Pull request by michalsn**
**Description**
This PR fixes a bug in the `Postgre` and `SQLSRV` handlers when calling `Builder::affectedRows()` after a failed query.

This is because when `Builder::affectedRows()` is called after a failed query, the `$resultID` is set to `false`, and a boolean value is not acceptable for either `pg_affected_rows()` or `sqlsrv_rows_affected()`.

Fixes #9362

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPDoc blocks, only if necessary or adds value
- [x] Unit testing, with >80% coverage
- [x] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

File: tests/system/Database/Live/InsertTest.php [hunk 1]
```diff
@@ -79,13 +80,41 @@ public function testInsertBatch(): void
...
+            [
+                'name' => null,
+            ],
+        ];
+
+        $db = $this->db;
+
+        if ($this->db->DBDriver === 'MySQLi') {
+            // strict mode is required for MySQLi to throw an exception here
+            $config                    = config('Database');
```
Comment (paulbalandan) [inline tests/system/Database/Live/InsertTest.php:109]: can you not use the shared config so the strict mode will not persist in other tests?

Comment (michalsn) [reply tests/system/Database/Live/InsertTest.php:109]: I thought the factories were reset during `setUp()`?

https://github.com/codeigniter4/CodeIgniter4/blob/develop/system/Test/CIUnitTestCase.php#L58

Comment (paulbalandan) [reply tests/system/Database/Live/InsertTest.php:109]: Oh, ok forgot that.

**Review by paulbalandan — APPROVED** [review]

**Review by samsonasik — APPROVED** [review]

**Comment by michalsn** [comment]
Thank you everyone!
