### PR TITLE
fix: Validation raises TypeError when invalid JSON comes

### LINKED ISSUE #8134: Error: Argument #2 ($array) must be of type array, null given - Validation.php
### PHP Version

8.2

### CodeIgniter4 Version

4.4.3

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

cli-server (PHP built-in webserver)

### Database

_No response_

### What happened?

`CodeIgniter\\Validation\\DotArrayFilter::run(): Argument #2 ($array) must be of type array, null given, called in ...\\vendor\\codeigniter4\\framework\\system\\Validation\\Validation.php on line 203`

### Steps to Reproduce

I have the next code:
```php

if (
            !$this->validate(
                [
                    'start' => [
                        'label' => 'Inicio',
                        'rules' => 'if_exist|numeric|integer|is_natural',
                    ],
                    'length' => [
                        'label' => 'Limite',
                        'rules' => 'if_exist|numeric|integer|is_natural_no_zero',
                    ],
                    'columns' => [
                        'label' => 'Columnas',
                        'rules' => 'if_exist|valid_json',
                    ],
                    'order' => [
                        'label' => 'Orden',
                        'rules' => 'if_exist|required_with[columns]|valid_json',
                    ],
                    'filters' => [
                        'label' => 'Filtros',
                        'rules' => 'if_exist|valid_json',
                    ],
                ]
            )
        ) {
            $errores = validation_errors();

            return response()->setJSON(
                [
                    'estado' => false,
                    'msje'   => view_cell(
                        'AlertCell',
                        [
                            'tipo'      => 'warning',
                            'contenido' => ul($errores, ['class' => 'mb-0']),
                        ]
                    ),
                    'errores' => $errores,
                    // Propiedad del datatable para respuesta de error
                    'error'   => current($errores),
                ]
            );
        }
```

and returns:

```
{
    "title": "TypeError",
    "type": "TypeError",
    "code": 500,
    "message": "CodeIgniter\\Validation\\DotArrayFilter::run(): Argument #2 ($array) must be of type array, null given, called in C:\\Users\\xonip\\OneDrive - ADN ERP S.A.S\\www\\local_html\\macc\\vendor\\codeigniter4\\framework\\system\\Validation\\Validation.php on line 203",
    "file": "C:\\Users\\xonip\\OneDrive - ADN ERP S.A.S\\www\\local_html\\macc\\vendor\\codeigniter4\\framework\\system\\Validation\\DotArrayFilter.php",
    "line": 29,
    "trace": [
        {
            "file": "C:\\Users\\xonip\\OneDrive - ADN ERP S.A.S\\www\\local_html\\macc\\vendor\\codeigniter4\\framework\\system\\Validation\\Validation.php",
            "line": 203,
            "function": "run",
            "class": "CodeIgniter\\Validation\\DotArrayFilter",
            "type": "::"
        },
        {
            "file": "C:\\Users\\xonip\\OneDrive - ADN ERP S.A.S\\www\\local_html\\macc\\vendor\\codeigniter4\\framework\\system\\Controller.php",
            "line": 152,
            "function": "run",
            "class": "CodeIgniter\\Validation\\Validation",
            "type": "->"
        },
        {
            "file": "C:\\Users\\xonip\\OneDrive - ADN ERP S.A.S\\www\\local_html\\macc\\app\\Controllers\\InformacionController.php",
            "line": 33,
            "function": "validate",
            "class": "CodeIgniter\\Controller",
            "type": "->"
        },
        {
            "file": "C:\\Users\\xonip\\OneDrive - ADN ERP S.A.S\\www\\local_html\\macc\\vendor\\codeigniter4\\framework\\system\\CodeIgniter.php",
            "line": 942,
            "function": "list",
            "class": "App\\Controllers\\InformacionController",
            "type": "->"
        },
        {
            "file": "C:\\Users\\xonip\\OneDrive - ADN ERP S.A.S\\www\\local_html\\macc\\vendor\\codeigniter4\\framework\\system\\CodeIgniter.php",
            "line": 502,
            "function": "runController",
            "class": "CodeIgniter\\CodeIgniter",
            "type": "->"
        },
        {
            "file": "C:\\Users\\xonip\\OneDrive - ADN ERP S.A.S\\www\\local_html\\macc\\vendor\\codeigniter4\\framework\\system\\CodeIgniter.php",
            "line": 361,
            "function": "handleRequest",
            "class": "CodeIgniter\\CodeIgniter",
            "type": "->"
        },
        {
            "file": "C:\\Users\\xonip\\OneDrive - ADN ERP S.A.S\\www\\local_html\\macc\\public\\index.php",
            "line": 79,
            "function": "run",
            "class": "CodeIgniter\\CodeIgniter",
            "type": "->"
        },
        {
            "file": "C:\\Users\\xonip\\OneDrive - ADN ERP S.A.S\\www\\local_html\\macc\\vendor\\codeigniter4\\framework\\system\\Commands\\Server\\rewrite.php",
            "line": 47,
            "args": [
                "C:\\Users\\xonip\\OneDrive - ADN ERP S.A.S\\www\\local_html\\macc\\public\\index.php"
            ],
            "function": "require_once"
        }
    ]
}
```

### Expected Output

a JSON of data or a JSON with invalid input information

### Anything else?

This was working in CI **4.4.2**

### PR DESCRIPTION
**Pull request by kenjis**
~~Needs #8161~~

**Description**
Fixes #8134

- `IncomingRequest` will throw `HTTPException` when the body is invalid as JSON
- add lang key `HTTP.invalidJSON`.

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [x] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Review by michalsn — COMMENTED** [review]
Seems like we need special treatment when the body is `null`.

**Comment by kenjis** [comment]
How? 

When is the `body` null?
https://github.com/codeigniter4/CodeIgniter4/blob/develop/system/HTTP/IncomingRequest.php#L153
Ah, when sending `0` or `''`as body?

**Comment by kenjis** [comment]
I sent #8161

File: system/HTTP/IncomingRequest.php [hunk 1]
```diff
@@ -568,10 +568,18 @@ public function getVar($index = null, $filter = null, $flags = null)
...
      * @return array|bool|float|int|stdClass|null
+     *
+     * @throws HTTPException When the body is invalid as JSON.
      */
     public function getJSON(bool $assoc = false, int $depth = 512, int $options = 0)
     {
-        return json_decode($this->body ?? '', $assoc, $depth, $options);
+        $result = json_decode($this->body ?? '', $assoc, $depth, $options);
+
+        if (json_last_error() !== JSON_ERROR_NONE) {
```
Comment (MGatner) [inline system/HTTP/IncomingRequest.php:578]: I think we need to check for `JSON_THROW_ON_ERROR`. From the docs:
> Returns the last error (if any) occurred during the last JSON encoding/decoding, which did not specify JSON_THROW_ON_ERROR.
https://www.php.net/manual/en/function.json-last-error.php

```suggestion
        if ($options & JSON_THROW_ON_ERROR === 0 && json_last_error() !== JSON_ERROR_NONE) {
```

File: tests/system/Validation/ValidationTest.php [hunk 2]
```diff
@@ -789,6 +790,25 @@ public function testJsonInput(): void
...
+
+        $rules = [
+            'role' => 'if_exist|max_length[5]',
+        ];
+        $this->validation
+            ->withRequest($request->withMethod('POST'))
+            ->setRules($rules)
+            ->run();
+    }
+
```
Comment (MGatner) [inline tests/system/Validation/ValidationTest.php:811]: Based on my comment above it would be good to add a test or two around proper handling with `JSON_THROW_ON_ERROR`

**Review by MGatner — CHANGES_REQUESTED** [review]

File: system/HTTP/IncomingRequest.php (hunk 1 above)
Comment (kenjis) [reply system/HTTP/IncomingRequest.php:578]: Why is the check needed? 
If `JSON_THROW_ON_ERROR` is specified, `json_decode()` throws an Exception already.
If there is an error in decoding, we do not reach this `if` statement.

Comment (michalsn) [reply system/HTTP/IncomingRequest.php:578]: I don't think we need this.

Comment (paulbalandan) [reply system/HTTP/IncomingRequest.php:578]: `JSON_THROW_ON_ERROR` is used inside `json_(de|en)code`.

How about put the json_decode with JSON_THROW_ON_ERROR inside a try/catch?

Comment (michalsn) [reply system/HTTP/IncomingRequest.php:578]: We can, but why do we want to hide the native exception? If I use `JSON_THROW_ON_ERROR` flag, I expect `JsonException` to be thrown.

**Comment by kenjis** [comment]
> Seems like we need special treatment when the body is `null`.

Done.

File: system/HTTP/IncomingRequest.php (hunk 1 above)
Comment (kenjis) [reply system/HTTP/IncomingRequest.php:587]: In this case, a dev sets `JSON_THROW_ON_ERROR` intentionally.
So I also think we don't need to convert `JsonException` to a framework exception.

File: tests/system/Validation/ValidationTest.php (hunk 2 above)
Comment (kenjis) [reply tests/system/Validation/ValidationTest.php:811]: Added a test to show the behavior.

**Review by michalsn — APPROVED** [review]

File: system/HTTP/IncomingRequest.php (hunk 1 above)
Comment (MGatner) [reply system/HTTP/IncomingRequest.php:587]: Yes I was wrong: the if statement is only reached when it doesn't throw so the check is unnecessary. My mistake.

**Review by MGatner — APPROVED** [review]
