### PR TITLE
fix: incorrect metadata querying of Redis cache

### LINKED ISSUE #7304: Bug: Cache RedisHandler Always Returns null MetaData if a prefix is Set
### PHP Version

8.2

### CodeIgniter4 Version

4.3.2

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

cli-server (PHP built-in webserver)

### Database

_No response_

### What happened?

When a prefix is provided for the Redis cache handler, the `getMetaData()` method always returns null.

### Steps to Reproduce

1. Set up Redis handler in the file `App\Config\Cache.php`.
2. Set the handler `redis`.
3. Set a key prefix.
4. Provide the appropriate Redis configuration.
5. Ensure that Redis is valid handler.

Now try to store any value in the Redis caching using the service.
Try to access the metadata using the method `getMetaData()`.
It will be received null.

### Expected Output

Proper Metadata array about the existing cache key.

### Anything else?

In the file `system\Cache\Handlers\RedisHandler.php` [Line #236](https://github.com/codeigniter4/CodeIgniter4/blob/develop/system/Cache/Handlers/RedisHandler.php#L236),
the `key` is validated and the `prefix` is prepended.
In the next line the `get()` method is called which again prepend the `prefix`.

Hence, prepending the `prefix` twice turns the `key` into an always non-existing key.
The resolution is exchanging the order of execution for both lines.
```php
public function getMetaData(string $key)
    {
        $value = $this->get($key);
        $key   = static::validateKey($key, $this->prefix);

        if ($value !== null) {
            $time = Time::now()->getTimestamp();
            $ttl  = $this->redis->ttl($key);

            return [
                'expire' => $ttl > 0 ? $time + $ttl : null,
                'mtime'  => $time,
                'data'   => $value,
            ];
        }

        return null;
    }
```

### PR DESCRIPTION
**Pull request by paulbalandan**
**Description**
Fixes #7304 

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPDoc blocks, only if necessary or adds value
- [x] Unit testing, with >80% coverage
- [ ] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

File: tests/system/Cache/Handlers/RedisHandlerTest.php [hunk 1]
```diff
@@ -198,6 +198,15 @@ public function testGetCacheInfo()
         $this->assertIsArray($this->handler->getCacheInfo());
     }
 
+    public function testGetMetadataNotNull(): void
+    {
+        $this->handler->save(self::$key1, 'value');
+
+        $metadata = $this->handler->getMetaData(self::$key1);
```
Comment (kenjis) [inline tests/system/Cache/Handlers/RedisHandlerTest.php:205]: Please add an empty line.
Arrange-Act-Assert.
See https://automationpanda.com/2020/07/07/arrange-act-assert-a-pattern-for-writing-good-tests/

**Review by kenjis — APPROVED** [review]

**Comment by kenjis** [comment]
@paulbalandan Thank you!
