### PR TITLE
fix: use `addHeader()`

### LINKED ISSUE #5041: Bug: CURLRequest keeps the last value provided by headers with the same name
It is not possible to get and forward all headers having multiple values of a response when performing a CURLRequest.
My experience was with 'set-cookie' header, but after investigating it was pretty obvious that the CURLRequest (and probably other involved or related classes) will only retain the last value of headers with the same name and in case of redirection trigger ErrorException: Header may not contain more than a single header, new line detected (SYSTEMPATH/HTTP/ResponseTrait.php at line 471).

The following fixed the issue for me:
----------------------------------------------------------------------------------------
System\HTTP\CURLRequest
```php
    protected function parseOptions(array $options)
    {
        if (array_key_exists('baseURI', $options)) {
            $this->baseURI = $this->baseURI->setURI($options['baseURI']);
            unset($options['baseURI']);
        }

        if (array_key_exists('headers', $options) && is_array($options['headers'])) {
            foreach ($options['headers'] as $name => $value) {
                // my adjustment
                if($this->hasHeader($name)) {
                    $this->appendHeader($name, $value);
                } else {
                    $this->setHeader($name, $value);
                }
                // end my adjustment
            }

            unset($options['headers']);
        }
...
```

----------------------------------------------------------------------------------------
System\HTTP\ResponseTrait
```php
    public function sendHeaders()
    {
        // Have the headers already been sent?
        if ($this->pretend || headers_sent()) {
            return $this;
        }

        // Per spec, MUST be sent with each request, if possible.
        // http://www.w3.org/Protocols/rfc2616/rfc2616-sec13.html
        if (! isset($this->headers['Date']) && PHP_SAPI !== 'cli-server') {
            $this->setDate(DateTime::createFromFormat('U', (string) time()));
        }

        // HTTP Status
        header(sprintf('HTTP/%s %s %s', $this->getProtocolVersion(), $this->getStatusCode(), $this->getReason()), true, $this->getStatusCode());

        // Send all of our headers
        foreach (array_keys($this->getHeaders()) as $name) {
            // my adjustment
            $headerValue = $this->getHeader($name)->getValue();
            if(is_array($headerValue)) {
                foreach($headerValue as $h_value) {
                    header($name . ': ' . $h_value, false, $this->getStatusCode());
                }
            } else {
                header($name . ': ' . $this->getHeaderLine($name), false, $this->getStatusCode());
            }
        // end my adjustment
        }

        return $this;
    }
```

**CodeIgniter 4 version**
4.1.3

**Affected module(s)**
System\HTTP\CURLRequest
System\HTTP\ResponseTrait
probably some of the other classes as well 

**Expected behavior, and steps to reproduce if appropriate**
1. Perform a CURLRequest
2. Obtain response with multiple values for i.e. 'set-cookie' header: expected - all values, obtained - the last value 
3. Redirect to endpoint while passing all 'set-cookie' headers: expected - redirection OK, obtained - error

**Context**
All

### PR DESCRIPTION
**Pull request by kenjis**
**Description**
Follow-up #8194
Fixes #5041

**Checklist:**
- [x] Securely signed commits
- [x] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Comment by NicolaeIotu** [comment]
I'm setting up the environment and revert when done testing

**Review by NicolaeIotu — CHANGES_REQUESTED** [review]
Hi,

Not recommended for production as it is.
I tested these changes and found the following:
1. Cannot find method **addHeader**. Is this method added recently? Action: replaced with method **appendHeader** and continued testing
2. File **system/HTTP/CURLRequest.php** @ change "**if ($this->response instanceof Response) {**": this check may be feasible but not here. If **$this->response** is not a Response why **$this->response->setHeader(...** ? and what is the connection with the existence of a certain header? Action: replaced with "**if ($this->response->hasHeader($title)) {**" and continued testing
3. This observation may or may not be correct or acceptable for the framework. I'm personally redirecting while appending set-cookie headers obtained from a remote CURLRequest. When this happens my proposal is able to detect all the headers (including the ones appended manually) and '_sendHeaders_' correctly in file **system/HTTP/ResponseTrait.php**. This is a sensitive syntax or you won't be able to get all the headers:
```php
foreach (array_keys($this->headers()) as $name)
{
        $headerValue = $this->getHeader($name)->getValue();
        // !!! custom adjustment to framework
        if(is_array($headerValue)) {
                foreach ($headerValue as $h_value) {
                        header($name . ': ' . $h_value, false, $this->getStatusCode());
                }
        } else {
                header($name . ': ' . $this->getHeaderLine($name), false, $this->getStatusCode());
        }
}
```

Bottom line is that the change in file **system/HTTP/ResponseTrait.php** may be correct, but cannot detect all the headers including the ones set manually.

--------------------------------------------------------------------------------------------------
The following is probably a subject for another PR.
When CURLRequest 'verify' is set to *false* the only action taken is "$curlOptions[CURLOPT_SSL_VERIFYPEER] = $config['verify']". 
This may appear to be correct, but actually it relies on a few defaults and assumptions which are mostly correct except for some use cases.
If the request is done to services on private networks where there is no intention or possibility of making host checks when doing SSL requests, then these requests will fail.
For my purposes I'm just adding the following:
```php
if ($config['verify'] === FALSE) {
    $curlOptions[CURLOPT_SSL_VERIFYHOST] = 0;
}
```
Note that requests to services on private networks are something common nowadays. It may be useful to add an option for CURLOPT_SSL_VERIFYHOST. Some will want to make the checks and some will want to skip this check.
For example the tool **curl** has the option **-k** which skips any SSL checks. This is very useful on private networks a.o. cases.

That's all I could find for now. I really hope it helps.

**Comment by kenjis** [comment]
> Cannot find method addHeader. Is this method added recently? Action: replaced with method appendHeader and continued testing

Can you tell us what you did to test this?
You must checkout this PR branch or download the branch.
https://github.com/kenjis/CodeIgniter4/tree/fix-use-addHeader

**Comment by kenjis** [comment]
The `CURLOPT_SSL_VERIFYHOST` thing has nothing to do with this PR, so please don't put it here. 
It will be forgotten once this PR is completed.
If you think it is a bug, please submit a PR or create an Issue.

**Comment by NicolaeIotu** [comment]
Okay. Found the branch. I'm gonna revert when done testing because I have to merge again with my implementation. Sorry for the delay.
As far as I can see in order to make a PR you need a fork of the project and a branch which will include some commits. Is that correct technically?

File: system/Cache/ResponseCache.php [hunk 1]
```diff
@@ -99,8 +100,14 @@ public function make($request, ResponseInterface $response): bool
 
         $headers = [];
 
-        foreach ($response->headers() as $header) {
-            $headers[$header->getName()] = $header->getValueLine();
+        foreach ($response->headers() as $name => $value) {
+            if ($value instanceof Header) {
+                $headers[$name] = $value->getValueLine();
+            } else {
+                foreach ($value as $header) {
```
Comment (NicolaeIotu) [inline system/Cache/ResponseCache.php:107]: If not Header then it's not automatically an array. Why not check if it is an array?

File: system/HTTP/ResponseTrait.php [hunk 2]
```diff
@@ -398,8 +398,22 @@ public function sendHeaders()
...
+                );
+            } else {
+                foreach ($value as $header) {
+                    header(
+                        $name . ': ' . $header->getValueLine(),
+                        false,
+                        $this->getStatusCode()
+                    );
+                }
+            }
```
Comment (NicolaeIotu) [inline system/HTTP/ResponseTrait.php:416]:
```suggestion
        foreach (array_keys($this->headers()) as $name)
        {
            $headerValue = $this->getHeader($name)->getValue();
            if(is_array($headerValue)) {
                foreach ($headerValue as $h_value) {
                    header($name . ': ' . $h_value, false, $this->getStatusCode());
                }
            } else {
                header($name . ': ' . $this->getHeaderLine($name), false, $this->getStatusCode());
            }
        }
```

File: system/HTTP/CURLRequest.php [hunk 3]
```diff
@@ -479,10 +479,14 @@ protected function setResponseHeaders(array $headers = [])
     {
         foreach ($headers as $header) {
             if (($pos = strpos($header, ':')) !== false) {
-                $title = substr($header, 0, $pos);
-                $value = substr($header, $pos + 1);
+                $title = trim(substr($header, 0, $pos));
+                $value = trim(substr($header, $pos + 1));
 
-                $this->response->setHeader($title, $value);
+                if ($this->response instanceof Response) {
```
Comment (NicolaeIotu) [inline system/HTTP/CURLRequest.php:485]:
```suggestion
                if ($this->response->hasHeader($title)) {
```

File: system/HTTP/RedirectResponse.php [hunk 4]
```diff
@@ -161,8 +161,14 @@ public function withCookies()
...
     {
-        foreach (Services::response()->headers() as $name => $header) {
-            $this->setHeader($name, $header->getValue());
+        foreach (Services::response()->headers() as $name => $value) {
+            if ($value instanceof Header) {
+                $this->setHeader($name, $value->getValue());
+            } else {
+                foreach ($value as $header) {
+                    $this->addHeader($name, $header->getValue());
+                }
```
Comment (NicolaeIotu) [inline system/HTTP/RedirectResponse.php:170]:
```suggestion
                if(is_array($value)) {
                    foreach ($value as $header) {
                        $this->addHeader($name, $header->getValue());
                    }
                }
```

**Review by NicolaeIotu — COMMENTED** [review]
Done testing.

File **ResponseTrait.php**:  I cannot make it work without the suggested changes. 

For file **CURLRequest.php** I think we can agree to replace **if ($this->response instanceof Response) {** with **if ($this->response->hasHeader($title)) {**.

Others changes are only suggestions in order to avoid any errors.

**Comment by kenjis** [comment]
> As far as I can see in order to make a PR you need a fork of the project and a branch which will include some commits. Is that correct technically?

Yes, you can send one PR with one branch.

File: system/HTTP/CURLRequest.php (hunk 3 above)
Comment (kenjis) [reply system/HTTP/CURLRequest.php:485]: We cannot remove `if ($this->response instanceof Response)` because the type of `$this->response` is `ResponseInterface`, and it does not have the `addHeader()` method.

File: system/HTTP/ResponseTrait.php (hunk 2 above)
Comment (kenjis) [reply system/HTTP/ResponseTrait.php:416]: I don't know why my code does not work for you.
It seems your code does the same thing.

What was wrong? Any error message?
