### PR TITLE
fix: `Postgre\Connection::reconnect()` `TypeError` in `pg_ping()`

### LINKED ISSUE #9043: Bug: TypeError in pg_ping()
### PHP Version

8.3

### CodeIgniter4 Version

4.5.3

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

macOS

### Which server did you use?

apache

### Database

PostgreSQL 16.3

### What happened?

pg_ping() expects the first parameter to be a PostgreSQL connection (or null), but receives the boolean value false.

See also https://github.com/codeigniter4/queue/issues/45#issue-2401691847

This is a blocker for other packages.

Screenshot 2024-07-11 at 05 47 49

### Steps to Reproduce

```php
$db = db_connect();
d($db->connect());
d($db->close());
d($db->reconnect());
d($db->getDatabase());
d($db->getVersion());
dd();
``` 

### Expected Output

The output should show the db name and db driver version.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by ping-yee**
**Description**
Fix #9043

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [x] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

File: system/Database/Postgre/Connection.php [hunk 1]
```diff
@@ -149,8 +149,8 @@ private function convertDSN()
      */
     public function reconnect()
     {
-        if (pg_ping($this->connID) === false) {
-            $this->connID = false;
+        if ($this->connID === false || pg_ping($this->connID) === false) {
+            $this->connect();
```
Comment (michalsn) [inline system/Database/Postgre/Connection.php:153]: Actually, I think it would be better to use the `initialize()` method because it will take into account all the settings (including failover). 
```suggestion
            $this->close();
            $this->initialize();
```

Comment (ping-yee) [reply system/Database/Postgre/Connection.php]: Done.

**Review by samsonasik — APPROVED** [review]

File: user_guide_src/source/changelogs/v4.5.6.rst [hunk 2]
```diff
@@ -40,6 +40,7 @@ Bugs Fixed
 - **Routing:** Fixed a TypeError in `str_replace()` when `Routing::$translateURIDashes` is set to `true` and a route is defined using a closure.
 
 - **Validation:** Fixed a bug where complex language strings were not properly handled.
+- **PostgreSQL Connection:** Fixed bug that PostgreSQL cannot reconnect the database with ``reconnect()`` method.
```
Comment (michalsn) [inline user_guide_src/source/changelogs/v4.5.6.rst:43]:
```suggestion
- **Database:** Fixed a bug that caused ``Postgre\Connection::reconnect()`` method to throw an error when the connection had not yet been established.
```

**Review by michalsn — CHANGES_REQUESTED** [review]
Can we change a changelog entry to be more specific?

File: user_guide_src/source/changelogs/v4.5.6.rst (hunk 2 above)
Comment (ping-yee) [reply user_guide_src/source/changelogs/v4.5.6.rst]: Done.

**Comment by paulbalandan** [comment]
Hi @ping-yee ,  one last rebase please and we can merge this. Thank you!

**Review by paulbalandan — APPROVED** [review]

**Comment by paulbalandan** [comment]
Thank you, @ping-yee . I rebased your branch.
