### PR TITLE
fix: CI returns "200 OK" when PageNotFound

### LINKED ISSUE #8009: Bug: CI returns 200 OK even though the route does not exist
### PHP Version

8.2

### CodeIgniter4 Version

4.4.1

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### Database

_No response_

### What happened?

Codeigniter 4.4.1 responds with code **200 OK** when a Fetch request is made even if the route does not exist.

### Steps to Reproduce

1. These are my defined routes.

image

2. In the browser, modify the 'action' attribute in the form for the '**usuarios/nuevo**' route, placing it as '**usuarios/nuevoss**', _POST_ method.

image

3. The request is sent and the response was 200 OK.

image

4. And upon reviewing the response content it was the following.

```
{
    "title": "CodeIgniter\\Exceptions\\PageNotFoundException",
    "type": "CodeIgniter\\Exceptions\\PageNotFoundException",
    "code": 404,
    "message": "Can't find a route for 'post: usuarios/nuevoss'.",
    "file": "C:\\Users\\xonip\\www\\local_html\\macc\\vendor\\codeigniter4\\framework\\system\\CodeIgniter.php",
    "line": 966,
    "trace": [
        {
            "file": "C:\\Users\\xonip\\www\\local_html\\macc\\vendor\\codeigniter4\\framework\\system\\CodeIgniter.php",
            "line": 966,
            "function": "forPageNotFound",
            "class": "CodeIgniter\\Exceptions\\PageNotFoundException",
            "type": "::"
        },
        {
            "file": "C:\\Users\\xonip\\www\\local_html\\macc\\vendor\\codeigniter4\\framework\\system\\CodeIgniter.php",
            "line": 362,
            "function": "display404errors",
            "class": "CodeIgniter\\CodeIgniter",
            "type": "->"
        },
        {
            "file": "C:\\Users\\xonip\\www\\local_html\\macc\\public\\index.php",
            "line": 79,
            "function": "run",
            "class": "CodeIgniter\\CodeIgniter",
            "type": "->"
        },
        {
            "file": "C:\\Users\\xonip\\www\\local_html\\macc\\vendor\\codeigniter4\\framework\\system\\Commands\\Server\\rewrite.php",
            "line": 47,
            "args": [
                "C:\\Users\\xonip\\www\\local_html\\macc\\public\\index.php"
            ],
            "function": "require_once"
        }
    ]
}
```

### Expected Output

The response code that CI should send is 404.

image

since the route '**usuarios/nuevoss**' does not exist in the route declarations.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by kenjis**
**Description**
Fixes #8009

Navigate to `http://localhost:8080/404`, you will get "200 OK" status code.

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [x] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

File: system/CodeIgniter.php [hunk 1]
```diff
@@ -979,8 +979,7 @@ protected function display404errors(PageNotFoundException $e)
         // Display 404 Errors
         $this->response->setStatusCode($e->getCode());
 
-        echo $this->outputBufferingEnd();
-        flush();
+        $this->outputBufferingEnd();
```
Comment (kenjis) [inline system/CodeIgniter.php:982]: Reading the code now, I don't understand why it was flushing here.
https://github.com/codeigniter4/CodeIgniter4/commit/96a0d4f3#diff-d913ae68414ad947e24e588e6ee68d68194142a8aae52e61e0aab2cc7f120e0cL982
No response headers have been sent yet.

**Review by ddevsr — APPROVED** [review]

File: system/CodeIgniter.php (hunk 1 above)
Comment (MGatner) [reply system/CodeIgniter.php:982]: It looks like @iRedds was just replacing the functionality that was already there.

**Review by MGatner — APPROVED** [review]

**Review by michalsn — APPROVED** [review]
