### PR TITLE
Fix `Model::__call` throwing `BadMethodCallException` on empty results

### LINKED ISSUE #5137: Bug: affctedRows - BadMethodCallException
**Describe the bug**
Calling the affectedRows method through a model instance may throw a BadMethodCallException if the value is zero.

```php
$model = new Model()
$model->set('key', 'value')
            ->where('id', 'nonExistentID')
            ->update();
$model->affectedRows(); // BadMethodCallException 
$model->db->affectedRows(); // 0
```

Since the result of executing the method is zero, and ``empty(0)`` === true, the code below throws an exception.

https://github.com/codeigniter4/CodeIgniter4/blob/4649204306276af6c06bfbd229fb1895fb5b0e4e/system/Model.php#L723-L728

### PR DESCRIPTION
**Pull request by ytetsuro**
Fixes #5137.

**Description**

An error occurs when a method of the Database\Connection class returns a falsy value.

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPdocs
- [x] Unit testing, with >80% coverage
- [ ] User guide updated
- [ ] Conforms to style guide

### CODE REVIEW

File: system/BaseModel.php [hunk 1]
```diff
@@ -1636,11 +1637,13 @@ public function __isset(string $name): bool
      */
     public function __call(string $name, array $params)
     {
-        if (method_exists($this->db, $name)) {
-            return $this->db->{$name}(...$params);
+        if (! method_exists($this->db, $name)) {
+            $className = static::class;
+
+            throw new BadMethodCallException('Call to undefined method ' . $className . '::' . $name);
```
Comment (kenjis) [inline system/BaseModel.php:1643]: It seems this is a breaking change.

Comment (paulbalandan) [reply system/BaseModel.php:1643]: Yes, this is breaking for users using the `BaseModel` for their NoSQL models.

Comment (ytetsuro) [reply system/BaseModel.php:1643]: @kenjis @paulbalandan 

Yes, It's a breaking change, that's for sure. However, I don't understand what the problem is.
I don't know what use case it would be better to call a non-existent method and return null when using NoSQL.
What do NoSQL users call non-existent methods for?

Comment (kenjis) [reply system/BaseModel.php:1643]: We just can't merge breaking changes until the next major version (v5.0).
Because if we change the public API, user's applications may break.

Comment (paulbalandan) [reply system/BaseModel.php:1643]: The problem is we do not know how they implemented this in their code. One I can think of is like this:
```php
class NoSqlModel extends BaseModel
{
    ...
}

// then somewhere in their code
$nosql = new NoSqlModel();

if ($nosql->doSomething() === null) {
    // do something else
}
```

In code above, the user expects a call to non-existent method to return `null`. However, if this be merged, their code would break because it will now throw `BadMethodCallException` instead.

Comment (ytetsuro) [reply system/BaseModel.php]: @kenjis @paulbalandan 

> We just can't merge breaking changes until the next major version (v5.0).
> The problem is we do not know how they implemented this in their code.

I understand.
Thank you.
FIxed it.

File: system/Model.php [hunk 2]
```diff
@@ -714,20 +714,17 @@ public function __isset(string $name): bool
...
     public function __call(string $name, array $params)
     {
-        $result = parent::__call($name, $params);
+        $builder = $this->builder();
+        $result  = null;
 
-        if ($result === null && method_exists($builder = $this->builder(), $name)) {
+        if (method_exists($this->db, $name)) {
+            $result = $this->db->{$name}(...$params);
+        } else if (method_exists($builder, $name)) {
```
Comment (kenjis) [inline system/Model.php:722]: @ytetsuro Fix coding style, please.
Run `composer cs-fix`.

File: system/Model.php [hunk 3]
```diff
@@ -714,20 +714,17 @@ public function __isset(string $name): bool
...
-        }
-
-        if (empty($result)) {
-            if (! method_exists($this->builder(), $name)) {
-                $className = static::class;
-
-                throw new BadMethodCallException('Call to undefined method ' . $className . '::' . $name);
-            }
+        } else {
+            $className = static::class;
```
Comment (paulbalandan) [inline system/Model.php:726]:
```suggestion
```

File: system/Model.php [hunk 4]
```diff
@@ -714,20 +714,17 @@ public function __isset(string $name): bool
...
 
-            return $result;
+            throw new BadMethodCallException('Call to undefined method ' . $className . '::' . $name);
```
Comment (paulbalandan) [inline system/Model.php:727]:
```suggestion
            throw new BadMethodCallException('Call to undefined method ' . static::class . '::' . $name);
```

File: system/Model.php (hunk 2 above)
Comment (ytetsuro) [reply system/Model.php]: @kenjis 

Thanks, response.
Fixed it.

File: system/Model.php (hunk 3 above)
Comment (ytetsuro) [reply system/Model.php]: @paulbalandan 

Thanks, review.

Fixed it.

**Review by paulbalandan — COMMENTED** [review]
Last thing on my part, I guess. Can you check the return type in L713 of Model. I think it is not accurate and should be `mixed` instead.

**Comment by ytetsuro** [comment]
@paulbalandan 

> Can you check the return type in L713 of Model. I think it is not accurate and should be mixed instead.

Thanks, review.
Fixed it.

**Review by kenjis — APPROVED** [review]

**Review by paulbalandan — APPROVED** [review]

**Comment by paulbalandan** [comment]
Thank you, @ytetsuro
