### PR TITLE
fix: handling binary data for prepared statement

### LINKED ISSUE #9335: Bug: Data stored in SQlite3 blob fields might get truncated when read back
### PHP Version

8.3

### CodeIgniter4 Version

4.5.5

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

cli-server (PHP built-in webserver)

### Database

SQlite3 (built into php 8.3.6 on Ubuntu 24.04)

### What happened?

Binary data stored in SQlite blob fields gets truncated when read back, depending on the content.

### Steps to Reproduce

I'm storing some files as blobs into a SQlite database and because CI's implementation defaults to SQLITE3_TEXT, sometimes when reading the data back it ends up truncated.

The problem appears to be caused by this line:
https://github.com/codeigniter4/CodeIgniter4/blob/develop/system/Database/SQLite3/PreparedQuery.php#L79

If I change the SQLITE3_TEXT constant to SQLITE3_BLOB, then, after saving the data, it's read back correctly. 

### Expected Output

When querying the data from the database I expect it to be returned completely.

### Anything else?

I have attached a sample sqlite database and a sample pdf file that causes this issue.

Inside the database within the "files" table there are two records holding the same data:
id 8 = saved with SQLITE3_TEXT => if I do a strlen on the "content" field, it returns 654 bytes which is wrong 
id 9 = saved with SQLITE3_BLOB => doing a strlen on content gives me 4146790 bytes, which is correct.

```php
    $db = \Config\Database::connect();
    $preparedQuery = $db->prepare(static function($db) {
        return $db->table('files')->insert([
            'filename' => '',
            'mimetype' => '',
            'size' => '',
            'content' => '',
        ]);
    });
    
	$filename = ...;
	$mimetype = ...;
    	$size = ...;
        $content = file_get_contents( ... path to file ...);
        $preparedQuery->execute($filename, $mimetype, $size, $content); 
```

And I'm reading it back like this:
```php
$db = \Config\Database::connect();
$file = $db->table('files')->where('id', $id)->get()->getRow();
dd(strlen($file->content));
```

Maybe the Sqlite driver should default to SQLITE3_BLOB when saving data?
This is the pdf file I uploaded:
[csc-api-v2.0.0.2.pdf](https://github.com/user-attachments/files/18211794/csc-api-v2.0.0.2.pdf)

This is the sample sqlite file:
[notes.zip](https://github.com/user-attachments/files/18211797/notes.zip)

### PR DESCRIPTION
**Pull request by michalsn**
**Description**
This PR fixes problems with handling binary data when working with Prepared Query.

I have not been able to test OCI8 even through the docker on my Mac, so we will see how it goes.

Fixes #9335

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPDoc blocks, only if necessary or adds value
- [x] Unit testing, with >80% coverage
- [ ] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Comment by michalsn** [comment]
@paulbalandan What can we do to make our coding standard respect SQLSRV constants that act like functions?

Problem:
* https://github.com/codeigniter4/CodeIgniter4/actions/runs/12470250839/job/34805029465?pr=9337

Reference:
* https://www.php.net/manual/en/sqlsrv.constants.php#constant.sqlsrv-phptype-stream
* https://learn.microsoft.com/en-us/sql/connect/php/constants-microsoft-drivers-for-php-for-sql-server?view=sql-server-ver16#phptype-constants

**Comment by paulbalandan** [comment]
It seems this is a bug of the `native_function_casing` fixer. For now, we can ignore the file in the config then report to php-cs-fixer.

File: system/Database/OCI8/PreparedQuery.php [hunk 1]
```diff
@@ -74,11 +74,21 @@ public function _execute(array $data): bool
...
+                $binaryData->writeTemporary($data[$key], OCI_TEMP_BLOB);
+                oci_bind_by_name($this->statement, ':' . $key, $binaryData, -1, OCI_B_BLOB);
+            } else {
+                oci_bind_by_name($this->statement, ':' . $key, $data[$key]);
+            }
         }
 
         $result = oci_execute($this->statement, $this->db->commitMode);
 
+        if (isset($binaryData)) {
```
Comment (samsonasik) [inline system/Database/OCI8/PreparedQuery.php:88]: how about add 

```php
$binaryData = null;
```

initialization before foreach, so the check can be updated to:

```php
if ($binaryData instanceof \OCILob)
```

**Review by samsonasik — APPROVED** [review]

**Review by paulbalandan — APPROVED** [review]

**Comment by michalsn** [comment]
Thanks everyone!
