### PR TITLE
Wrap extract calls in IIFEs in View

### LINKED ISSUE #4108: Bug: View rendering,  extracted variables overwrites existed variables(arguments and etc.)
**Direction**

`extract($this->tempData);` can overwrites existed variables

**Describe the bug**

https://github.com/codeigniter4/CodeIgniter4/blob/0489678a54d0a4dab534cb1aaaece3faac459ec3/system/View/View.php#L295
https://github.com/codeigniter4/CodeIgniter4/blob/0489678a54d0a4dab534cb1aaaece3faac459ec3/system/View/View.php#L212

It's can overwrites existed variables (arguments and etc.).

**CodeIgniter 4 version**
4.0.4, master

**Fix**

Need add wrapper-functions to capture output and keep scope resolution, for example:
~~~php
function (string $viewCode, array $viewData): string {
    extract($viewData, EXTR_SKIP);
    ob_start();
    eval('?>' . $viewCode);
    return (string) ob_get_clean();
}
~~~
or
~~~php
function (string $viewCode, array $viewData): string {
     $viewFileHandler = tmpfile();
     fwrite($viewFileHandler, $viewCode);
     unset($viewCode);
     extract($viewData, EXTR_SKIP);
     ob_start();
     include(stream_get_meta_data($viewFileHandler)['uri']);
     fclose($viewFileHandler);
     return (string) ob_get_clean();
}
~~~

### PR DESCRIPTION
**Pull request by paulbalandan**
**Description**
Fixes #4108 

**Checklist:**
- [x] Securely signed commits
- [x] Unit testing, with >80% coverage
- [x] Conforms to style guide

### CODE REVIEW

File: system/View/View.php [hunk 1]
```diff
@@ -219,10 +218,12 @@ public function render(string $view, array $options = null, bool $saveData = nul
...
 		$renderVars = $this->renderVars;
 
-		ob_start();
-		include $this->renderVars['file']; // PHP will be processed
-		$output = ob_get_contents();
-		@ob_end_clean();
+		$output = (function (string $view, array $data): string {
+			extract($data);
+			ob_start();
+			include $view;
```
Comment (WinterSilence) [inline system/View/View.php:224]: if `$this` not used  in views then function must be `static` + need add prefix to parameter names to keep their values, in other case need use `$this->renderVars['file']`, `$this->tempData` instead pass as arguments.

**Review by WinterSilence — CHANGES_REQUESTED** [review]

File: system/View/View.php (hunk 1 above)
Comment (WinterSilence) [reply system/View/View.php:224]: to test:
~~~php
$this->tempData = ['view' => $this];
~~~
