### PR TITLE
fix: migrations not using custom DB connection of migration runner

### LINKED ISSUE #8060: Bug: Migration runner allows a $db but its never passed to the Migration files
### PHP Version

8.0

### CodeIgniter4 Version

4.3.4

### CodeIgniter4 Installation Method

Manual (zip or tar.gz)

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

apache

### Database

Mysql

### What happened?

When running a `new MigrationRunner($config, $db);` we are allowed to pass in a $db as the second param. However this $db is never passed to the actual migration files which means that it will fall back to the default one when running latest/up/regress etc. Furthermore, it can't be assumed that $db is a group because it could be a custom config.

### Steps to Reproduce

1. Create a `$group` and pass it to `$forge = \Config\Database::forge($group);`
2. Run a migration file and outtput `$this->forge` and you'll see it reverts to the default

### Expected Output

The migration files should be using the same $db group / config as the Migration runner.

The solution is to:

1. Amend MigrationRunner `$instance = new $class(Database::forge($this->db));`
2. Within your Migration files add a construct which calls the parent.

```
	public function __construct($forge = null){
		if ($forge) parent::__construct($forge);
	}
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by paulbalandan**
**Description**
Closes  #8060

When using custom array connection for migration runner, the migrations ran do not use the custom connection of the runner but instead uses the default shared connection.

**Checklist:**
- [x] Securely signed commits
- [x] Component(s) with PHPDoc blocks, only if necessary or adds value
- [x] Unit testing, with >80% coverage
- [ ] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Comment by paulbalandan** [comment]
I found this bug while working on `phpstan-codeigniter` in trying to add an extension for properly identifying the property types of Entities.

**Comment by kenjis** [comment]
@paulbalandan The code is indeed something wrong, but I don't understand the significance of passing DB connection to MigrationRunner.

**Comment by paulbalandan** [comment]
The use case is this: In order to infer the property types of Entities, I thought of using the database tables and the fields. So, I must run migrations in order to get the tables. However, I don't want to mess with the migrations of the end users so I thought of running the migrations in a separate connection. So, regardless of the default connection of the user, I run my own migrations using `SQLite3` with a database file. I don't use `command('migrate')` because it will use the default group. I don't want either to alter the shared `Config\Database`. So, here comes the array connection. All went smoothly until I am listing all the tables using `$db->listTables()` to find out that the db file only contains the `migrations` table. Upon checking, migration files were found but were ran using the shared connection.

File: system/Database/MigrationRunner.php [hunk 1]
```diff
@@ -839,7 +839,8 @@ protected function migrate($direction, $migration): bool
             throw new RuntimeException($message);
         }
 
-        $instance = new $class();
+        /** @var Migration $instance */
+        $instance = new $class(Database::factory()->loadForge($this->db));
```
Comment (kenjis) [inline system/Database/MigrationRunner.php:843]: Why do you need to add Database::factory() method?

```suggestion
        $instance = new $class(Database::forge($this->db));
```

**Comment by kenjis** [comment]
Okay, so you want to change the DB connection for testing. 
After all, the parameter is for testing.

File: system/Database/MigrationRunner.php (hunk 1 above)
Comment (paulbalandan) [reply system/Database/MigrationRunner.php]: Done.

**Comment by kenjis** [comment]
What should be the group for the added test?

```
sqlite> select * from migrations;
1|2018-01-24-102301|Tests\Support\MigrationTestMigrations\Database\Migrations\Migration_some_migration|tests|Tests\Support\MigrationTestMigrations|1700128890|1
2|2018-01-24-102302|Tests\Support\MigrationTestMigrations\Database\Migrations\Migration_another_migration|tests|Tests\Support\MigrationTestMigrations|1700128890|1
```

**Comment by kenjis** [comment]
It appears that `resetDataCache()` resolves the OCI8 test failures.
See https://github.com/kenjis/CodeIgniter4/pull/138/files#diff-ef065cd29dd2066d73750ad2480b61bf513b037402889ee0c0d9e0fb8b3fca3bR478-R479

File: system/Database/MigrationRunner.php [hunk 2]
```diff
@@ -839,7 +839,8 @@ protected function migrate($direction, $migration): bool
             throw new RuntimeException($message);
         }
 
-        $instance = new $class();
+        /** @var Migration $instance */
+        $instance = new $class(Database::forge($this->db));
```
Comment (kenjis) [inline system/Database/MigrationRunner.php:843]: This is not good.
The Migration class uses the DB connection in the DBForge if you pass it.
But it must use the `$this->DBGroup` if it has the property.

**Comment by kenjis** [comment]
Frankly, Migration is complex and difficult to maintain consistency.

When temporarily changing a DB connection for testing purposes, it seems better to regard that the DB connection as the default group because it is easier to manipulate.

However, it seems a bit odd that the DB group name in the migration history is changed to the default group even if you specify the name of the DB group, e.g., `db1`.

Maybe the following patch is needed.

```diff
--- a/system/Database/MigrationRunner.php
+++ b/system/Database/MigrationRunner.php
@@ -141,10 +141,17 @@ class MigrationRunner
         // Default name space is the app namespace
         $this->namespace = APP_NAMESPACE;
 
-        // get default database group
-        $config      = config(Database::class);
-        $this->group = $config->defaultGroup;
-        unset($config);
+        if (is_string($db)) {
+            $this->group = $db;
+        } else {
+            // We use `defaultGroup` even if $db is ConnectionInterface or config
+            // array. Because this is for testing purposes, and it is easier to
+            // understand and operate as if the migrations were run on the
+            // default group.
+            $config      = config(Database::class);
+            $this->group = $config->defaultGroup;
+            unset($config);
+        }
 
         // If no db connection passed in, use
         // default database group.
@@ -841,7 +848,7 @@ class MigrationRunner
 
         /** @var Migration $instance */
         $instance = new $class(Database::forge($this->db));
-        $group    = $instance->getDBGroup() ?? config(Database::class)->defaultGroup;
+        $group    = $instance->getDBGroup() ?? $this->group;
 
         if (ENVIRONMENT !== 'testing' && $group === 'tests' && $this->groupFilter !== 'tests') {
             // @codeCoverageIgnoreStart
@@ -857,8 +864,6 @@ class MigrationRunner
             return true;
         }
 
-        $this->setGroup($group);
-
         if (! is_callable([$instance, $direction])) {
             $message = sprintf(lang('Migrations.missingMethod'), $direction);
 
```

**Comment by MGatner** [comment]
This is complicated. I'm tracking but let me know if you need me more. Thanks for handling.

File: system/Database/MigrationRunner.php (hunk 2 above)
Comment (paulbalandan) [reply system/Database/MigrationRunner.php:837]: Changed in https://github.com/codeigniter4/CodeIgniter4/pull/8221/commits/fa68681a7da63acc35417d420abd3149e9dc3352

File: system/Database/MigrationRunner.php [hunk 3]
```diff
@@ -138,10 +138,7 @@ public function __construct(MigrationsConfig $config, $db = null)
         // Default name space is the app namespace
         $this->namespace = APP_NAMESPACE;
 
-        // get default database group
-        $config      = config(Database::class);
-        $this->group = $config->defaultGroup;
-        unset($config);
+        $this->group = is_string($db) ? $db : config(Database::class)->defaultGroup;
```
Comment (kenjis) [inline system/Database/MigrationRunner.php:141]: It seems to me that we should include a comment here.

```suggestion
        // Even if a DB connection object is passed, since it is a test,
        // it is assumed to be the default group name.
        $this->group = is_string($db) ? $db : config(Database::class)->defaultGroup;
```

**Review by kenjis — APPROVED** [review]
LGTM!

**Review by lonnieezell — APPROVED** [review]
