### PR TITLE
fix: [Validation] `if_exist` does not work with array data

### LINKED ISSUE #8956: Bug: [Validation] if_exist is not working as intended with arrays
### PHP Version

8.2

### CodeIgniter4 Version

4.4.8

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

apache

### Database

_No response_

### What happened?

Ok so based on the official CodeIgniter 4's documentation, the `if_exist` validation rule is supposed to prevent further validation when the field is not present in the data to validate.

However, I noticed that when sending an array it causes the `if_exist` to misbehave.

### Steps to Reproduce

To reproduce you can use this bit of code:
```PHP
$validation_rules = [
    'foo' => [
        'rules' => 'if_exist|in_list',
        'errors' => [
            'in_list' => 'invalid_parameter'
        ]
     ]
 ];
 $this->validate($validation_rules);
```

and send something like this in the payload (This is from Postman's Body using form-data):
```
foo[0]:bar
```

### Expected Output

The `validate()` function should return `false`

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by kenjis**
**Description**
Fixes #8956

Fixed the bug that If an array is passed, Validation with `if_exist` rule always returns `true`.

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

File: system/Validation/FormatRules.php [hunk 1]
```diff
@@ -29,6 +29,10 @@ class FormatRules
      */
     public function alpha($str = null): bool
     {
+        if (is_array($str)) {
+            return false;
+        }
+
```
Comment (michalsn) [inline system/Validation/FormatRules.php:35]: Why is this check only added here? Shouldn't it also be in other rules?

Comment (kenjis) [reply system/Validation/FormatRules.php]: Because there was an error when running phpunit.
But changing `alpha` is not good.

The Traditional Rules should not be changed as much as possible.
So I reverted it and changed the test code.

> Traditional Rules exist only for backward compatibility. Do not use them in new projects. Even if you are already using them, we recommend switching to Strict Rules.
https://codeigniter4.github.io/CodeIgniter4/libraries/validation.html#traditional-rules

**Review by michalsn — APPROVED** [review]
