### PR TITLE
fix: add dbgroup to model template only when specified as an option

### LINKED ISSUE #8073: Bug: Models declared in the App namespace references the 'default' database group in Tests.
### PHP Version

8.2

### CodeIgniter4 Version

4.4.2

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### Database

MariaDB 10.4.18

### What happened?

When I try to run unit tests on models declared in the App namespace, the models only reference the default database and not the test database.

And when I try to comment the default database, I get the following error:
```text
CodeIgniter\Database\Exceptions\DatabaseException: Unable to connect to the database.
Main connection [MySQLi]: Access denied for user ''@'localhost' (using password: NO)
```
Same thing happens even when the environment is set as TESTING, i.e. `CI_ENVIRONMENT = testing` in the .env file.

### Steps to Reproduce

1. Install Shield to a fresh CodeIgniter installation: `composer require codeigniter4/shield`. This is just to confirm that migrations run in the appropriate _(test)_ database.

2. Create a model (eg. SampleModel.php) via command line: `php spark make:model sample --suffix --table sample_table`

3. Create a migration for the model: `php spark make:migration create_sample_table` and add fields for the `up()` method like so:
```php
$this->forge->addField([
    'id'                    => ['type' => 'int', 'constraint' => 11, 'unsigned' => true, 'auto_increment' => true],
    'name'                  => ['type' => 'varchar', 'constraint' => 300],
    'description'           => ['type' => 'text', 'null' => true],
    'created_at'            => ['type' => 'datetime'],
    'updated_at'            => ['type' => 'datetime', 'null' => true],
    'deleted_at'            => ['type' => 'datetime', 'null' => true],
]);

$this->forge->addPrimaryKey('id');
$this->forge->createTable('sample_table');
```
Don't forget to drop the table in the `down()` method: `$this->forge->dropTable('sample_table');`

4. Create a test for the model: **test/app/Models/SampleModelTest.php** with the following code:
```php
declare(strict_types=1);

namespace Tests\App\Models;

use App\Models\SampleModel;
use CodeIgniter\Test\CIUnitTestCase;
use CodeIgniter\Test\DatabaseTestTrait;

final class SampleModelTest extends CIUnitTestCase
{
    use DatabaseTestTrait;

    protected $migrate = true;
    protected $migrateOnce = true;
    protected $namespace = null;
    protected $refresh = true;

    public function testSampleModelCanSaveData() : void 
    {
        $model = model(SampleModel::class);
        $result = $model->save([
            'name' => 'asample',
            'description' => 'Lorem ipsum dolor'
        ]);

        $this->assertTrue($result);

        $this->seeInDatabase('sample_table', [
            'name' => 'asample'
        ]);
    }
}
```

5. Create your default and test databases and add the records in your `.env` file: 
```env
# database.default.hostname = localhost
# database.default.database = ci4_app
# database.default.username = root
# database.default.password = 
# database.default.DBDriver = MySQLi
# database.default.DBPrefix =
# database.default.port = 3306

database.tests.hostname = localhost
database.tests.database = ci4_test
database.tests.username = root
database.tests.password = 
database.tests.DBDriver = MySQLi
database.tests.DBPrefix =
database.tests.port = 3306
```
6. Comment the default database and run the test: `vendor\bin\phpunit`

### Expected Output

I expected that the test would run without any error, as models in the App namespace are not supposed to be limited to the default database.

### Anything else?

Commenting the `$DBGroup` property of the model class:
```php
// protected $DBGroup = 'default';`
```
seemed to resolve the issue, as pointed out by @datamweb which makes me to wonder why the 'default' table was hardcoded in the first place.

### PR DESCRIPTION
**Pull request by sammyskills**
**Description**
The property `$DBGroup` should only be added to the generated model template when specified as an option: `--dbgroup`.
Fixes #8073 

**Checklist:**
- [x] Securely signed commits
- [] Component(s) with PHPDoc blocks, only if necessary or adds value
- [] Unit testing, with >80% coverage
- [] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Review by datamweb — COMMENTED** [review]
To be honest, I personally prefer $DBGroup to be like this when creating the model.
```php
protected $DBGroup = null;
```
The reason for this is in the visibility of this property for rapid change during development.
However, this is a personal opinion.

**Comment by kenjis** [comment]
@datamweb I don't know what you exactly means by *rapid change during development*, but I feel strange that writing `protected $DBGroup = null;` in the model by default. 

And more than 90% devs use single db group, I guess.
And, if  a dev changes it to `'default'` by mistake, tests will not work like the reported issue.

**Review by kenjis — APPROVED** [review]
I'm fine, but wait for other people's opinions.

**Comment by datamweb** [comment]
> @datamweb I don't know what you exactly means by _rapid change during development_, but I feel strange that writing `protected $DBGroup = null;` in the model by default.

Imagine that the model is make as follows.
```php
<?php

namespace App\Models;

use CodeIgniter\Model;

class Sample extends Model
{
    protected $table            = 'Sample';
    protected $primaryKey       = 'id';
    protected $useAutoIncrement = true;
    protected $returnType       = 'array';
    protected $useSoftDeletes   = false;
    protected $protectFields    = true;
    protected $allowedFields    = [];

    // Dates
    protected $useTimestamps = false;
    protected $dateFormat    = 'datetime';
    protected $createdField  = 'created_at';
    protected $updatedField  = 'updated_at';
    protected $deletedField  = 'deleted_at';
}
```
Do you realize that there are **Validation** or **Callbacks**? No, you must see the documents.

```php
<?php

namespace App\Models;

use CodeIgniter\Model;

class Sample extends Model
{
    protected $table            = 'Sample';
    protected $primaryKey       = 'id';
    protected $useAutoIncrement = true;
    protected $returnType       = 'array';
    protected $useSoftDeletes   = false;
    protected $protectFields    = true;
    protected $allowedFields    = [];

    // Dates
    protected $useTimestamps = false;
    protected $dateFormat    = 'datetime';
    protected $createdField  = 'created_at';
    protected $updatedField  = 'updated_at';
    protected $deletedField  = 'deleted_at';

    // Validation
    protected $validationRules      = [];
    protected $validationMessages   = [];
    protected $skipValidation       = false;
    protected $cleanValidationRules = true;

    // Callbacks
    protected $allowCallbacks = true;
    protected $beforeInsert   = [];
    protected $afterInsert    = [];
    protected $beforeUpdate   = [];
    protected $afterUpdate    = [];
    protected $beforeFind     = [];
    protected $afterFind      = [];
    protected $beforeDelete   = [];
    protected $afterDelete    = [];
}
```
As a beginner in CodeIgniter, I prefer to have everything in front of my eyes so that I can be aware of the existence of this feature and be curious. Not that I have to constantly read the documentation or even not know about many features. This is very important for me, who is not an English speaker.

> And more than 90% devs use single db group, I guess.
> And, if a dev changes it to `'default'` by mistake, tests will not work like the reported issue.

I agree with you on this.

File: system/Commands/Generators/ModelGenerator.php [hunk 1]
```diff
@@ -101,9 +101,11 @@ protected function prepare(string $class): string
             $baseClass = $match[1];
         }
 
-        $table   = is_string($table) ? $table : plural(strtolower($baseClass));
-        $dbGroup = is_string($dbGroup) ? $dbGroup : 'default';
-        $return  = is_string($return) ? $return : 'array';
+        // Add or remove the DBGroup line based on the presence of the dbgroup option
+        $addDBGroupLine = is_string($dbGroup);
+
```
Comment (paulbalandan) [inline system/Commands/Generators/ModelGenerator.php:106]: I don't think you need this extra variable. Just pass `$dbGroup` to the template and do the `is_string` check there.

Comment (paulbalandan) [reply system/Commands/Generators/ModelGenerator.php:106]: Since you changed the behavior, can you add a test that when `--dbgroup <something>` is passed, it still sets the $DBGroup property.

**Review by paulbalandan — CHANGES_REQUESTED** [review]

File: system/Commands/Generators/ModelGenerator.php (hunk 1 above)
Comment (sammyskills) [reply system/Commands/Generators/ModelGenerator.php:106]: > I don't think you need this extra variable. Just pass `$dbGroup` to the template and do the `is_string` check there.

Noted.

Comment (sammyskills) [reply system/Commands/Generators/ModelGenerator.php:106]: > Since you changed the behavior, can you add a test that when `--dbgroup <something>` is passed, it still sets the $DBGroup property.

That test is already covered here:
https://github.com/codeigniter4/CodeIgniter4/blob/6f81e6e42e996eb1d0eacb2325600f74fefc9307/tests/system/Commands/ModelGeneratorTest.php#L68

**Comment by paulbalandan** [comment]
> I prefer to have everything in front of my eyes so that I can be aware of the existence of this feature and be curious. Not that I have to constantly read the documentation or even not know about many features. This is very important for me, who is not an English speaker.

For me, I don't want code to clutter when I don't have a need for them. Just the needed code to run.

File: system/Commands/Generators/ModelGenerator.php (hunk 1 above)
Comment (paulbalandan) [reply system/Commands/Generators/ModelGenerator.php:106]: Oh I overlooked that.

**Review by kenjis — APPROVED** [review]

**Review by paulbalandan — APPROVED** [review]

**Comment by kenjis** [comment]
@sammyskills Thank you!
