### PR TITLE
fix: Parse error occurs before PHP version check

### LINKED ISSUE #6306: Parse error: syntax error, unexpected '_536_000' (T_STRING), expecting ')'
### PHP Version

7.3

### CodeIgniter4 Version

4

### CodeIgniter4 Installation Method

Manual (zip or tar.gz)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### Database

_No response_

### What happened?

Parse error: syntax error, unexpected '_536_000' (T_STRING), expecting ')' in E:\MYPROJECTS\codignitor\system\Common.php on line 480

### Steps to Reproduce

php spark serve

### Expected Output

This will launch the server and you can now view your application in your browser at http://localhost:8080/.

### Anything else?

image

### PR DESCRIPTION
**Pull request by kenjis**
**Description**
Fixes #6306

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

File: system/CodeIgniter.php [hunk 1]
```diff
@@ -962,6 +950,7 @@ protected function display404errors(PageNotFoundException $e)
             ob_end_flush(); // @codeCoverageIgnore
         }
 
+        // Throws new PageNotFoundException and remove exception message on production.
```
Comment (MGatner) [inline system/CodeIgniter.php:953]: I think this got scooped up by mistake?

**Review by MGatner — APPROVED** [review]

File: system/CodeIgniter.php (hunk 1 above)
Comment (kenjis) [reply system/CodeIgniter.php:953]: Oh, yes. It is not related to this PR.

**Comment by totoprayogo1916** [comment]
then https://github.com/kenjis/CodeIgniter4/blob/6ac3a7bfe48e72b687c5727cd60f88b9724da4ac/system/Language/en/Core.php#L17
should be removed
