### PR TITLE
fix: Validation cannot handle array item

### LINKED ISSUE #5368: Bug: Validation rule can't handle array data
PHP Version

7.4

CodeIgniter4 Version

4,1,5

CodeIgniter4 Installation Method

Composer (new project)

Which operating systems have you tested for this bug?

Linux

Which server did you use?

apache

Database

MariaDB 10.1.31

What happened?
I am trying to create a new rule to check if value "is array" and "array length equals to".
The parameter passed inside the new function doesn't get the array but the array first parameter.

Steps to Reproduce
New rule created as below
> is_array($value) {
 return is_array($value);
}

If you add the new rule inside the validator as below
> $data = [
 'arr' => [1,2,3,4,5],
];
$validation->setRules([
 'arr' => 'is_array',
]);

Validator always return false because the value passed inside the validator is 1 and not the entire array.

Expected Output
Need to get the entire array inside the validator?

Anything else?

### PR DESCRIPTION
**Pull request by kenjis**
**Description**
Supersedes #5402
Fixes #5368
- separate validation process of multiple field and single field

**Checklist:**
- [x] Securely signed commits
- [x] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [x] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Review by MGatner — CHANGES_REQUESTED** [review]
The code is a bit hard to review on mobile but what I see all looks good, and the tests are great. 

Your User Guide write-up is very thorough, but I would rather see that in the changelogs (i.e. ** user_guide_src/source/changelogs/v4.1.6.rst**) and keep the Upgrading section as actual *tasks* that need to be done when upgrading. A simple sentence with reference to the longer explanation in the changelog would be good, like "Due to a bug fix Validation now might ____ (see ____.rst), so make sure you ____ to any code calling it."

**Comment by MGatner** [comment]
Will this conflict with the Strict Validation changes?

**Comment by kenjis** [comment]
@MGatner I added the last commit to fix the docs. I rebased because the commits are not verified.

> Will this conflict with the Strict Validation changes?

No.
#5402 will be split into two PRs. This is one.

**Review by MGatner — APPROVED** [review]
Doc changes look good! Since this is a breaking change I'd like it if you could get another reviewer. I'll ping the team on Slack.

File: system/Validation/Validation.php [hunk 1]
```diff
@@ -139,16 +139,20 @@ public function run(?array $data = null, ?string $group = null, ?string $dbGroup
...
-                // Otherwise, we'll let the loop do the job
-                $this->processRules($field, $setup['label'] ?? $field, $value, $rules, $data);
+            if (strpos($field, '*') !== false && is_array($values)) {
+                // Process multiple fields
+                foreach ($values as $value) {
+                    $this->processRules($field, $setup['label'] ?? $field, $value, $rules, $data);
+                }
+            } else {
+                // Process single field
+                $this->processRules($field, $setup['label'] ?? $field, $values, $rules, $data);
```
Comment (paulbalandan) [inline system/Validation/Validation.php:155]: Since this one is the same with L145, I think we can combine this with that?

File: system/Validation/Validation.php [hunk 2]
```diff
@@ -274,7 +285,8 @@ protected function processRules(string $field, ?string $label, $value, $rules =
                     }
 
                     $found  = true;
-                    $passed = $param === false ? $set->{$rule}($value, $error) : $set->{$rule}($value, $param, $data, $error);
+                    $passed = $param === false ? $set->{$rule}($value, $error)
+                        : $set->{$rule}($value, $param, $data, $error);
```
Comment (paulbalandan) [inline system/Validation/Validation.php:289]: The `operator_linebreak` should break this one.
```suggestion
                    $passed = $param === false
                        ? $set->{$rule}($value, $error)
                        : $set->{$rule}($value, $param, $data, $error);
```

File: system/Validation/Validation.php [hunk 3]
```diff
@@ -295,7 +307,14 @@ protected function processRules(string $field, ?string $label, $value, $rules =
                     $value = json_encode($value);
                 }
 
-                $this->errors[$field] = $error ?? $this->getErrorMessage($rule, $field, $label, $param, $value);
+                $param                = ($param === false) ? '' : $param;
+                $this->errors[$field] = $error ?? $this->getErrorMessage(
```
Comment (paulbalandan) [inline system/Validation/Validation.php:311]: Can we add a line in between? The empty space between `$param` and `=` is quite much.

File: user_guide_src/source/changelogs/v4.1.6.rst [hunk 4]
```diff
@@ -7,12 +7,26 @@ Release Date: Not released
...
 ========
 - Multiple table names will no longer be stored in ``BaseBuilder::$tableName`` - an empty string will be used instead.
 
+.. _changelog-v416-validation-changes:
+
+Validation changes
+------------------
+- The previous version of the Validation can't handle an array item.
+  Because of the bug fix, the validation results may be different,
+  or raise an TypeError.
```
Comment (paulbalandan) [inline user_guide_src/source/changelogs/v4.1.6.rst:22]:
```suggestion
  or raise a ``TypeError``.
```

File: system/Validation/Validation.php (hunk 1 above)
Comment (kenjis) [reply system/Validation/Validation.php:155]: If I remove the `if` statement from L143, tests in `tests/system/Validaton/` passes.
But I'm not sure removing it causes no problem.

What input makes `$values` empty array?

File: system/Validation/Validation.php (hunk 3 above)
Comment (kenjis) [reply system/Validation/Validation.php]: Done.

File: system/Validation/Validation.php (hunk 1 above)
Comment (kenjis) [reply system/Validation/Validation.php:157]: I added `continue` in the `if` to fix the bug that `$this->processRules()` run twice.

File: system/Validation/Validation.php [hunk 5]
```diff
@@ -646,6 +669,9 @@ public function setError(string $field, string $error): ValidationInterface
      */
     protected function getErrorMessage(string $rule, string $field, ?string $label = null, ?string $param = null, ?string $value = null): string
     {
+        $param = $param ?? '';
```
Comment (samsonasik) [inline system/Validation/Validation.php:672]: how about `(string) $param` ? ref https://3v4l.org/NijdY#v7.3.33

**Review by lonnieezell — APPROVED** [review]

File: system/Validation/Validation.php (hunk 5 above)
Comment (kenjis) [reply system/Validation/Validation.php:672]: @samsonasik What is better?

Comment (samsonasik) [reply system/Validation/Validation.php:672]: probably just cast it? 

```suggestion
        $param = (string) $param;
```

Comment (kenjis) [reply system/Validation/Validation.php:672]: `$param` is null or string. So `$param = $param ?? ''` is no problem.

I'm not sure, but it seems @paulbalandan likes `$param = $param ?? ''`.
Is there any advantage of `(string)`?

Comment (samsonasik) [reply system/Validation/Validation.php:672]: oh, ok it seems other file have it as well, ok then 👍

Comment (paulbalandan) [reply system/Validation/Validation.php:672]: I don't know of optimization gains but typing `?? ''` is much faster than `(string)` 😂

File: system/Validation/Validation.php (hunk 1 above)
Comment (paulbalandan) [reply system/Validation/Validation.php:157]: > What input makes `$values` empty array?

This is raised in an issue report. I'll check.

Comment (paulbalandan) [reply system/Validation/Validation.php:157]: https://github.com/codeigniter4/CodeIgniter4/issues/4510#issuecomment-813532899

**Review by samsonasik — APPROVED** [review]

File: system/Validation/Validation.php (hunk 1 above)
Comment (kenjis) [reply system/Validation/Validation.php:157]: I read the comment and the fix PR.
But I'm not sure we can remove the `if ($values === []) { ... }`.
I feel it is safer not to remove it.

Comment (kenjis) [reply system/Validation/Validation.php:157]: @paulbalandan I want to update `upgrade_416.rst`, so I merge this for now.
