### PR TITLE
fix: SMTP connection resource validation in `Email` class destructor

### LINKED ISSUE #9647: Bug: fwrite(): supplied resource is not a valid stream resource
### PHP Version

8.4

### CodeIgniter4 Version

4.6.2

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Linux

### Which server did you use?

apache

### Database

PostgreSQL 9.6

### What happened?

I upgraded from version 4.4.0 to 4.6.2 before, I did not have this error when sending email

### Steps to Reproduce

 // configuration de base des mails
            $config['userAgent'] = 'CodeIgniter';
            $config['protocol'] = 'smtp';
            
            $config['SMTPTimeout'] = 5;
            $config['wordWrap'] = TRUE;
            $config['wrapChars'] = 76;
            $config['mailType'] = 'html';
            $config['charset'] = 'utf-8';
            $config['validate'] = FALSE;
            $config['priority'] = 3;
            $config['CRLF'] = "\r\n";
            $config['newline'] = "\r\n";
            $config['BCCBatchMode'] = FALSE;
            $config['BCCBatchSize'] = 200;

            $config['SMTPCrypto'] = '';
            $config['SMTPHost'] = '10.0.0.2';
            $config['SMTPUser'] = '';
            $config['SMTPPass'] = '';
            $config['SMTPPort'] = 25;
  $email->initialize($config);

            $email->clear(true);

   foreach ($file  as $key => $value) {
                $email->attach($value);
            }

  if ($email->send()) {
                $response['success'] = true;
                $response['messages'] = 'Le mail à bien été transmis au client';
            } else {
                $response['success'] = false;
                $response['messages'] =  $email->printDebugger();
            }

### Expected Output

The email was sent, but I get this error every time I send an email that I didn't have before.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by michalsn**
**Description**
This PR fixes a bug where the destructor was checking `$this->SMTPConnect !== null` to validate SMTP connections.

However, `fclose()` creates closed resources that are not `null`, which led to unnecessary cleanup attempts on already-closed connections.

When the `SMTPKeepAlive` option is `false` (the default), the `quit` command is called before the destructor is reached.

Fixes #9647

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Comment by michalsn** [comment]
No tests are provided, as I'm not sure how this could be tested effectively.

However, since this is a regression from v4.6.1, I believe it's acceptable without tests in this case.

File: system/Email/Email.php [hunk 1]
```diff
@@ -2227,7 +2227,7 @@ protected function mimeTypes($ext = '')
 
     public function __destruct()
     {
-        if ($this->SMTPConnect !== null) {
+        if (is_resource($this->SMTPConnect)) {
```
Comment (paulbalandan) [inline system/Email/Email.php]: This is a fault in my recent refactoring. Sorry for that. 😅

Would the intent be clearer if we make this explicitly check for a live connection?
Like `$this->SMTPConnect !== null && get_debug_type($this->SMTPConnect) !== 'resource (closed)'`. As I remember, I am avoiding here the [non-strict type checking of `is_resource`](https://www.php.net/manual/en/function.is-resource.php#refsect1-function.is-resource-notes) which phpstan is also checking.

Comment (michalsn) [reply system/Email/Email.php]: Ok, I followed your example to avoid `is_resource()` use.

Tested manually - works fine.

Comment (michalsn) [reply system/Email/Email.php]: I also added a check for `false` as this could be returned by `fsockopen` function.

Comment (paulbalandan) [reply system/Email/Email.php]: Can you then add the `false` to the property's PHPDoc.

Comment (michalsn) [reply system/Email/Email.php]: Done

**Review by paulbalandan — APPROVED** [review]

**Comment by samsonasik** [comment]
Thank you @michalsn
