### PR TITLE
fix: Entity's isset() and unset()

### LINKED ISSUE #5495: Bug: Can't unset mapped property in Entitiy
### PHP Version

8.0

### CodeIgniter4 Version

`develop` (60f1367c8ad16c4dea998a9d9a4bb1a7fd48c75c)

### CodeIgniter4 Installation Method

Git

### Which operating systems have you tested for this bug?

macOS

### Which server did you use?

cli

### Database

_No response_

### What happened?

> In this example, when the model sets the full_name field on the User class, it actually assigns that value to the class’ $name property, so it can be set and retrieved through $user->name. The value will still be accessible through the original $user->full_name, also, as this is needed for the model to get the data back out and save it to the database. However, **unset and isset only work on the mapped property, $name, not on the original name, full_name.**
https://codeigniter.com/user_guide/models/entities.html#data-mapping

But unsetting mapped property does not work.

```php
unset($user->name);
```

From https://forum.codeigniter.com/thread-80835.html

**Note**: the user guide says "unset and isset only work on the mapped property", but `isset()` works on the original name.

### Steps to Reproduce

```php
<?php
namespace App\Entities;
use CodeIgniter\Entity\Entity;
class User extends Entity
{
    protected $attributes = [
        'id' => null,
        'name' => null, // Represents a username
        'email' => null,
        'password' => null,
        'created_at' => null,
        'updated_at' => null,
    ];

    protected $datamap = [
        'name' => 'full_name',
    ];
}
```
```php
<?php
namespace App\Controllers;
use App\Entities\User;
class Home extends BaseController
{
    public function index()
    {
        $user = new User();
        echo $user->name . PHP_EOL;

        $user->name = 'John Smith';
        echo $user->name . PHP_EOL;

        unset($user->name);
        echo $user->name . PHP_EOL;
    }
}
```
```sh-session
$ php public/index.php 

John Smith
John Smith
```

### Expected Output

```sh-session
$ php public/index.php 

John Smith

```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by kenjis**
**Description**
- fixes #5495
- fixes `isset()`may work on db column name in some cases

**Checklist:**
- [x] Securely signed commits
- [x] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [x] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

File: system/Entity/Entity.php [hunk 1]
```diff
@@ -530,6 +534,37 @@ public function __isset(string $key): bool
...
+
+    /**
+     * Whether this key is mapped db column name?
+     */
+    protected function isMappedDbColumn(string $key): bool
+    {
+        $maybeColumnName = $this->mapProperty($key);
+
+        // Property name which has mapped column name
+        if (($key !== $maybeColumnName)) {
```
Comment (samsonasik) [inline system/Entity/Entity.php:554]: multiple parentheses can be removed:

```suggestion
        if ($key !== $maybeColumnName) {
```

Comment (kenjis) [reply system/Entity/Entity.php]: Thanks. 
But this should be removed by cs-fixer or rector.

**Review by MGatner — APPROVED** [review]
I think this system is a bit too confusing, but this is a step in the right direction. We might consider a different way to handle this in version 5.

**Comment by kenjis** [comment]
Yes, this is very confusing. At first I didn't understand which is correct the documentation or the implementation.
It is not good design.
