### PR TITLE
fix: failover's DBPrefix not working

### LINKED ISSUE #5812: Bug: failover's DBPrefix not working
### PHP Version

7.4

### CodeIgniter4 Version

4.1.9

### CodeIgniter4 Installation Method

Manual (zip or tar.gz)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### Database

10.4.14-MariaDB

### What happened?

Today I found `failover` option and before integration I had checked this option.

To verify my integration I used these lines of code:
 
```
    public $default = [
        'DSN'      => '',
        'hostname' => 'localhost',
        'username' => 'user',
        'password' => 'pass',
        'database' => 'local_db',
        'DBDriver' => 'MySQLi',
        'DBPrefix' => 'localPrefix_',
        'pConnect' => false,
        'DBDebug'  => (ENVIRONMENT !== 'production'),
        'charset'  => 'utf8mb4',
        'DBCollat' => 'utf8mb4_general_ci',
        'swapPre'  => '',
        'encrypt'  => false,
        'compress' => false,
        'strictOn' => false,
        'failover' => [
            [
                'hostname' => 'remote.db.host',
                'username' => 'remote_user'
                'password' => 'remote_pass!',
                'database' => 'remote_db',
                'DBDriver' => 'MySQLi',
                'DBPrefix' => 'remotePrefix_',
                'pConnect' => true,
                'DBDebug'  => true,
                'charset'  => 'utf8',
                'DBCollat' => 'utf8_general_ci',
                'swapPre'  => '',
                'encrypt'  => false,
                'compress' => false,
                'strictOn' => false,
            ]
        ], 
```

Everything was fine except one option. My MySQL server [default config which host is **localhost**] is **off**, then it's trying to connect to failover's remote.db.host, but it following default config's DBPrefix (localPrefix_) instead of failovers' DBPrefix (remotePrefix_).

That mean's it trying to connect remote_db.localPrefix_myTable instead of remote_db.remotePrefix_myTable

Kindly verify this issue and fix this issue.

### Steps to Reproduce

```
    public $default = [
        'DSN'      => '',
        'hostname' => 'localhost',
        'username' => 'user',
        'password' => 'pass',
        'database' => 'local_db',
        'DBDriver' => 'MySQLi',
        'DBPrefix' => 'localPrefix_',
        'pConnect' => false,
        'DBDebug'  => (ENVIRONMENT !== 'production'),
        'charset'  => 'utf8mb4',
        'DBCollat' => 'utf8mb4_general_ci',
        'swapPre'  => '',
        'encrypt'  => false,
        'compress' => false,
        'strictOn' => false,
        'failover' => [
            [
                'hostname' => 'remote.db.host',
                'username' => 'remote_user'
                'password' => 'remote_pass!',
                'database' => 'remote_db',
                'DBDriver' => 'MySQLi',
                'DBPrefix' => 'remotePrefix_',
                'pConnect' => true,
                'DBDebug'  => true,
                'charset'  => 'utf8',
                'DBCollat' => 'utf8_general_ci',
                'swapPre'  => '',
                'encrypt'  => false,
                'compress' => false,
                'strictOn' => false,
            ]
        ], 
```

### Expected Output

Successful connection to remote.db.host's remote_db.localPrefix_myTable

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by kenjis**
**Description**
Fixes #5812

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

File: system/Database/BaseConnection.php [hunk 1]
```diff
@@ -342,6 +342,13 @@ public function __construct(array $params)
         if (class_exists($queryClass)) {
             $this->queryClass = $queryClass;
         }
+
+        if ($this->failover !== []) {
+            // If there is a failover database, connect now to do failover.
+            // Otherwise, Query Builder creates SQL statement with the main database config
+            // (DBPrefix) even when the main database is down.
+            $this->initialize();
```
Comment (MGatner) [inline system/Database/BaseConnection.php:350]: Is there any reason why we wouldn't always initialize now, for consistency? This seems like it could introduce some strange varying behavior based on whether failover is configured or not.

Comment (kenjis) [reply system/Database/BaseConnection.php:350]: Because this is the minimum change to fix the bug.

Do you accept that removing the `if` and always initialize in the constructor?
It changes the current behavior completely, so it seems a breaking change.

Comment (kenjis) [reply system/Database/BaseConnection.php:350]: It seems calling `initialize()` just before running query came from CI3.

But CI4 has a lot of code like this:
```php
        if (empty($this->connID)) {
            $this->initialize();
        }
```

If we call`initialize()` always in the constructor, we could remove the code.

But the following test code will be fail:
```php
        $db = new MockConnection($this->options);
        $db->shouldReturn('connect', 123)->initialize();
```

**Review by MGatner — APPROVED** [review]

File: system/Database/BaseConnection.php (hunk 1 above)
Comment (kenjis) [reply system/Database/BaseConnection.php:350]: No problem. 
Personally I think calling initialize() always in the constructor is better and cleaner code.

**Review by michalsn — APPROVED** [review]
