### PR TITLE
fix: view cell cannot locate the auto-generated view file

### LINKED ISSUE #7391: Bug: View cell cannot locate the auto-generated view file
### PHP Version

7.4

### CodeIgniter4 Version

4.3.3

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### Database

MariaDB 10.4.18

### What happened?

When I generate a cell via the command `php spark make:cell MyMagicCell`, the command also generates a view file `my_magic_cell.php` which is normal according to the docs, but when I try to use the cell in a view file like so:
```php
<?= view_cell('MyMagicCell::render') ?>
```
I get the following error:
`Error Exception: include(C:\xampp7427\htdocs\pbo\app\Cells\my_magic.php): failed to open stream: No such file or directory`.

Upon troubleshooting, I found out that the `_cell` is actually removed here:
https://github.com/codeigniter4/CodeIgniter4/blob/775a99e6518070dfc05deda8c1f843d08655acf2/system/View/Cells/Cell.php#L77
which conflicts with what is stated in the [docs](https://codeigniter.com/user_guide/outgoing/view_cells.html#controlled-cells).

> Controlled Cells have two primary goals: to make it as fast as possible to build the cell, and provide additional logic and flexibility to your views, if they need it. The class must extend `CodeIgniter\View\Cells\Cell`. They should have a view file in the same folder. **By convention the class name should be PascalCase and the view should be the snake_cased version of the class name. So, for example, if you have a `MyCell` class, the view file should be `my_cell.php`**.

One of two things can be done to resolve this, of which I can send a PR to fix it, but I need to know the direction that should be followed:
- To update the docs to correspond with what the code is actually doing, OR
- To update the code to correspond with the current explanation in the docs.

### Steps to Reproduce

1. Generate a cell: `php spark make:cell MyAwesomeCell` or `php spark make:cell MyAwesome`.
2. Try to view the cell in any of your view files using `view_cell('MyAwesomeCell::render')` or `view_cell('MyAwesome::render)`.

### Expected Output

I expected that the cell's view file would be located without any error.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by sammyskills**
Fixes #7391 

- fix a bug that View Cells cannot load a view file with `_cell` when the classname ends with `Cell`.
- fix a bug that `spark make:cell` creates a view file with `_cell` when the classname does not end with `Cell`.

**Checklist:**
- [x] Securely signed commits
- [x] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Comment by kenjis** [comment]
These errors seem to have nothing to do with this PR.

```
There were 3 errors:

1) CodeIgniter\Images\ImageMagickHandlerTest::testText
CodeIgniter\Images\Exceptions\ImageException: Image processing failed. Please verify that your server supports the chosen protocol and that the path to your image library is correct.

/home/runner/work/CodeIgniter4/CodeIgniter4/system/Images/Handlers/ImageMagickHandler.php:212
/home/runner/work/CodeIgniter4/CodeIgniter4/system/Images/Handlers/ImageMagickHandler.php:408
/home/runner/work/CodeIgniter4/CodeIgniter4/system/Images/Handlers/BaseHandler.php:418
/home/runner/work/CodeIgniter4/CodeIgniter4/tests/system/Images/ImageMagickHandlerTest.php:300
phpvfscomposer:///home/runner/work/CodeIgniter4/CodeIgniter4/vendor/phpunit/phpunit/phpunit:106

2) CodeIgniter\Images\ImageMagickHandlerTest::testMoreText
CodeIgniter\Images\Exceptions\ImageException: Image processing failed. Please verify that your server supports the chosen protocol and that the path to your image library is correct.

/home/runner/work/CodeIgniter4/CodeIgniter4/system/Images/Handlers/ImageMagickHandler.php:212
/home/runner/work/CodeIgniter4/CodeIgniter4/system/Images/Handlers/ImageMagickHandler.php:408
/home/runner/work/CodeIgniter4/CodeIgniter4/system/Images/Handlers/BaseHandler.php:418
/home/runner/work/CodeIgniter4/CodeIgniter4/tests/system/Images/ImageMagickHandlerTest.php:308
phpvfscomposer:///home/runner/work/CodeIgniter4/CodeIgniter4/vendor/phpunit/phpunit/phpunit:106

3) CodeIgniter\Images\ImageMagickHandlerTest::testImageCreation
CodeIgniter\Images\Exceptions\ImageException: Image processing failed. Please verify that your server supports the chosen protocol and that the path to your image library is correct.

/home/runner/work/CodeIgniter4/CodeIgniter4/system/Images/Handlers/ImageMagickHandler.php:212
/home/runner/work/CodeIgniter4/CodeIgniter4/system/Images/Handlers/ImageMagickHandler.php:408
/home/runner/work/CodeIgniter4/CodeIgniter4/system/Images/Handlers/BaseHandler.php:418
/home/runner/work/CodeIgniter4/CodeIgniter4/tests/system/Images/ImageMagickHandlerTest.php:322
phpvfscomposer:///home/runner/work/CodeIgniter4/CodeIgniter4/vendor/phpunit/phpunit/phpunit:106
```
https://github.com/codeigniter4/CodeIgniter4/actions/runs/4562927692/jobs/8050774291?pr=7392

**Comment by sammyskills** [comment]
Yes, I wonder why it keeps failing here. 🤷🏽‍♂️

File: system/View/Cells/Cell.php [hunk 1]
```diff
@@ -73,8 +73,13 @@ final protected function view(?string $view, array $data = []): string
 
         // If no view is specified, we'll try to guess it based on the class name.
         if (empty($view)) {
-            $view = decamelize((new ReflectionClass($this))->getShortName());
-            $view = str_replace('_cell', '', $view);
+            // According to the docs, the name of the view file should be the
+            // snake_cased version of the cell's class name, but for backward
+            // compactibility, the name also accepts '_cell' being omitted.
```
Comment (kenjis) [inline system/View/Cells/Cell.php:78]:
```suggestion
            // compatibility, the name also accepts '_cell' being omitted.
```

File: system/View/Cells/Cell.php [hunk 2]
```diff
@@ -73,8 +73,13 @@ final protected function view(?string $view, array $data = []): string
...
+            $ref      = new ReflectionClass($this);
+            $view     = decamelize($ref->getShortName());
+            $viewPath = dirname($ref->getFileName()) . DIRECTORY_SEPARATOR . $view . '.php';
+            $view     = file_exists($viewPath) ? $viewPath : str_replace('_cell', '', $view);
```
Comment (kenjis) [inline system/View/Cells/Cell.php:82]: We use `is_file()` to check a file (not directory).
```suggestion
            $view     = is_file($viewPath) ? $viewPath : str_replace('_cell', '', $view);
```

**Comment by kenjis** [comment]
Okay.

```console
$ php spark make:cell MyAwesomeCell

CodeIgniter v4.3.3 Command Line Tool - Server Time: 2023-03-31 08:22:09 UTC+00:00

File created: APPPATH/Cells/MyAwesomeCell.php

File created: APPPATH/Cells/my_awesome_cell.php

$ php spark make:cell MyAwesome

CodeIgniter v4.3.3 Command Line Tool - Server Time: 2023-03-31 08:22:17 UTC+00:00

File created: APPPATH/Cells/MyAwesome.php

File created: APPPATH/Cells/my_awesome.php
```

**Review by kenjis — APPROVED** [review]
LGTM!

**Comment by kenjis** [comment]
@sammyskills Thank you!
