### PR TITLE
fix: Images\Handlers\GDHandler Implicit conversion from float to int loses precision

### LINKED ISSUE #5941: Bug: PHP 8.1 Images\Handlers\GDHandler Implicit conversion from float to int loses precision
See https://forum.codeigniter.com/showthread.php?tid=81803

```
ErrorException

Implicit conversion from float 63.5 to int loses precision [search →](https://www.duckduckgo.com/?q=ErrorException+Implicit+conversion+from+float+63.5+to+int+loses+precision)

SYSTEMPATH/Images/Handlers/GDHandler.php at line 467
```

```php
<?php
namespace App\Controllers;
class Home extends BaseController
{
    public function index()
    {
        \Config\Services::image('gd')
            ->withFile(WRITEPATH . 'img.png')
            ->text('Copyright 2017 My Photo Co', [
                'color'      => '#fff',
                'opacity'    => 0.5,
                'withShadow' => true,
                'hAlign'    => 'center',
                'vAlign'    => 'bottom',
                'fontSize'  => 20
            ])
            ->save(WRITEPATH . 'img2.png');
    }
}
```

### PR DESCRIPTION
**Pull request by kenjis**
**Description**
Fixes #5941

**Checklist:**
- [x] Securely signed commits
- [] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

File: system/Images/Handlers/GDHandler.php [hunk 1]
```diff
@@ -451,7 +451,7 @@ protected function textOverlay(string $text, array $options = [], bool $isShadow
          * Get the rest of the string and split it into 2-length
          * hex values:
          */
-        $opacity = ($options['opacity'] * 127);
+        $opacity = (int) ($options['opacity'] * 127);
```
Comment (paulbalandan) [inline system/Images/Handlers/GDHandler.php:454]: Casting by `(int)` removes the decimals part. https://3v4l.org/8lXKD
Is that the intended behavior or should we use `round()`?

Comment (paulbalandan) [reply system/Images/Handlers/GDHandler.php:454]: Looking at my comment in https://github.com/codeigniter4/CodeIgniter4/pull/5370#issuecomment-976165819, it seems this is to match the current behavior.

Comment (kenjis) [reply system/Images/Handlers/GDHandler.php:454]: Frankly, I don't think there is much difference either way.
And yes, this is to match the current behavior.

**Review by paulbalandan — APPROVED** [review]
