### PR TITLE
fix: Logger - allow variable {line} to be used without variable {file} when logging message

### LINKED ISSUE #9501: Bug: Logger variable {line} cannot be use without variable {file}
### PHP Version

8.3

### CodeIgniter4 Version

4.6.0

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

cli

### Database

_No response_

### What happened?

The first line prints with the placeholder instead of value.

### Steps to Reproduce

log_message("debug", "Model User :{line}");
log_message("debug", "{file}:{line}");

### Expected Output

DEBUG - 2025-04-02 09:33:17 --> Model User :557 
DEBUG - 2025-04-02 09:33:17 --> APPPATH\Models\UserModel.php:557

### Anything else?

[Caused by this line](https://github.com/codeigniter4/CodeIgniter4/blob/c377646e8cb42d80e59d17b19b4155c476442879/system/Log/Logger.php#L344)

### PR DESCRIPTION
**Pull request by michalsn**
**Description**
This PR fixes a bug where the `{line}` variable in the Logger cannot be used without specifying the `{file}` variable in the logged message.

Fixes #9501

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPDoc blocks, only if necessary or adds value
- [x] Unit testing, with >80% coverage
- [ ] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

File: tests/system/Log/LoggerTest.php [hunk 1]
```diff
@@ -236,6 +236,23 @@ public function testLogInterpolatesFileAndLine(): void
...
+
+        $_ENV['foo'] = 'bar';
+
+        $logger->log('debug', 'Test message Sample {line}');
+        $line     = __LINE__ - 1;
+        $expected = "Sample {$line}";
+
+        $logs = TestHandler::getLogs();
+
+        $this->assertGreaterThan(1, strpos($logs[0], $expected));
```
Comment (neznaika0) [inline tests/system/Log/LoggerTest.php:253]: No?
```suggestion
        $this->assertTrue(str_contains($logs[0], $expected));
```

**Review by neznaika0 — CHANGES_REQUESTED** [review]

File: tests/system/Log/LoggerTest.php (hunk 1 above)
Comment (michalsn) [reply tests/system/Log/LoggerTest.php:253]: Yes, we can also write it this way, but I wanted to use the same style as in the previous test. This will ensure that the correct text is added to the log message. The logged message should not start with the `$expected` string.
