### PR TITLE
fix: directory_mirror() throws an error if destination directory exists

### LINKED ISSUE #5478: Bug: Helper function directory_mirror() throws an error if destination directory exists (with overwrite option true)
### PHP Version

8.0

### CodeIgniter4 Version

4.1.5

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

macOS

### Which server did you use?

apache

### Database

MySql 5.6

### What happened?

Helper function directory_mirror() throws an error if destination directory exists (with overwrite option true), because there is no check whether directory already exists (filesystem_helper.php line 94).
I think this should be changed because the name of the function (* mirror *) suggests a function including subdirectories.

### Steps to Reproduce

Just call twice directory_mirror() with same source (including subdirectories) and target path with overwrite option true.

### Expected Output

Create sub directory only if subdirectory in target does not exist. 
Consequently the name (* mirror *) perhaps suggests that you could mirror an path with all elements (including deleting no longer existing elements in destination)

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by kenjis**
**Description**
Fixes #5478
- do nothing if destination directory exists
  - I don't see the reason to raise error when destination directory exists
 
**Checklist:**
- [x] Securely signed commits
- [x] Component(s) with PHPDoc blocks, only if necessary or adds value
- [x] Unit testing, with >80% coverage
- [] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Review by dmillard70 — APPROVED** [review]
Perfect. It works.

**Review by MGatner — APPROVED** [review]
Nice fix @kenjis

File: system/Helpers/filesystem_helper.php [hunk 1]
```diff
@@ -91,7 +91,9 @@ function directory_mirror(string $originDir, string $targetDir, bool $overwrite
             $target = $targetDir . substr($origin, $dirLen);
 
             if ($file->isDir()) {
-                mkdir($target, 0755);
+                if (! is_dir($target)) {
```
Comment (paulbalandan) [inline system/Helpers/filesystem_helper.php:94]: Can you make this not nested if? I mean you can combine this with the outer `if` by a `&&`

Comment (kenjis) [reply system/Helpers/filesystem_helper.php:94]:
```diff
--- a/system/Helpers/filesystem_helper.php
+++ b/system/Helpers/filesystem_helper.php
@@ -90,10 +90,8 @@ if (! function_exists('directory_mirror')) {
             $origin = $file->getPathname();
             $target = $targetDir . substr($origin, $dirLen);
 
-            if ($file->isDir()) {
-                if (! is_dir($target)) {
-                    mkdir($target, 0755);
-                }
+            if ($file->isDir() && ! is_dir($target)) {
+                mkdir($target, 0755);
             } elseif (! is_file($target) || ($overwrite && is_file($target))) {
                 copy($origin, $target);
             }
```
```sh-session
$ ./phpunit tests/system/Helpers/FilesystemHelperTest.php
PHPUnit 9.5.10 by Sebastian Bergmann and contributors.

Runtime:       PHP 8.0.14
Configuration: /Users/kenji/work/codeigniter/CodeIgniter4/phpunit.xml

.......E.............................                             37 / 37 (100%)

Time: 00:00.256, Memory: 12.00 MB

There was 1 error:

1) CodeIgniter\Helpers\FilesystemHelperTest::testDirectoryMirrorSkipExistingFolder
ErrorException: copy(): The first argument to copy() function cannot be a directory

/Users/kenji/work/codeigniter/CodeIgniter4/system/Helpers/filesystem_helper.php:96
/Users/kenji/work/codeigniter/CodeIgniter4/tests/system/Helpers/FilesystemHelperTest.php:181

ERRORS!
Tests: 37, Assertions: 87, Errors: 1.
```

Comment (kenjis) [reply system/Helpers/filesystem_helper.php:94]: @paulbalandan If you want to remove if in if, this is the code.
But I'm not sure it is correct.

```diff
--- a/system/Helpers/filesystem_helper.php
+++ b/system/Helpers/filesystem_helper.php
@@ -90,10 +90,12 @@ if (! function_exists('directory_mirror')) {
             $origin = $file->getPathname();
             $target = $targetDir . substr($origin, $dirLen);
 
-            if ($file->isDir()) {
-                if (! is_dir($target)) {
-                    mkdir($target, 0755);
-                }
+            if ($file->isDir() && ! is_dir($target)) {
+                mkdir($target, 0755);
+            } elseif ($file->isDir() && is_dir($target)) {
+                continue;
+            } elseif (is_dir($target)) {
+                continue;
             } elseif (! is_file($target) || ($overwrite && is_file($target))) {
                 copy($origin, $target);
             }
```

Comment (paulbalandan) [reply system/Helpers/filesystem_helper.php:94]: How about this:
```diff
diff --git a/system/Helpers/filesystem_helper.php b/system/Helpers/filesystem_helper.php
index 89d4d507f..104b739a3 100644
--- a/system/Helpers/filesystem_helper.php
+++ b/system/Helpers/filesystem_helper.php
@@ -90,11 +90,11 @@ if (! function_exists('directory_mirror')) {
             $origin = $file->getPathname();
             $target = $targetDir . substr($origin, $dirLen);

-            if ($file->isDir()) {
-                if (! is_dir($target)) {
-                    mkdir($target, 0755);
-                }
-            } elseif (! is_file($target) || ($overwrite && is_file($target))) {
+            if ($file->isDir() && ! is_dir($target)) {
+                mkdir($target, 0755);
+            }
+
+            if ($file->isFile() && (! is_file($target) || $overwrite)) {
                 copy($origin, $target);
             }
         }
```

Comment (kenjis) [reply system/Helpers/filesystem_helper.php:94]: Changing the conditions of the if statements does not seem to make it easier to understand.
