### PR TITLE
fix: case-insensitivity in the `like()` method when in use with accented characters

### LINKED ISSUE #9236: Bug: insensitive like query failing with multibyte characters
### PHP Version

7.4

### CodeIgniter4 Version

4.4.8

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

cli

### Database

Postgres 16

### What happened?

strtolower() in BaseBuilder.php on line 1135 will ignore the multibyte characters (according to PHP8 docs) or in experience on 7.4 will mangle them into diamonds (�).

### Steps to Reproduce

`$query->like('name', 'Š', 'both', null, true)->find();`

### Expected Output
all rows where name contains `š`

### Actual Output
ErrorException: pg_query(): Query failed: ERROR:  invalid byte sequence for encoding &quot;UTF8&quot;: 0xe5 0xa1 0x27 in C:\....

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by michalsn**
**Description**
This PR fixes the case insensitivity option in the `like()` method when we deal with accented characters.

Closes #9236

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPDoc blocks, only if necessary or adds value
- [x] Unit testing, with >80% coverage
- [ ] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

File: system/Database/BaseBuilder.php [hunk 1]
```diff
@@ -1151,7 +1151,7 @@ protected function _like($field, string $match = '', string $type = 'AND ', stri
 
         foreach ($keyValue as $k => $v) {
             if ($insensitiveSearch === true) {
-                $v = strtolower($v);
+                $v = mb_strtolower($v);
```
Comment (datamweb) [inline system/Database/BaseBuilder.php:1154]:
```suggestion
                $v = mb_strtolower($v, 'UTF-8');
```
It seems better to include the second parameter ('UTF-8') in `mb_strtolower` to ensure proper handling of multibyte characters.

File: tests/_support/Database/Seeds/CITestSeeder.php [hunk 2]
```diff
@@ -86,6 +86,10 @@ public function run(): void
                     'key'   => 'key',
                     'value' => 'value',
                 ],
+                [
+                    'key'   => 'accented characters',
+                    'value' => 'śćźżłąęó',
```
Comment (datamweb) [inline tests/_support/Database/Seeds/CITestSeeder.php:91]: Could you also please add a test case for Farsi characters to verify the correct behavior? (e.g. 'خٌوب')

File: system/Database/BaseBuilder.php (hunk 1 above)
Comment (michalsn) [reply system/Database/BaseBuilder.php:1154]: Good point.

File: tests/_support/Database/Seeds/CITestSeeder.php (hunk 2 above)
Comment (michalsn) [reply tests/_support/Database/Seeds/CITestSeeder.php:91]: Will do.

**Review by datamweb — APPROVED** [review]
LGTM!
@michalsn Thanks.

**Review by ddevsr — CHANGES_REQUESTED** [review]
Add more case test

1. Bengali (https://github.com/codeigniter4/translations/blob/develop/Language/bn/Cast.php)
2. Korean (https://github.com/codeigniter4/translations/blob/develop/Language/ko/Cast.php)
3. Malayam  (https://github.com/codeigniter4/translations/blob/develop/Language/ml/Cast.php)

File: tests/system/Database/Live/LikeTest.php [hunk 3]
```diff
@@ -79,6 +79,12 @@ public function testLikeCaseInsensitive(): void
     #[DataProvider('provideMultibyteCharacters')]
     public function testLikeCaseInsensitiveWithMultibyteCharacter(string $match, string $result): void
     {
+        if ($this->db->DBDriver === 'SQLSRV') {
+            $this->markTestSkipped(
+                'Currently Builder class does not fully support Unicode strings in SQLSRV.'
```
[the remark this answers is not in the document]
Comment (michalsn) [reply tests/system/Database/Live/LikeTest.php]: I was going to post the details as a bug report, but I gave it another try after your comment.

You are right. When I was checking this, I set collation only for the `value` field. Apparently, we have to set it for the entire database to work properly. Because of this, I was only able to add Unicode string using `N` prefix.

Thank you!

**Comment by samsonasik** [comment]
@michalsn rebase is needed

**Comment by michalsn** [comment]
@samsonasik Thanks, done.

**Review by samsonasik — APPROVED** [review]

**Review by datamweb — APPROVED** [review]

File: tests/system/Database/Live/LikeTest.php (hunk 3 above)
[the remark this answers is not in the document]
Comment (datamweb) [reply tests/system/Database/Live/LikeTest.php]: Thanks for the explanation.

**Review by ddevsr — APPROVED** [review]
