### PR TITLE
fix: upsert with composite unique index

### LINKED ISSUE #9450: Bug: Issue with Composite Primary Keys in _upsertBatch for PostgreSQL – Only the First Index Field Is Considered
### PHP Version

8.4

### CodeIgniter4 Version

4.6.0

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

macOS

### Which server did you use?

apache

### Database

PostgreSQL 17.2

### What happened?

Hello,

I'm reporting a potential bug in CodeIgniter 4 related to the _upsertBatch function when used with PostgreSQL. It appears that the function only considers the first field of an index for conflict resolution, which causes issues when dealing with composite primary keys or tables with multiple unique indexes.

### **Details:**
In the _upsertBatch function, the following code snippet suggests that only one index (and, in practice, only the first field of that index) is used:

```
foreach (array_map(static fn($index) => $index->fields, $allIndexes) as $index) {
    $constraints[] = current($index);
    // only one index can be used?
    break;
}
```
Because of this, if a table has a composite primary key (or multiple unique constraints), the generated SQL will include only the first field from the index in the ON CONFLICT clause. This behavior may lead to unexpected failures or incorrect updates during upsert operations.

### Steps to Reproduce

Create a PostgreSQL table with a composite primary key or with multiple unique indexes.
Use the upsertBatch method to insert/update data in this table.
Observe that the conflict resolution logic only uses the first field of the composite key, which can lead to errors or improper upsert behavior.

### Expected Output

All relevant fields of the composite key (or the chosen unique index) should be used in the ON CONFLICT clause to correctly identify conflicts and perform the update action.

### Anything else?

This issue might be related to the comment // only one index can be used? present in the code. It suggests that the current implementation might be a temporary workaround or an oversight that did not fully account for composite keys.

### PR DESCRIPTION
**Pull request by michalsn**
**Description**
This PR fixes a bug in `Postgre` and `SQLite3` where composite indexes are not fully taken into account when using `upsert()`. 

Both handlers:
* requires specifying all columns in the composite unique constraint
* and cannot mix columns from multiple unique constraints

Fixes #9450

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPDoc blocks, only if necessary or adds value
- [x] Unit testing, with >80% coverage
- [ ] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

File: system/Database/Postgre/Builder.php [hunk 1]
```diff
@@ -469,9 +469,8 @@ protected function _upsertBatch(string $table, array $keys, array $values): stri
                     return ($index->type === 'UNIQUE' || $index->type === 'PRIMARY') && $hasAllFields;
                 });
 
-                foreach (array_map(static fn ($index) => $index->fields, $allIndexes) as $index) {
-                    $constraints[] = current($index);
-                    // only one index can be used?
+                foreach ($allIndexes as $index) {
+                    $constraints = $index->fields;
```
Comment (paulbalandan) [inline system/Database/Postgre/Builder.php:473]: Would $constraints be just overwritten on iterations > 1?

Comment (michalsn) [reply system/Database/Postgre/Builder.php:473]: No, we break the loop after the first item.

**Comment by sclubricants** [comment]
Posgre has very different functioning then MySQL when it comes to upserts. Postgre offers much more features while mysql automatically applies any and all constraints. It was attempted apply the primary key if constraints were not set. Its really just a guess but it was done to try and provide the same functionality across all databases. For all the DBMS except mysql it is really recommended to use the onConstraint() method and explicitly define them. Perhaps the documentation should highlight this.

**Comment by michalsn** [comment]
While I agree that `onConstraint()` should be used when dealing with multiple keys, in cases where we have one composite key, it should be automatically applied as a whole and not partially.

**Review by paulbalandan — APPROVED** [review]

**Review by samsonasik — APPROVED** [review]
