### PR TITLE
fix: [Postgre] QueryBuilder::updateBatch() does not work (No API change)

### LINKED ISSUE #7387: Bug: [Postgres] `QueryBuilder::updateBatch()` pg_affected_rows(): Argument #1 ($result) must be of type PgSql\Result, bool given
### PHP Version

8.1

### CodeIgniter4 Version

4.3.3

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### Database

PostgeSQL 15

### What happened?

Error after run $this->modelName->updateBatch($updatedData, 'id');

```json
{
    "title": "TypeError",
    "type": "TypeError",
    "code": 500,
    "message": "pg_affected_rows(): Argument #1 ($result) must be of type PgSql\\Result, bool given",
    "file": "D:\\onero\\onero-crm-ci4-api\\vendor\\codeigniter4\\framework\\system\\Database\\Postgre\\Connection.php",
    "line": 172,
    "trace": [
        {
            "file": "D:\\onero\\onero-crm-ci4-api\\vendor\\codeigniter4\\framework\\system\\Database\\Postgre\\Connection.php",
            "line": 172,
            "function": "pg_affected_rows",
            "args": [
                false
            ]
        },
        {
            "file": "D:\\onero\\onero-crm-ci4-api\\vendor\\codeigniter4\\framework\\system\\Database\\BaseBuilder.php",
            "line": 1802,
            "function": "affectedRows",
            "class": "CodeIgniter\\Database\\Postgre\\Connection",
            "type": "->",
            "args": []
        },
        {
            "file": "D:\\onero\\onero-crm-ci4-api\\vendor\\codeigniter4\\framework\\system\\Database\\BaseBuilder.php",
            "line": 2562,
            "function": "batchExecute",
            "class": "CodeIgniter\\Database\\BaseBuilder",
            "type": "->",
            "args": [
                "_updateBatch",
                100
            ]
        },
        {
            "file": "D:\\onero\\onero-crm-ci4-api\\vendor\\codeigniter4\\framework\\system\\Model.php",
            "line": 414,
            "function": "updateBatch",
            "class": "CodeIgniter\\Database\\BaseBuilder",
            "type": "->",
            "args": [
                [
                    {
                        "package_plan_id": "PP63aa9a4a1f221",
                        "package_plan_name": "Basic",
                        "package_plan_description": "The ideal solution for small businesses with an affordable price, easy to use, even for beginners.",
                        "updated_at": "2023-03-27 05:08:21"
                    },
                    {
                        "package_plan_id": "PP63aa9a4a1f252",
                        "package_plan_name": "Business",
                        "package_plan_description": "The perfect package for mid-size companies, various additional features to market, sell & support your business.",
                        "updated_at": "2023-03-27 05:08:21"
                    },
                    {
                        "package_plan_id": "PP63aa9a4a1f26d",
                        "package_plan_name": "Professional",
                        "package_plan_description": "Complete features for complex needs, bring value to customers and create the best user experience.",
                        "updated_at": "2023-03-27 05:08:21"
                    }
                ],
                "package_plan_id",
                100
            ]
        },
```

### Steps to Reproduce

Run updateBatch method
$this->modelName->updateBatch($updatedData, 'id');

### Expected Output

No error.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by kenjis**
**Description**
Supersedes #8426
Fixes #7387
See https://forum.codeigniter.com/showthread.php?tid=88871

```php
$data = [
    [
        'type_text'     => 'updated',
        'type_bigint'   => 9_999_999,
        'type_date'     => '2023-12-01', // Key
        'type_datetime' => '2024-01-01 09:00:00',
    ],
    [
        'type_text'     => 'updated',
        'type_bigint'   => 9_999_999,
        'type_date'     => '2023-12-02', // Key
        'type_datetime' => '2024-01-01 09:00:00',
    ],
];
$this->db->table($table)->updateBatch($data, 'type_date');
```
```sql
UPDATE "db_type_test"
SET
"type_bigint" = CAST(_u."type_bigint" AS BIGINT),
"type_datetime" = CAST(_u."type_datetime" AS TIMESTAMP WITHOUT TIME ZONE),
"type_text" = CAST(_u."type_text" AS TEXT)
FROM (
SELECT 9999999 "type_bigint", '2023-12-01' "type_date", '2024-01-01 09:00:00' "type_datetime", 'updated' "type_text" UNION ALL
SELECT 9999999 "type_bigint", '2023-12-02' "type_date", '2024-01-01 09:00:00' "type_datetime", 'updated' "type_text"
) _u
WHERE "db_type_test"."type_date" = CAST(_u."type_date" AS DATE)
```

References:
- https://www.postgresqltutorial.com/postgresql-tutorial/postgresql-cast/
- https://docs.oracle.com/javadb/10.8.3.0/ref/rrefsqlj33562.html
- https://dev.mysql.com/doc/refman/8.0/en/cast-functions.html#function_cast
- https://learn.microsoft.com/en-us/sql/t-sql/functions/cast-and-convert-transact-sql?view=sql-server-ver16
- https://www.sqlite.org/lang_expr.html#castexpr

**Checklist:**
- [x] Securely signed commits
- [x] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [x] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Comment by kenjis** [comment]
```
Starting mssql service container
  /usr/bin/docker pull mcr.microsoft.com/mssql/server:2022-latest
  Error response from daemon: received unexpected HTTP status: 503 Service Unavailable
  Warning: Docker pull failed with exit code 1, back off 8.668 seconds before retry.
  /usr/bin/docker pull mcr.microsoft.com/mssql/server:2022-latest
  Error response from daemon: received unexpected HTTP status: 503 Service Unavailable
  Warning: Docker pull failed with exit code 1, back off 4.351 seconds before retry.
  /usr/bin/docker pull mcr.microsoft.com/mssql/server:2022-latest
  Error response from daemon: Head "https://mcr.microsoft.com/v2/mssql/server/manifests/2022-latest": no basic auth credentials
  Error: Docker pull failed with exit code 1
```
https://github.com/codeigniter4/CodeIgniter4/actions/runs/7598402465/job/20694371974?pr=8439

**Comment by kenjis** [comment]
SQLSRV

```
There was 1 error:

1) CodeIgniter\Database\Live\UpdateTest::testUpdateBatch
CodeIgniter\Database\Exceptions\DatabaseException: [Microsoft][ODBC Driver 17 for SQL Server][SQL Server]The data types text and varchar are incompatible in the equal to operator.

/home/runner/work/CodeIgniter4/CodeIgniter4/system/Database/BaseConnection.php:647
/home/runner/work/CodeIgniter4/CodeIgniter4/system/Database/BaseBuilder.php:1697
/home/runner/work/CodeIgniter4/CodeIgniter4/system/Test/Constraints/SeeInDatabase.php:55
/home/runner/work/CodeIgniter4/CodeIgniter4/system/Test/DatabaseTestTrait.php:280
/home/runner/work/CodeIgniter4/CodeIgniter4/tests/system/Database/Live/UpdateTest.php:156
phpvfscomposer:///home/runner/work/CodeIgniter4/CodeIgniter4/vendor/phpunit/phpunit/phpunit:106
```
https://github.com/codeigniter4/CodeIgniter4/actions/runs/7598402465/job/20695798884?pr=8439

It seems we cannot compare `text` and `varchar` with `=` .
```sql
SELECT COUNT(*) AS "numrows"
FROM "test"."dbo"."db_type_test"
WHERE "type_varchar" = 'test1'
AND "type_text" = 'updated'
AND "type_bigint" = 9999999
AND "type_date" = '2024-01-01'
AND "type_datetime" = '2024-01-01 09:00:00'
```

**Comment by kenjis** [comment]
```
There was 1 error:

1) CodeIgniter\Database\Live\UpdateTest::testUpdateBatch
CodeIgniter\Database\Exceptions\DatabaseException: oci_execute(): ORA-01400: cannot insert NULL into ("ORACLE"."db_type_test"."type_boolean")

/home/runner/work/CodeIgniter4/CodeIgniter4/system/Database/BaseConnection.php:647
/home/runner/work/CodeIgniter4/CodeIgniter4/system/Database/BaseBuilder.php:2302
/home/runner/work/CodeIgniter4/CodeIgniter4/tests/system/Database/Live/UpdateTest.php:133
phpvfscomposer:///home/runner/work/CodeIgniter4/CodeIgniter4/vendor/phpunit/phpunit/phpunit:106
```
https://github.com/codeigniter4/CodeIgniter4/actions/runs/7598402465/job/20695798698

**Comment by sclubricants** [comment]
Might run into problems in the where part as well

WHERE "db_type_test"."type_varchar" = _u."type_varchar"

It probably works here because its text to varchar. 

We could cast everything in the select part but it adds a lot of redundancy. 

Maybe try the query where the constraint is timestamp and see what it does.

**Comment by sclubricants** [comment]
Looks like we should take a look at sqsrv->forge->_attributeType(array &$attributes)

Maybe text should be mapped to nvarchar(max) and enum as well.

This could be problematic changing these though I suppose.

**Comment by kenjis** [comment]
> Might run into problems in the where part as well
> WHERE "db_type_test"."type_varchar" = _u."type_varchar"

Yes, fixed in https://github.com/codeigniter4/CodeIgniter4/pull/8439/commits/c4ecd69c5f78f3665377f3b8444d296eb62a3b37

**Comment by sclubricants** [comment]
Maybe uppercase ::text to ::TEXT. This is part of SQL and might be easier to read.

**Comment by kenjis** [comment]
> We could cast everything in the select part but it adds a lot of redundancy.
> Maybe try the query where the constraint is timestamp and see what it does.

I'm not sure what types are safe to remove.

If we remove `::bigint`, the following query fails:

```sql
UPDATE "db_type_test"
SET
"type_bigint" = _u."type_bigint",
"type_integer" = _u."type_integer"
FROM (
SELECT '2448114396435166946' "type_bigint", '9999999' "type_integer", 'test1' "type_varchar" UNION ALL
SELECT '2448114396435166946' "type_bigint", '9999999' "type_integer", 'test2' "type_varchar"
) _u
WHERE "db_type_test"."type_varchar" = _u."type_varchar"
```
```
ErrorException: pg_query(): Query failed: ERROR:  column "type_bigint" is of type bigint but expression is of type text
LINE 3: "type_bigint" = _u."type_bigint",
                        ^
HINT:  You will need to rewrite or cast the expression. 
```

In this case, the value `'2448114396435166946'` is wrong, but this may happen, because all data returned by PosrgreSQL are PHP strings.
https://forum.codeigniter.com/showthread.php?tid=88871&pid=414027#pid414027

File: tests/_support/Database/Migrations/20160428212500_Create_test_tables.php [hunk 1]
```diff
@@ -47,16 +47,22 @@ public function up(): void
...
+            'type_varchar' => ['type' => 'VARCHAR', 'constraint' => 40, 'null' => true],
+            'type_char'    => ['type' => 'CHAR', 'constraint' => 10, 'null' => true],
+            // TEXT should not be used on SQLSRV. It is deprecated.
+            'type_text'     => ['type' => 'TEXT', 'null' => true],
+            'type_smallint' => ['type' => 'SMALLINT', 'null' => true],
+            'type_integer'  => ['type' => 'INTEGER', 'null' => true],
+            // FLOAT should not be used on MySQL.
+            //   CREATE TABLE t (f FLOAT, d DOUBLE);
+            //   INSERT INTO t VALUES(99.9, 99.9);
+            //   SELECT * FROM t WHERE f=99.9; // Empty set
```
Comment (sclubricants) [inline tests/_support/Database/Migrations/20160428212500_Create_test_tables.php:64]: Float is an approximation of a number. The following would work:
```SQL
SELECT * FROM t WHERE f > 99.89 AND f < 99.91;
```

File: system/Database/Postgre/Builder.php [hunk 2]
```diff
@@ -312,6 +313,138 @@ public function join(string $table, $cond, string $type = '', ?bool $escape = nu
...
+            $that = $this;
+            $sql .= implode(
+                ",\n",
+                array_map(
+                    static function ($key, $value) use ($alias, $that) {
+                        $fieldName = trim($key, '"');
+
+                        return $key . ($value instanceof RawSql ?
+                                ' = ' . $value :
+                                ' = ' . $alias . '.' . $that->castValue($fieldName, $value));
```
Comment (sclubricants) [inline system/Database/Postgre/Builder.php:362]:
```suggestion
                                ' = ' . $alias . '.' . $this->castValue($fieldName, $value));
```

File: system/Database/Postgre/Builder.php [hunk 3]
```diff
@@ -312,6 +313,138 @@ public function join(string $table, $cond, string $type = '', ?bool $escape = nu
...
+
+    /**
+     * Returns cast value.
+     *
+     * @param float|int|string $value Escaped value
+     */
+    private function castValue(string $fieldName, $value): string
+    {
+        if (! isset($this->QBOptions['fieldTypes'])) {
+            throw new LogicException(
```
Comment (sclubricants) [inline system/Database/Postgre/Builder.php:424]: I'm not sure I like throwing an exception here. I think rather than an exception if fieldTypes aren't defined then getFieldTypes() should be called. This would require the additional parameter $table though. The way it is the method is dependent on another method being called to get some data. If you don't want to add $table as another parameter then you could add $fieldTypes. 

You also would need to pass $value to the method as you could simply append ::TEXT or empty string.

```php
$value . $that->addType($fieldName, $fieldTypes);
```

Comment (sclubricants) [reply system/Database/Postgre/Builder.php:424]: On second thought might should include value because with other DBMS as well as Postgre the format is: 

`CAST ('100' AS INTEGER)`

So: 
```php
$that->castValue($table, $fieldName, $value);
```

Comment (sclubricants) [reply system/Database/Postgre/Builder.php:424]:
```php
    private function castValue(string $table, string $fieldName, $value): string
    {
        if (! isset($this->QBOptions['fieldTypes'])) {
            $this->QBOptions['fieldTypes'] = $this->getFieldTypes($table);
        }

        $type = $this->QBOptions['fieldTypes'][$fieldName] ?? null;

        return ($type === null) ? $value : $value . '::' . strtoupper($type);
        // return ($type === null) ? $value : 'CAST(' . $value . ' AS ' . strtoupper($type) . ')';
    }
```

Comment (sclubricants) [reply system/Database/Postgre/Builder.php:424]:
```php
$that->castValue($table, $fieldName, '2024-01-01'); // CAST('2024-01-01' AS DATE)

$that->castValue($table, $fieldName, $alias . $fieldName); // CAST(_u.created_date AS DATE)
```

Comment (sclubricants) [reply system/Database/Postgre/Builder.php:424]: You could still use the ::DATE style but in case this was ever implemented with other DBMS then it would work with this format.

Comment (sclubricants) [reply system/Database/Postgre/Builder.php:424]: call it expression:
```php
$that->castValue($table, $fieldName, $expression);
```

Comment (sclubricants) [reply system/Database/Postgre/Builder.php:424]:
```php
$that->cast($type, $expression);

$that->cast($that->getType($table, $fieldName), $expression);

```

File: tests/_support/Database/Migrations/20160428212500_Create_test_tables.php (hunk 1 above)
Comment (kenjis) [reply tests/_support/Database/Migrations/20160428212500_Create_test_tables.php:64]: Yes, and we cannot use `seeInDatabase()`.

File: system/Database/Postgre/Builder.php (hunk 3 above)
Comment (kenjis) [reply system/Database/Postgre/Builder.php]: Changed. https://github.com/codeigniter4/CodeIgniter4/pull/8439/commits/6d4ce25435ef1aae1c3c9bfeaf23ec5399bc77c0

Comment (sclubricants) [reply system/Database/Postgre/Builder.php]: I made some updates to last post.. see what ya think

Comment (kenjis) [reply system/Database/Postgre/Builder.php]: `cast($expression, $type)` makes sense. But we can't add API in a patch version.

Changed. 92cc84e1ff1ac91c596bed6d511633cc70c5457b

**Comment by kenjis** [comment]
@codeigniter4/database-team Review, please.

**Review by michalsn — APPROVED** [review]
Looks great - thank you @kenjis and @sclubricants!

File: system/Database/Postgre/Builder.php [hunk 4]
```diff
@@ -312,6 +312,131 @@ public function join(string $table, $cond, string $type = '', ?bool $escape = nu
...
+
+            $sql .= "SET\n";
+
+            $that = $this;
+            $sql .= implode(
+                ",\n",
+                array_map(
+                    static fn ($key, $value) => $key . ($value instanceof RawSql ?
+                            ' = ' . $value :
+                            ' = ' . $alias . '.' . $that->cast($value, $that->getFieldType($table, $key))),
```
Comment (sclubricants) [inline system/Database/Postgre/Builder.php:356]:
```suggestion
                            ' = ' . $that->cast($alias . '.' . $value, $that->getFieldType($table, $key))),
```

$alias . '.' . $value is the full part of the expression. I would like to see us use the more universal format of CAST(expression AS type). If we use this then you definitely have to include the alias as part of expression. The expression here is  "table"."column"

File: system/Database/Postgre/Builder.php [hunk 5]
```diff
@@ -312,6 +312,131 @@ public function join(string $table, $cond, string $type = '', ?bool $escape = nu
...
+                    static function ($key, $value) use ($table, $alias, $that) {
+                        if ($value instanceof RawSql && is_string($key)) {
+                            return $table . '.' . $key . ' = ' . $value;
+                        }
+
+                        if ($value instanceof RawSql) {
+                            return $value;
+                        }
+
+                        return $table . '.' . $value . ' = ' . $alias . '.' . $that->cast($value, $that->getFieldType($table, $value));
```
Comment (sclubricants) [inline system/Database/Postgre/Builder.php:378]:
```suggestion
                        return $table . '.' . $value . ' = ' . $that->cast($alias . '.' . $value, $that->getFieldType($table, $value));
```

File: system/Database/Postgre/Builder.php [hunk 6]
```diff
@@ -312,6 +312,131 @@ public function join(string $table, $cond, string $type = '', ?bool $escape = nu
...
+    /**
+     * Returns cast expression.
+     *
+     * @TODO move this to BaseBuilder in 4.5.0
+     *
+     * @param float|int|string $expression
+     */
+    private function cast($expression, ?string $type): string
+    {
+        return ($type === null) ? $expression : $expression . '::' . strtoupper($type);
```
Comment (sclubricants) [inline system/Database/Postgre/Builder.php:416]:
```suggestion
        return ($type === null) ? $expression : 'CAST(' . $expression . ' AS ' . strtoupper($type) . ')';
```
The `expression::TYPE` format is a shorthand format postgre supports. However Postgre and all other DBMS support the format `CAST(expression AS type)`. We should go ahead and use this format so that if this method is moved to BaseBuilder it will generate code compatible with all DBMS.

https://www.postgresqltutorial.com/postgresql-tutorial/postgresql-cast/
https://docs.oracle.com/javadb/10.8.3.0/ref/rrefsqlj33562.html
https://dev.mysql.com/doc/refman/8.0/en/cast-functions.html#function_cast
https://learn.microsoft.com/en-us/sql/t-sql/functions/cast-and-convert-transact-sql?view=sql-server-ver16
https://www.sqlite.org/lang_expr.html#castexpr

File: system/Database/Postgre/Builder.php (hunk 4 above)
Comment (kenjis) [reply system/Database/Postgre/Builder.php]: Done.

File: system/Database/Postgre/Builder.php (hunk 5 above)
Comment (kenjis) [reply system/Database/Postgre/Builder.php]: Done.

File: system/Database/Postgre/Builder.php (hunk 6 above)
Comment (kenjis) [reply system/Database/Postgre/Builder.php]: Done.

**Comment by sclubricants** [comment]
This looks good to me.

We should probably check upsertBatch() and deleteBatch() as well. I think insertBatch() should be ok.

**Review by sclubricants — APPROVED** [review]

**Comment by kenjis** [comment]
Thank you! @sclubricants @michalsn

**Comment by kenjis** [comment]
@sclubricants 
> We should probably check upsertBatch() and deleteBatch() as well. I think insertBatch() should be ok.

See 
- #8450
- #8451
- #8453
