### PR TITLE
fix: `Time::humanize()` causes error with ar locale

### LINKED ISSUE #4708: Bug: Time::humanize() does not work with ar locale
I set arabic language in app config file for defualtLocale like this:

`public $defaultLocale = 'ar';`

Now, I work with `humanize` time function like this:

```
$time = CodeIgniter\I18n\Time::parse($date, 'America/Chicago');
return $time->humanize(); 
```

Now in action I get this error:

```

DateTime::__construct(): Failed to parse time string (٢٠٢١-٠٥-١٩ ٠١:٤٧:٢٨) at position 0 (�): Unexpected character

SYSTEMPATH\I18n\Time.php at line 1150

public function humanize()
1149     {
1150         $now  = IntlCalendar::fromDateTime(Time::now($this->timezone)->toDateTimeString());

```

I think the `DateTime` function have problem with arabic number. because when I set `en` for default locale, `humanize function` work truly. 

@lonnieezell @MGatner

### PR DESCRIPTION
**Pull request by kenjis**
Need to rebase after merging #6116

**Description**
Fixes #4708
Related #6116

**Checklist:**
- [x] Securely signed commits
- [] Component(s) with PHPDoc blocks, only if necessary or adds value
- [x] Unit testing, with >80% coverage
- [] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

File: tests/system/I18n/TimeTest.php [hunk 1]
```diff
@@ -1025,6 +1027,31 @@ public function testHumanizeNow()
...
+        $config->supportedLocales = ['ar'];
+        $config->defaultLocale    = 'ar';
+        Factories::injectMock('config', 'App', $config);
+
+        Time::setTestNow('2022-06-14 12:00', 'America/Chicago');
+
+        $date = '2022-06-07 12:00';
+        $time = Time::parse($date, 'America/Chicago');
+
+        $this->assertSame('١ week ago', $time->humanize());
```
Comment (kenjis) [inline tests/system/I18n/TimeTest.php:1050]: I don't know `١` is correct or not.

Comment (datamweb) [reply tests/system/I18n/TimeTest.php:1050]: Numbers are similar in Arabic and Persian **(١ farsi = ١ arabic)**.

Comment (kenjis) [reply tests/system/I18n/TimeTest.php:1050]: https://www.saitak.com/Number/
Okay, I got `1` is `۱`.

**Comment by datamweb** [comment]
@kenjis also had this problem for the Persian language(fa).
The problem is **now solved** (after [15cd4ca](https://github.com/codeigniter4/CodeIgniter4/pull/6120/commits/15cd4ca05020b1aa25090ff4186aa6fa97ccc0a1),)
The output is as expected.
```php
$time = Time::parse('March 9, 2016 12:00:00', 'Asia/Tehran');
dd ($time->humanize());
```
`$time->humanize() UTF-8 string (16) "۶ سال پیش"`

**Thanks**

File: tests/system/I18n/TimeTest.php (hunk 1 above)
Comment (MGatner) [reply tests/system/I18n/TimeTest.php:1050]: It's the same in Hebrew, we use characters for numbers: `א` = 1

It would be like `a` = 1

File: system/I18n/Time.php [hunk 2]
```diff
@@ -1005,7 +1005,7 @@ public function isAfter($testTime, ?string $timezone = null): bool
      */
     public function humanize()
     {
-        $now  = IntlCalendar::fromDateTime(self::now($this->timezone)->toDateTimeString());
+        $now  = IntlCalendar::fromDateTime(self::now($this->timezone));
```
Comment (MGatner) [inline system/I18n/Time.php:1008]: That's kind of funny that we were using an unnecessary intermediate string to begin with 😅

**Review by MGatner — APPROVED** [review]
Looks good, don't need to re-review after rebase.
