### PR TITLE
fix: route options are not merged (inner filter overrides outer filter)

### LINKED ISSUE #7963: Bug: route group filter bug
### PHP Version

8.2

### CodeIgniter4 Version

4.4.1

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Windows, Linux

### Which server did you use?

apache

### Database

MySQL 5.6

### What happened?

I was using filters in `Grouping Routes` which was working properly in `nested routes` and `nested grouping routes`. But when I used a namespace in `nested grouping routes` the filter stopped working for `nested grouping routes`.

### Steps to Reproduce

```php
$routes->group('', ['filter' => AuthenticationFilter::class], function ($routes) {
    $routes->get('dashboard', function (){
        echo "AuthenticationFilter is working";
    });
    
    $routes->group('profile', ['namespace' => 'App\Controllers\Profile'], function($routes){
        $routes->get('/', function (){
            echo "AuthenticationFilter is not working";
        });
    });
});
```

### Expected Output

I am expecting the auth filter to be called before the profile request.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by kenjis**
**Description**
Fixes #7963

- merge outer `group()` options with inner `group()` options
- outer group filter option is not merged with inner group filter option. See https://github.com/codeigniter4/CodeIgniter4/pull/7981/files#diff-9e755caf334ca07345b43d4fdc3986ac1f9bb9594c6f78ebdec59bc780699b73R375-R400

**Checklist:**
- [x] Securely signed commits
- [x] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [x] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

File: tests/system/Router/RouteCollectionTest.php [hunk 1]
```diff
@@ -337,6 +337,104 @@ static function ($routes): void {
...
+        );
+
+        $expected = [
+            'admin/dashboard' => [
+                'filter' => ['csrf'],
+            ],
+            'admin/profile' => [
+                'filter' => ['honeypot'],
+            ],
+        ];
```
Comment (michalsn) [inline tests/system/Router/RouteCollectionTest.php:400]: This is still confusing to me but I guess it's because we can have only one filter when `Config\Feature::multipleFilters` is disabled.

Will this gonna end up as:

```php
$expected = [
    'admin/dashboard' => [
        'filter' => ['csrf'],
    ],
    'admin/profile' => [
        'filter' => ['csrf', 'honeypot'],
    ],
];
```
when `multipleFilters` option will be enabled?

**Review by michalsn — COMMENTED** [review]
I'm trying to imagine scenarios in which this could have been intentionally used, and frankly, I can't. But I'm sure there will be devs who take advantage of current behavior.

File: tests/system/Router/RouteCollectionTest.php (hunk 1 above)
Comment (kenjis) [reply tests/system/Router/RouteCollectionTest.php:400]: No. it is just because using `array_merge()`.
https://3v4l.org/tskmm

It is the current behavior that filters are not merged, and also the reason why the Note in the user guide was added.

One possible behavior would be to merge filters as well, but then it would not be possible to delete filters in inner group. Multiple filters are already the default in 4.5.

Comment (michalsn) [reply tests/system/Router/RouteCollectionTest.php:400]: Good point about removing filters. 

I don't know... now I'm leaning towards staying with the current behavior and not inheriting anything. Because the new behavior seems even more confusing - it's inherited only if there are no other filters. I can imagine people adding a new filter over time and "losing" functionality.

Thanks to the current note, at least we have clear rules to follow.

Comment (kenjis) [reply tests/system/Router/RouteCollectionTest.php:400]: The current behavior is not that straightforward either.
The current behavior is that if you don't pass an options array to the inner group, the outer options are inherited.

That's why when you set outer filter and add namespace option to inner group, the filter that set in outer suddenly will be gone for the inner route.

It seems that this issue is not so easy to conclude.

Comment (michalsn) [reply tests/system/Router/RouteCollectionTest.php:400]: Yes, this is a bit more complex than I thought at first. Especially if we add namespaces to it.

Personally, I would probably merge all the declared filters from the external to the internal group using `array_merge_recursive` and introduce something like `filterExclude` to remove the filters if needed. However, this seems a bit too complex... not sure if we want to make such big changes.

 Although the rules would be clear and need no further explanation.

Comment (neznaika0) [reply tests/system/Router/RouteCollectionTest.php:400]: > No. it is just because using `array_merge()`. https://3v4l.org/tskmm
> 
> It is the current behavior that filters are not merged, and also the reason why the Note in the user guide was added.
> 
> One possible behavior would be to merge filters as well, but then it would not be possible to delete filters in inner group. Multiple filters are already the default in 4.5.

https://3v4l.org/2jijf
While we are working with options as an array, why not combine the outer with the inner?

I believe the group should be inheritable internally. Including namespace. To exclude filters, it is possible to create an additional key or, as before, configure it in `Config/Filters`

Comment (MGatner) [reply tests/system/Router/RouteCollectionTest.php:400]: I'm leaning towards "all or none". Either we should completely merge all keys, including filters as @neznaika0 suggests - or we should exclude filters from any inheritance and require them to be redefined in subroutes. I think the former solution is more intuitive but the latter solution is more flexible. 

Given that Filters are a significant nexus for security concerns I think this is important to consider carefully.

Comment (kenjis) [reply tests/system/Router/RouteCollectionTest.php:400]: I also am leaning towards "all or none". 

But if you specify namespaces, merging does not make sense.
See https://3v4l.org/ifMuX
When merging all, namespaces must be overwritten and filters must be merged.

If we go with none, the filter that was previously working, specified only for the outer group, will no longer work on the inner routes.

Comment (neznaika0) [reply tests/system/Router/RouteCollectionTest.php:400]: That's right, namespace needs to be replaced.

Comment (kenjis) [reply tests/system/Router/RouteCollectionTest.php:400]: @neznaika0 `$multipleFilters` was already removed in 4.5. Do you want to revert it?

Comment (kenjis) [reply tests/system/Router/RouteCollectionTest.php:400]: I still go back to the beginning and `array_merge()` seems to be the way to go.
At least the implementation will be the simplest.

**Comment by kenjis** [comment]
Rebased to resolve a conflict.

File: tests/system/Router/RouteCollectionTest.php (hunk 1 above)
Comment (neznaika0) [reply tests/system/Router/RouteCollectionTest.php:400]: > @neznaika0 `$multipleFilters`was already removed in 4.5. Do you want to revert it?

How do we make exceptions when merging filters? Just ignore it? 

For example, we don't need an 'outer_filter' in the group - `['auth', 'outer_filter'] >> ['auth','inner_filter']`
Add except to `Config`? If "Yes", it looks fine.

```php
// Routes
$routes->group('', ['filter' => 'outer_filter', 'inner_filter'], function ($routes) {
    $routes->get('route1', function () {});
    $routes->get('route2', function () {});
});

// Filters
public array $globals = [
        'before' => [
            'inner_filter' => ['except' => ['route1/*', 'route2/*'],
        ],
        'after' => [
            'inner_filter' => ['except' => ['route1/*', 'route2/*'],
        ],
    ];
```
Or back, add only 100% common filters in the group. Individual set up inside.

```php
// Routes
$routes->group('', ['filter' => 'outer_filter'], function ($routes) {
    $routes->get('route1', function () {}, ['filter' => 'inner_filter']);
    $routes->get('route2', function () {}, ['filter' => 'inner_filter']);
});
```

Comment (kenjis) [reply tests/system/Router/RouteCollectionTest.php:400]: `array_merge()` replaces all filters in outer group with filters in inner group.
See the test:
https://github.com/codeigniter4/CodeIgniter4/pull/7981/files#diff-9e755caf334ca07345b43d4fdc3986ac1f9bb9594c6f78ebdec59bc780699b73R371-R400

Comment (neznaika0) [reply tests/system/Router/RouteCollectionTest.php:400]: I looked, in my opinion it's wrong. We can't fine-tune the filters any more. The same example with authorization - we want to have it for many routes, and have an additional filter inside.

Comment (neznaika0) [reply tests/system/Router/RouteCollectionTest.php:400]: 3. We want to have 1-2 outer filters and 0-5 inner.

Okay. I understand your position. If it's not necessary, I don't say anymore

Comment (kenjis) [reply tests/system/Router/RouteCollectionTest.php:400]: Sorry, I don't get what you say. What is 1-2 outer and 0-5 inner?

Do you want to put a filter in outer group and remove it in inner group?

Comment (neznaika0) [reply tests/system/Router/RouteCollectionTest.php:400]: > > @neznaika0 `$multipleFilters`was already removed in 4.5. Do you want to revert it?
> 
> How do we make exceptions when merging filters? Just ignore it?
> 
> For example, we don't need an 'outer_filter' in the group - `['auth', 'outer_filter'] >> ['auth','inner_filter']` Add except to `Config`? If "Yes", it looks fine.
> 
> ```
> // Routes
> $routes->group('', ['filter' => 'outer_filter', 'inner_filter'], function ($routes) {
>     $routes->get('route1', function () {});
>     $routes->get('route2', function () {});
> });
> 
> // Filters
> public array $globals = [
>         'before' => [
>             'outer_filter' => ['except' => ['route1/*', 'route2/*'],
>         ],
>         'after' => [
>             'outer_filter' => ['except' => ['route1/*', 'route2/*'],
>         ],
>     ];
> ```
> 
> Or back, add only 100% common filters in the group. Individual set up inside.
> 
> ```
> // Routes
> $routes->group('', ['filter' => 'outer_filter'], function ($routes) {
>     $routes->get('route1', function () {}, ['filter' => 'inner_filter']);
>     $routes->get('route2', function () {}, ['filter' => 'inner_filter']);
> });
> ```
> 
> EDIT: to `outer_filter` except

Numbers - count filters. ['filter' => '1', '2', '3'] 
0 - without filters

**Comment by kenjis** [comment]
Rebased to resolve a conflict.

File: tests/system/Router/RouteCollectionTest.php (hunk 1 above)
Comment (MGatner) [reply tests/system/Router/RouteCollectionTest.php:400]: > Why? You can control filters 100%. The rules are:
> 
> 1. outer filters are applied if you don't specify filter at all in inner group.
> 
> 2. if you want to change filters in inner group, specify all filters.

I think this is the best we can do for now, and as @kenjis noted is also the simplest implementation.

**Review by MGatner — APPROVED** [review]

File: tests/system/Router/RouteCollectionTest.php (hunk 1 above)
Comment (kenjis) [reply tests/system/Router/RouteCollectionTest.php:400]: @neznaika0 Sorry, I don't get what you mean at all.

Comment (neznaika0) [reply tests/system/Router/RouteCollectionTest.php:400]: What exactly? A message with numbers? Or "how to merge filters"?

The figures are an example of the number of filters used: from 1 to X pieces. I want to show that it is convenient to have 2 filters outside and add (or not) 5 inside. Then the routes will have from 2 to 7 filters.

In your version, it is necessary to write 2-7 filters for each router. 
 `['filter' => 'outer_filter1', 'outer_filter2', 'inner_filter1',  ..., 'inner_filter5',]`

The main purpose of the question -`array_merge_recursive($params['outer']['filter'], $params['inner']['filter'])`

Comment (kenjis) [reply tests/system/Router/RouteCollectionTest.php:400]: Thank you for explanation. I got what you say.

Yes, the options are
1. use `array_merge()` for filters
2. use `array_merge_recursive()` for filters

When you have 2 filters outside and add (or not) 5 inside, in my version,
yes, you need to specify 7 filters when you add filters in inner routes:
```php
['filter' => ['outer_filter1', 'outer_filter2', 'inner_filter1',  ..., 'inner_filter5']]
```
But none (not specify `filter` key in the option array) when you don't add filters, because the outer 2 filters will be merged.

Using `array_merge_recursive()` seems better if you never remove outer filters in inner routes.
But if you want to remove a outer filter in inner routes, there is no way.

Comment (neznaika0) [reply tests/system/Router/RouteCollectionTest.php:400]: I am very sorry for my translation. 

Yes, to exclude the outside filter, I gave an example of `except` in the **Config**. Or we need to write such a filter for all routes except unnecessary ones (this is your option)

Comment (kenjis) [reply tests/system/Router/RouteCollectionTest.php:400]: I disagree with the new feature to exclude route filters in the `Config\Filter`.
The `Config\Filter` and route filters are the same filters, but I think mixing these settings is a source of confusion.

Also, I don't like to add a new key for excluding filters in the route option.
It also is complicated.

Comment (neznaika0) [reply tests/system/Router/RouteCollectionTest.php:400]: Well, this does not cancel your method - we leave the outside filters empty and configure each route individually

Comment (kenjis) [reply tests/system/Router/RouteCollectionTest.php:400]: `Config\Filter` defines filters for URI paths, not for routes.
`except` excepts the filter to the URI path in `Config\Filter`.
https://codeigniter4.github.io/CodeIgniter4/incoming/filters.html#except-for-a-few-uris

Filters for a route are different things. If you specify a filter to a route, it is always applied.
The definitions in `Config\Filter` does nothing to route filters.

What I don't like is to mix the two kind of filters. That is, `except` in `Config\Filter` excepts route filters, too.
It is really complicated and confusing.

Comment (kenjis) [reply tests/system/Router/RouteCollectionTest.php:400]: @michalsn @neznaika0 @MGatner I changed my mind. I sent another PR #8033 that behaves like michalsn expects in https://github.com/codeigniter4/CodeIgniter4/pull/7981#discussion_r1336782260

**Comment by kenjis** [comment]
Closed by 8033
