### PR TITLE
fix: add dot_array_search to required_with and required_without

### LINKED ISSUE #3965: Bug: required_with validation rule does not work with arrays
**Describe the bug**
When using array as key in a form, `required_with` never finds the field.

**CodeIgniter 4 version**
dev-develop

**Affected module(s)**
`CodeIgniter\Validation\Rules::required_with()`

**Expected behavior, and steps to reproduce if appropriate**
With these data:
```
'contacts' => [
    'name' => 'Joe Smith',
    'friend' => 'John Doe'
]

$validation->setRules([
    'contacts.name' => 'required_with[contacts.friend]'
]);
```
`required_with` never finds `contacts.friend` because no `dot_array_search` is performed.

**Context**
 - OS: Ubuntu
 - Web server: Nginx
 - PHP version: 7.4

**Suggested correction**
in `codeigniter4/codeigniter4/system/Validation/Rules.php` (`CodeIgniter\Validation\Rules::required_with()`):
```php
	/**
	 * The field is required when any of the other required fields are present
	 * in the data.
	 *
	 * Example (field is required when the password field is present):
	 *
	 *     required_with[password]
	 *
	 * @param string|null $str
	 * @param string      $fields List of fields that we should check if present
	 * @param array       $data   Complete list of fields from the form
	 *
	 * @return boolean
	 */
	public function required_with(
		$str = null,
		string $fields,
		array $data
	): bool {
		$fields = explode(',', $fields);

		// If the field is present we can safely assume that
		// the field is here, no matter whether the corresponding
		// search field is present or not.
		$present = $this->required($str ?? '');

		if ($present) {
			return true;
		}

		// Still here? Then we fail this test if
		// any of the fields are present in $data
		// as $fields is the lis
		$requiredFields = [];

		foreach ($fields as $field) {
			if (
				(strpos($field, '.') !== false &&
					!empty(dot_array_search($field, $data))) ||
				(array_key_exists($field, $data) && !empty($data[$field]))
			) {
				$requiredFields[] = $field;
			}
		}

		return empty($requiredFields);
	}
```

### PR DESCRIPTION
**Pull request by benjaminbellamy**
Closes #3965

**Description**
Added dot_array_search to required_with and required_without so that they work when using array as key in a form.

### CODE REVIEW

File: system/Validation/Rules.php [hunk 1]
```diff
@@ -376,20 +376,16 @@ public function required_with($str = null, string $fields, array $data): bool
...
-		foreach ($fields as $field)
-		{
-			if (array_key_exists($field, $data))
-			{
+		foreach ($fields as $field) {
+			if (
+				(strpos($field, '.') !== false &&
+					!empty(dot_array_search($field, $data))) ||
+				(array_key_exists($field, $data) && !empty($data[$field]))
+			) {
```
Comment (mostafakhudair) [inline system/Validation/Rules.php:384]:
```suggestion
		foreach ($fields as $field)
		{
			if (
				(strpos($field, '.') !== false && ! empty(dot_array_search($field, $data))) ||
				(array_key_exists($field, $data) && ! empty($data[$field]))
			)
			{
```

File: system/Validation/Rules.php [hunk 2]
```diff
@@ -425,10 +421,13 @@ public function required_without($str = null, string $fields, array $data): bool
...
-		{
-			if (! array_key_exists($field, $data))
-			{
+		foreach ($fields as $field) {
+			if (
+				(strpos($field, '.') !== false &&
+					empty(dot_array_search($field, $data))) ||
+				(strpos($field, '.') === false &&
+					(!array_key_exists($field, $data) || empty($data[$field])))
+			) {
```
Comment (mostafakhudair) [inline system/Validation/Rules.php:430]:
```suggestion
		foreach ($fields as $field)
		{
			if (
				(strpos($field, '.') !== false && empty(dot_array_search($field, $data))) ||
				(strpos($field, '.') === false && (! array_key_exists($field, $data) || empty($data[$field])))
			)
			{
```

**Review by mostafakhudair — CHANGES_REQUESTED** [review]

File: system/Validation/Rules.php [hunk 3]
```diff
@@ -378,18 +378,15 @@ public function required_with($str = null, string $fields, array $data): bool
 
 		foreach ($fields as $field)
 		{
-			if (array_key_exists($field, $data))
+			if (
+				(strpos($field, '.') !== false && ! empty(dot_array_search($field, $data))) ||
+				(array_key_exists($field, $data) && ! empty($data[$field]))
```
Comment (lonnieezell) [inline system/Validation/Rules.php:383]: I think flipping the order of these two will eek out a little more performance since `empty` and `array_key_exists` and almost assuredly faster than `dot_array_search`.

File: system/Validation/Rules.php [hunk 4]
```diff
@@ -427,7 +424,10 @@ public function required_without($str = null, string $fields, array $data): bool
 		// any of the fields are not present in $data
 		foreach ($fields as $field)
 		{
-			if (! array_key_exists($field, $data))
+			if (
+				(strpos($field, '.') !== false && empty(dot_array_search($field, $data))) ||
+				(strpos($field, '.') === false && (! array_key_exists($field, $data) || empty($data[$field])))
```
Comment (lonnieezell) [inline system/Validation/Rules.php:429]: Same thing here. Please reverse the order.

**Review by lonnieezell — CHANGES_REQUESTED** [review]
I left a very nit-picky comment lol. 

Other than that, though, we do need tests in place to cover this feature before we can merge.

**Review by benjaminbellamy — COMMENTED** [review]
I switched them.

File: system/Validation/Rules.php (hunk 3 above)
Comment (benjaminbellamy) [reply system/Validation/Rules.php]: Done! (And for what it’s worth, I tested it.)

File: system/Validation/Rules.php (hunk 4 above)
Comment (benjaminbellamy) [reply system/Validation/Rules.php]: Done!

**Comment by paulbalandan** [comment]
@benjaminbellamy the tests Lonnie referred here are not local tests but the PHPUnit tests. You should add new tests to the existing tests to see that this fix is working as intended.

**Comment by benjaminbellamy** [comment]
> @benjaminbellamy the tests Lonnie referred here are not local tests but the PHPUnit tests. You should add new tests to the existing tests to see that this fix is working as intended.

Done!

**Review by paulbalandan — APPROVED** [review]
@benjaminbellamy  thank you
