### PR TITLE
fix: FeatureTestTrait may change $params values passed to call(), and a few bug fixes

### LINKED ISSUE #7593: Bug: Test feature change value passed in params
### PHP Version

8.1

### CodeIgniter4 Version

4.3.4

### CodeIgniter4 Installation Method

Manual (zip or tar.gz)

### Which operating systems have you tested for this bug?

macOS

### Which server did you use?

apache

### Database

PostgreSQL 15.2

### What happened?

When a `boolean` is  passed as the body to the `call` testing feature params, the value is changed as `string` value
When a `integer` is passed  as the body to the `call` testing feature params, the value is changed as `string` value

### Steps to Reproduce

In the `FeatureTestTrait`
```php
$response = $this->withBodyFormat('json')->call('put', "put/uri", [
    'value1' => true,
    'value2' => false,
    'value3' => 2,
]);
```

In the controller
```php
dd($this->request->getJsonVar());
```

will log
```
stdClass#1912 (2) (
    public 'value1' -> string (1) "1"
    public 'value2' -> string (1) ""
    public 'value3' -> string (1) "2"
)
```

### Expected Output

should log
```
stdClass#1912 (2) (
    public 'value1' -> bool true
    public 'value2' -> bool false
    public 'value3' -> int 2
)
```

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by kenjis**
**Description**
Fixes #7593

- fix: when you call `withBodyFormat('json')` and pass `$params` to `call()`,  the values in  `$params` is converted to string.
- fix: REQUEST global is set with a JSON/XML request
   - $_REQUEST = $_POST + $_GET. It should be empty if it is a JSON/XML request.
- fix: when calling `withBody()` and `withBodyFormat()`, `Content-Type` is not set
- fix: [BC] change priority for request body
   - When you call `withBody($body)->withBodyFormat('json')->call('post', $param)`, `$param` is used for the request body from now on. Previously, `$body` was used.

**Checklist:**
- [x] Securely signed commits
- [x] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [x] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Comment by iRedds** [comment]
I would like to point out the incorrect handling of request parameters.
`FeatureTestTrait::populateGlobals()` method.
https://github.com/codeigniter4/CodeIgniter4/blob/52a2372addeb071f7deeb8418051554e2fba4149/system/Test/FeatureTestTrait.php#L341-L343

There are only two superglobal arrays that contain request data - _GET and _POST. 
That is, for example, for `$this->call('put', [...])`, this code should not be executed.

https://github.com/codeigniter4/CodeIgniter4/blob/52a2372addeb071f7deeb8418051554e2fba4149/system/Test/FeatureTestTrait.php#L345
The _REQUEST array will be populated if the request contains a query string and/or if the POST request was submitted with the content type `application/x-www-form-urlencoded` or `multipart/form-data`.
$_REQUEST = $_POST + $_GET;
In all other cases, _REQUEST must be empty.

I think it should look something like this.
```php
// regex is just for example.
if (
    $method == 'post'
    && ! empty($params)
    || ($this->bodyFormat === '' && preg_match('#^(.+=.+&?)+$#', $this->requestBody)) // a=b&c=d
) {
    if (empty($params) && preg_match('#^(.+=.+&?)+$#', $this->requestBody)) {
        parse_str($this->requestBody, $params);
    }

    $request->setGlobal('post', $params);
}

$request->setGlobal('request', $request->fetchGlobal('post') + $get);
```

`FeatureTestTrait::setRequestBody()` method.
https://github.com/codeigniter4/CodeIgniter4/blob/52a2372addeb071f7deeb8418051554e2fba4149/system/Test/FeatureTestTrait.php#L369-L371
This code doesn't make sense. Since _REQUEST will (should) be empty due to the above incorrect behavior.
And if the `$params` variable is empty, we can simply return the Request object.

**Comment by kenjis** [comment]
@iRedds Fixed the code except parsing the body and setting the POST global.

The behavior of parsing the body and setting the POST global in the case of POST request is legitimate. 
However, I don't think it is necessary to bother writing such test code.
Because we can use the `$params` of `call()`.

**Comment by iRedds** [comment]
@kenjis thanks for your work.

**Comment by kenjis** [comment]
Can someone please review this?

File: tests/system/Test/FeatureTestTraitTest.php [hunk 1]
```diff
@@ -358,6 +358,162 @@ public function testIsOkWithRedirects()
...
+
+        $response->assertOK();
+        $this->assertStringContainsString(
+            // All GET values will be strings.
+            '{"true":"1","false":"","int":"2","null":"","float":"1.23","string":"foo"}',
+            $response->getBody()
+        );
+    }
+
+    public function testCallGetWithParamsAndREQEST()
```
Comment (MGatner) [inline tests/system/Test/FeatureTestTraitTest.php:388]:
```suggestion
    public function testCallGetWithParamsAndREQUEST()
```

**Review by MGatner — CHANGES_REQUESTED** [review]
One typo but otherwise looks great!

File: tests/system/Test/FeatureTestTraitTest.php (hunk 1 above)
Comment (kenjis) [reply tests/system/Test/FeatureTestTraitTest.php]: Thanks. Done.

**Review by MGatner — APPROVED** [review]
