### PR TITLE
fix: Casting in insertBatch and updateBatch methods.

### LINKED ISSUE #9695: Bug: Casting happens in insert but not in insertBatch
### PHP Version

8.4

### CodeIgniter4 Version

4.6.3

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

macOS

### Which server did you use?

apache

### Database

MariaDB 10.4.28

### What happened?

When using `Model->insert()` command, casting (eg. converting of array type to json encoded array) happens. But when using `Model->insertBatch()` command, casting of each row doesn't happen.

### Steps to Reproduce

Create a table with atleast one column that stores json encoded values (i.e, of type TEXT, MEDIUMTEXT, LONGTEXT, etc.). Inside model, set the `$cast` of that column to type `array`. Then, fire up `Model->insertBatch()` command and for each row, pass an array (not string) for that model. The insert command will not insert values to DB.

### Expected Output

The `insertBatch` should perform the casting on each row similar to that done in `insert` command.

### Anything else?

I think I can contribute this but I don't know where to start. I mean, are there any specific things I need to setup before/after making changes or other things like that or just sending PR containing signed commits would suffice?

### PR DESCRIPTION
**Pull request by patel-vansh**
**Description**
This PR fixes the bug where casting was not performed on the rows during `insertBatch()` and `updateBatch()` methods inside `BaseModel` file.

Fixes #9695.

**Checklist:**
- [x] Securely signed commits
- [ ] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [x] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

File: system/BaseModel.php [hunk 1]
```diff
@@ -909,6 +909,19 @@ public function insertBatch(?array $set = null, ?bool $escape = null, int $batch
 
         if (is_array($set)) {
             foreach ($set as &$row) {
+                // If casts are used, convert the data first
```
Comment (michalsn) [inline system/BaseModel.php]: In line 928, please change `if` to `elseif`.

File: system/BaseModel.php [hunk 2]
```diff
@@ -1051,6 +1064,19 @@ public function updateBatch(?array $set = null, ?string $index = null, int $batc
     {
         if (is_array($set)) {
             foreach ($set as &$row) {
+                // If casts are used, convert the data first
+                if ($this->useCasts()) {
```
Comment (michalsn) [inline system/BaseModel.php]: In line 1083, please change `if` to `elseif`.

File: tests/system/Models/InsertModelTest.php [hunk 3]
```diff
@@ -376,4 +377,55 @@ public function testInsertWithDefaultValue(): void
...
+                    'work' => 'rahul@company123.com'
+                ],
+                'country' => 'India',
+            ]
+        ];
+        $this->createModel(UserCastsTimestampModel::class);
+
+        $numRows = $this->model->insertBatch($userData);
+
+        $this->assertSame(2, $numRows);
```
Comment (michalsn) [inline tests/system/Models/InsertModelTest.php:405]: Can we add a check with `$this->seeInDatabase()` - this would be enough for me to prove the data was properly inserted using the given casting.

File: tests/system/Models/InsertModelTest.php [hunk 4]
```diff
@@ -376,4 +377,55 @@ public function testInsertWithDefaultValue(): void
...
+        $this->assertSame('Smriti', $smriti['name']);
+        $this->assertIsArray($smriti['email']);
+        $this->assertSame('smriti@india.com', $smriti['email']['personal']);
+        $this->assertSame('smriti@company.com', $smriti['email']['work']);
+
+        // Check Rahul
+        $this->assertSame('Rahul', $rahul['name']);
+        $this->assertIsArray($rahul['email']);
+        $this->assertSame('rahul123@india.com', $rahul['email']['personal']);
+        $this->assertSame('rahul@company123.com', $rahul['email']['work']);
```
Comment (michalsn) [inline tests/system/Models/InsertModelTest.php]: This is not necessary, if we do a check with `$this->seeInDatabase()`.

File: tests/system/Models/UpdateModelTest.php [hunk 5]
```diff
@@ -602,4 +603,86 @@ public function testUpdateEntityUpdateOnlyChangedFalse(): void
         $this->assertTrue($result);
         $this->assertNotSame($updateAtBefore, $updateAtAfter);
     }
+
+    public function testUpdateBatchWithCasts(): void
```
Comment (michalsn) [inline tests/system/Models/UpdateModelTest.php:607]: Can we simplify this test by grabbing existing data from the user table and then using model, to `updateBatch` the data? Again, the simple check `$this->seeInDatabase()` will be enough for the confirmation of proper data casting.

**Review by michalsn — CHANGES_REQUESTED** [review]
To fix code style problems, simply run: `composer cs-fix`.

After making changes as suggested in my comments, you can run checks: `composer sa`, and see if there are still any problems. If you don't know how to fix them, please push the changes, and we will try to investigate.

File: tests/system/Models/InsertModelTest.php (hunk 4 above)
Comment (patel-vansh) [reply tests/system/Models/InsertModelTest.php]: I tried using the `$this->seeInDatabase()` function, but the problem there occurred was that the `where` statement that is performed under the `seeInDatabase` function doesn't use casting, and since the `name` column has `base64` casting, no rows are returned.

Hence `$this->seeInDatabase('user', ['name' => 'Smriti'])` is not returning any rows. (I don't know if its a bug or not).

So, I think there may be two ways, one is done already. And other one is using `$this->seeInDatabase('user', ['country' => 'India'])`, since country column is normal string.

If checking country is okay, then I would surely do that.
Thanks.

File: tests/system/Models/UpdateModelTest.php (hunk 5 above)
Comment (patel-vansh) [reply tests/system/Models/UpdateModelTest.php:607]: Is data already there inside the table? I didn't find any reference for existing data, hence I thought that I would have to insert it.

If it already exists, then I think there is no need of inserting it again.

Thanks.

File: system/BaseModel.php (hunk 2 above)
Comment (patel-vansh) [reply system/BaseModel.php]: Done.

File: system/BaseModel.php (hunk 1 above)
Comment (patel-vansh) [reply system/BaseModel.php]: Done.

File: tests/system/Models/InsertModelTest.php (hunk 4 above)
Comment (michalsn) [reply tests/system/Models/InsertModelTest.php]: > Hence $this->seeInDatabase('user', ['name' => 'Smriti']) is not returning any rows. (I don't know if its a bug or not).

This is because `name` also has a cast defined. You can use something like this to ensure that the record is saved in the desired format:

```php
$this->seeInDatabase('user', ['email'  => json_encode($userData[0]['email'])]);
```

File: tests/system/Models/UpdateModelTest.php (hunk 5 above)
Comment (michalsn) [reply tests/system/Models/UpdateModelTest.php:607]: There is some data set in the seeder file: https://github.com/codeigniter4/CodeIgniter4/blob/develop/tests/_support/Database/Seeds/CITestSeeder.php#L24

Just grab the first two rows and update them. Then check the result with: `$this->seeInDatabase()`.

Comment (patel-vansh) [reply tests/system/Models/UpdateModelTest.php:607]: I think the seeds in the db are not consistent with the cast. Currently, the user table seeds have email column normal string, but `$casts` says that it should be json, so, if I am using `findAll()` method, its failing with following stack trace.
```
Runtime:       PHP 8.4.12 with PCOV 1.0.12
Configuration: /Users/username/Projects/CodeIgniter4/phpunit.xml.dist

................SS.....E                                                                                                                                                                                                  24 / 24 (100%)

Time: 00:00.380, Memory: 18.00 MB

There was 1 error:

1) CodeIgniter\Models\UpdateModelTest::testUpdateBatchWithCasts
CodeIgniter\DataCaster\Exceptions\CastException: Syntax error, malformed JSON.

/Users/username/Projects/CodeIgniter4/system/Entity/Exceptions/CastException.php:50
/Users/username/Projects/CodeIgniter4/system/DataCaster/Cast/JsonCast.php:44
/Users/username/Projects/CodeIgniter4/system/DataCaster/DataCaster.php:185
/Users/username/Projects/CodeIgniter4/system/DataConverter/DataConverter.php:80
/Users/username/Projects/CodeIgniter4/system/BaseModel.php:1964
/Users/username/Projects/CodeIgniter4/system/Model.php:291
/Users/username/Projects/CodeIgniter4/system/BaseModel.php:677
/Users/username/Projects/CodeIgniter4/tests/system/Models/UpdateModelTest.php:611
```

So, should the seeds need to be updated or just insert new data as done initially?

File: tests/system/Models/InsertModelTest.php (hunk 4 above)
Comment (patel-vansh) [reply tests/system/Models/InsertModelTest.php]: Done.

File: tests/system/Models/UpdateModelTest.php (hunk 5 above)
Comment (michalsn) [reply tests/system/Models/UpdateModelTest.php:607]: Just don't grab the data using this model. Use it only for updates.

```php
$this->db->table('user')->limit(2)->orderBy('id', 'asc')->get()->getResultArray()
```

Comment (patel-vansh) [reply tests/system/Models/UpdateModelTest.php:607]: Done. Please check

**Comment by patel-vansh** [comment]
Hello @michalsn, I see there are two checks failing. I don't know how to fix them, can you please guide me?

I think the copy-paste detection check can be solved by creating a new function (if its okay to introduce a new function).

For the other check, I really can't see where its going wrong.

Thanks for you help.

File: tests/system/Models/InsertModelTest.php [hunk 6]
```diff
@@ -376,4 +377,34 @@ public function testInsertWithDefaultValue(): void
...
+                'email' => [
+                    'personal' => 'rahul123@india.com',
+                    'work'     => 'rahul@company123.com',
+                ],
+                'country' => 'India',
+            ],
+        ];
+        $this->createModel(UserCastsTimestampModel::class);
+
+        $numRows = $this->model->insertBatch($userData);
```
Comment (michalsn) [inline tests/system/Models/InsertModelTest.php]:
```suggestion
        $numRows = $this->model->insertBatch($userData); // @phpstan-ignore argument.type
```

File: tests/system/Models/UpdateModelTest.php [hunk 7]
```diff
@@ -602,4 +603,43 @@ public function testUpdateEntityUpdateOnlyChangedFalse(): void
...
+            [
+                'id'    => $row2['id'],
+                'email' => [
+                    'personal' => 'email2.new@country.com',
+                    'work'     => 'email2.new@company.com',
+                ],
+            ],
+        ];
+
+        $numRows = $this->model->updateBatch($updateData, 'id');
```
Comment (michalsn) [inline tests/system/Models/UpdateModelTest.php]:
```suggestion
        $numRows = $this->model->updateBatch($updateData, 'id'); // @phpstan-ignore argument.type
```

Comment (patel-vansh) [reply tests/system/Models/UpdateModelTest.php]: Done.

File: tests/system/Models/InsertModelTest.php (hunk 6 above)
Comment (patel-vansh) [reply tests/system/Models/InsertModelTest.php]: Done.

**Comment by patel-vansh** [comment]
I've created a protected `performCasting` function which does casting.

**Comment by michalsn** [comment]
Instead of using `performCasting()`, please try the approach below. Abstracting only a small portion of the transformation feels unnecessary, especially for a temporary method.

```php
protected function transformDataRowToArray(array $row): array
{
    if ($this->useCasts()) {
        if (is_array($row)) {
            $row = $this->converter->toDataSource($row);
        } elseif ($row instanceof stdClass) {
            $row = (array) $row;
            $row = $this->converter->toDataSource($row);
        } elseif ($row instanceof Entity) {
            $row = $this->converter->extract($row);
        } elseif (is_object($row)) {
            $row = $this->converter->extract($row);
        }
    } elseif (is_object($row) && ! $row instanceof stdClass) {
        $row = $this->objectToArray($row, false, true);
    }

    if (is_object($row)) {
        $row = (array) $row;
    }

    return $this->timeToString($row);
}
```

**Comment by patel-vansh** [comment]
I've made requested changes. Also, retained comments.

**Comment by michalsn** [comment]
Thank you @patel-vansh
