### PR TITLE
fix: make Time::__toString() database-compatible on any locale

### LINKED ISSUE #6439: make Time object usable with QueryBuilder in all locales
### PHP Version

8.0

### CodeIgniter4 Version

`develop` (799d6558187669a847f5ac573226e2e1ef6a31f6)

### CodeIgniter4 Installation Method

Git

### Which operating systems have you tested for this bug?

macOS

### Which server did you use?

cli

### Database

_No response_

### What happened?

In locale fa, cannot use `Time` object with QueryBuilder.

The following code generates the query  like `UPDATE "users" SET "last_active" = '۲۰۲۲-۰۸-۲۹ ۱۳:۰۰:۰۰' WHERE "id" = 1`.
And it results in database query error.

```php
        Locale::setDefault('fa');

        $builder = new BaseBuilder('users', $this->db);

        $time = Time::parse('2022-08-29 13:00');
        $builder->testMode()->set('last_active', $time)->where('id', 1)->update();
        $sql = $builder->getCompiledUpdate();
```

### Steps to Reproduce

See above.

### Expected Output

Generates `UPDATE "users" SET "last_active" = '2022-08-29 13:00:00' WHERE "id" = 1`.

### Anything else?

_No response_

### PR DESCRIPTION
**Pull request by kenjis**
**Description**
Closes #6439
Supersedes #6456

In this PR, `Time::__toString()` no longer depends on locale.
It always returns database-compatible string like `'2016-03-09 12:00:00'`.

In the current implementation, the `__toString()` output will be changed by the locale.
(But it seems it is not documented in the User Guide.)
It causes database query error in a few locale.

Time is localized class, but `__toString()` does not need to return localized value.
If a dev needs localized string, they can call [toDateTimeString()](https://codeigniter4.github.io/CodeIgniter4/libraries/time.html#todatetimestring).

Implicitly changing behavior depending on locale is a bad practice because it confuses developers.
`__toString()` is a standard PHP method, not a localized helper method. 
The  return value should be database-compatible.

**Checklist:**
- [x] Securely signed commits
- [x] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [x] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Comment by MGatner** [comment]
I think this is the way to go. Since that format is very clearly "database DateTime" I expect the intent was always to have the Stringable be database-compatible.

**Review by MGatner — APPROVED** [review]

File: tests/system/I18n/TimeTest.php [hunk 1]
```diff
@@ -1139,4 +1139,25 @@ public function testSetTestNowWithFaLocale()
 
         Locale::setDefault($currentLocale);
     }
+
+    /**
+     * @dataProvider provideLocales
+     */
+    public function testToStringDoesNotDependOnLocale(string $locale)
```
Comment (datamweb) [inline tests/system/I18n/TimeTest.php:1146]:
```suggestion
    public function testToStringDoesNotDependOnLocale(string $locale): void
```

File: tests/system/I18n/TimeTest.php [hunk 2]
```diff
@@ -1139,4 +1139,25 @@ public function testSetTestNowWithFaLocale()
...
+        $time = new Time('2017/03/10 12:00');
+
+        $this->assertSame('2017-03-10 12:00:00', (string) $time);
+    }
+
+    public function provideLocales(): Generator
+    {
+        yield from [
+            ['en'],
+            ['de'],
```
Comment (datamweb) [inline tests/system/I18n/TimeTest.php:1159]:
```suggestion
            ['de'],
            ['ar'],
```

**Review by datamweb — CHANGES_REQUESTED** [review]

File: tests/system/I18n/TimeTest.php (hunk 1 above)
Comment (kenjis) [reply tests/system/I18n/TimeTest.php:1143]: I did not add `void` because the code in this repository often does not have it.
No other test methods of this class have void.

Probably in the future, when we do a major version upgrade, we will add it with php-cs-fixer.

**Comment by kenjis** [comment]
Added the docs.

File: tests/system/I18n/TimeTest.php (hunk 1 above)
Comment (datamweb) [reply tests/system/I18n/TimeTest.php:1143]: Okay, Thanks👍

File: user_guide_src/source/changelogs/v4.2.7.rst [hunk 3]
```diff
@@ -12,7 +12,7 @@ Release Date: Unreleased
 BREAKING
 ********
 
-none.
+-  ``Time::__toStrong()`` is now locale-independent. It returns database-compatible strings like '2022-09-07 12:00:00' in any locale.
```
Comment (paulbalandan) [inline user_guide_src/source/changelogs/v4.2.7.rst:15]:
```suggestion
-  ``Time::__toString()`` is now locale-independent. It returns database-compatible strings like '2022-09-07 12:00:00' in any locale.
```

File: user_guide_src/source/installation/upgrade_427.rst [hunk 4]
```diff
@@ -0,0 +1,33 @@
...
+- :ref:`Manual Installation Upgrading <installing-manual-upgrading>`
+
+.. contents::
+    :local:
+    :depth: 2
+
+Breaking Changes
+****************
+
+-  ``Time::__toStrong()`` is now locale-independent. It returns database-compatible strings like '2022-09-07 12:00:00' in any locale. Most locales are not affected by this change. But in a few locales like `ar`, `fa`, ``Time::__toStrong()`` (or ``(string) $time`` or implicit casting to a string) no longer returns a localized datetime string. if you want to get a localized datetime string, use :ref:`Time::toDateTimeString() <time-todatetimestring>` instead.
```
Comment (paulbalandan) [inline user_guide_src/source/installation/upgrade_427.rst:18]:
```suggestion
-  ``Time::__toString()`` is now locale-independent. It returns database-compatible strings like '2022-09-07 12:00:00' in any locale. Most locales are not affected by this change. But in a few locales like `ar`, `fa`, ``Time::__toString()`` (or ``(string) $time`` or implicit casting to a string) no longer returns a localized datetime string. if you want to get a localized datetime string, use :ref:`Time::toDateTimeString() <time-todatetimestring>` instead.
```

**Review by paulbalandan — APPROVED** [review]

File: tests/system/I18n/TimeTest.php (hunk 1 above)
Comment (kenjis) [reply tests/system/I18n/TimeTest.php:1143]: I mean in test classes.
If we add a new public method, we should add parameter/return type.

**Review by MGatner — APPROVED** [review]

**Review by datamweb — APPROVED** [review]
**Kenjis**, I know you have sent several PRs to solve this problem and finally here we are.
 It works fine now. 
Thanks.

**Comment by kenjis** [comment]
Thank you all!

**Comment by kenjis** [comment]
🎉 
I think this will prevent us from producing broken code that causes a database error only if the locale is fa or ar.
