### PR TITLE
fix: Commands::discoverCommands() loads incorrect classname

### LINKED ISSUE #5818: Bug: defining new namespace under `app/` causes `Cannot declare class ..., because the name is already in use`
### PHP Version

8.0

### CodeIgniter4 Version

v4.1.9

### CodeIgniter4 Installation Method

Composer (using `codeigniter4/appstarter`)

### Which operating systems have you tested for this bug?

Windows

### Which server did you use?

apache

### Database

--

### What happened?

Problem in command `php spark make:command --namespace MyNameSpace`

### Steps to Reproduce

> `composer create-project codeigniter4/appstarter project-root`
```
    public $psr4 = [
        'MyNameSpace' 	        => APPPATH . 'ThirdParty\MyFolder',
    ];
```
`php spark make:command --namespace MyNameSpace`

Command class name : TeseCommand 
_File created: APPPATH\ThirdParty\MyFolder\Commands\TeseCommand.php_

Everything is done well.
The corresponding file is created.
But now typing command `php spark` displays the following error!
```
PHP Fatal error:  Cannot declare class MyNameSpace\Commands\TeseCommand, because the name is already in use in P:\Program\xampp8010\htdocs\cimc\app\ThirdParty\MyFolder\Commands\TeseCommand.php on line 8

[ErrorException]

Cannot declare class MyNameSpace\Commands\TeseCommand, because the name is already in use

at APPPATH\ThirdParty\MyFolder\Commands\TeseCommand.php:8
```

### Expected Output

@paulbalandan , @kenjis  need to check to fix the problem. Please check.

### Anything else?

This problem only exists in the installation method through **composer** .
This problem does **not** exist in the **manual installation** method.

### PR DESCRIPTION
**Pull request by kenjis**
**Description**
Fixes #5818
Supersedes #5834

- fix: FileLocator::listFiles() returns directories
- fix: discoverCommands() loads incorrect classname

Cannot write a unit test for `Cannot declare class ..., because the name is already in use`. 
To check manually using this repo:
1. Add `"App\\": "app/"` in the `autoload.psr4` section in the root composer.json
2. Run `composer dump -o` to regenerate the class map.
3. Add `'MyNameSpace' => APPPATH . 'ThirdParty/MyFolder'` in `Config\Autoload::$psr4` array.
4. Run `php spark make:command TeseCommand --namespace MyNameSpace`
5. Run `php spark`. This will now error.
6. Check out this PR branch (`fix-discoverCommands`).
7. Run `php spark`. No errors should appear.

**Checklist:**
- [x] Securely signed commits
- [x] Component(s) with PHPDoc blocks, only if necessary or adds value
- [ ] Unit testing, with >80% coverage
- [ ] User guide updated
- [x] Conforms to style guide

### CODE REVIEW

**Comment by paulbalandan** [comment]
This PR basically does two parts:
1. Removes the directories generated by `get_filenames()`; and
2. Uses `$locator->getClassName()` instead of `$locator->findQualifiedNameFromPath()`.

In 2, I understand the change will be more "intelligent" as it no longer guesses the class name from the path but rather checks the file itself to get the class name. This is +1 for me.

For 1, I don't understand why the need to filter out the directories? Maybe because the method is `listFiles()`. Well, that makes sense then.

**Comment by kenjis** [comment]
@paulbalandan 
> For 1, I don't understand why the need to filter out the directories? Maybe because the method is listFiles(). Well, that makes sense then.

Very simple. If it contains directories, spark does not work.

```
$ php spark

CodeIgniter v4.1.9 Command Line Tool - Server Time: 2022-04-02 18:32:08 UTC-05:00


[ErrorException]

file_get_contents(): Read of 8192 bytes failed with errno=21 Is a directory

at SYSTEMPATH/Autoloader/FileLocator.php:115

Backtrace:
  1    [internal function]
       CodeIgniter\Debug\Exceptions()->errorHandler(8, 'file_get_contents(): Read of 8192 bytes failed with errno=21 Is a directory', '/Users/kenji/work/codeigniter/CodeIgniter4/system/Autoloader/FileLocator.php', 115)

  2    SYSTEMPATH/Autoloader/FileLocator.php:115
       file_get_contents('/Users/kenji/work/codeigniter/CodeIgniter4/system/Commands/Cache')

  3    SYSTEMPATH/CLI/Commands.php:99
       CodeIgniter\Autoloader\FileLocator()->getClassname('/Users/kenji/work/codeigniter/CodeIgniter4/system/Commands/Cache')

  4    SYSTEMPATH/CLI/Commands.php:46
       CodeIgniter\CLI\Commands()->discoverCommands()

  5    SYSTEMPATH/Config/Services.php:159
       CodeIgniter\CLI\Commands()->__construct()

  6    SYSTEMPATH/Config/BaseService.php:251
       CodeIgniter\Config\Services::commands(false)

  7    SYSTEMPATH/Config/BaseService.php:192
       CodeIgniter\Config\BaseService::__callStatic('commands', [...])

  8    SYSTEMPATH/Config/Services.php:156
       CodeIgniter\Config\BaseService::getSharedInstance('commands')

  9    SYSTEMPATH/Config/BaseService.php:251
       CodeIgniter\Config\Services::commands()

 10    SYSTEMPATH/CLI/CommandRunner.php:35
       CodeIgniter\Config\BaseService::__callStatic('commands', [])

 11    SYSTEMPATH/CodeIgniter.php:857
       CodeIgniter\CLI\CommandRunner()->__construct()

 12    SYSTEMPATH/CodeIgniter.php:458
       CodeIgniter\CodeIgniter()->createController()

 13    SYSTEMPATH/CodeIgniter.php:346
       CodeIgniter\CodeIgniter()->handleRequest(null, Object(Config\Cache), false)

 14    SYSTEMPATH/CLI/Console.php:48
       CodeIgniter\CodeIgniter()->run()

 15    ROOTPATH/spark:79
       CodeIgniter\CLI\Console()->run()
```

File: system/Autoloader/FileLocator.php [hunk 1]
```diff
@@ -309,6 +311,9 @@ public function listFiles(string $path): array
 
             $tempFiles = get_filenames($fullPath, true);
 
+            // Remove directories
+            $tempFiles = array_filter($tempFiles, static fn ($path) => strtolower(substr($path, -4)) === '.php');
```
Comment (paulbalandan) [inline system/Autoloader/FileLocator.php:315]: Why not use the `is_file` check?

**Comment by paulbalandan** [comment]
> Very simple. If it contains directories, spark does not work.

Ah, yes! I missed the `file_get_contents`.

File: system/Autoloader/FileLocator.php (hunk 1 above)
Comment (kenjis) [reply system/Autoloader/FileLocator.php:315]: `is_file()` is slower. It needs file system access.

```php
            // Remove directories
            timer('rmdir');
            for ($i = 0; $i < 10000; $i++) {
                $tempFiles = array_filter($tempFiles, static fn ($path) => is_file($path));
//                $tempFiles = array_filter($tempFiles, static fn ($path) => strtolower(substr($path, -4)) === '.php');
            }
            timer('rmdir');
            echo timer()->getElapsedTime('rmdir');
            exit;
```

is_file(): 3.3436
substr(): 1.5712

Comment (kenjis) [reply system/Autoloader/FileLocator.php:315]: I think it is better that `get_filenames()` returns only files without directories.

**Review by paulbalandan — APPROVED** [review]
